### ISSUE TITLE
Add a welcome bot to the repo.

### ISSUE THREAD

**Issue by hr1shu** [prathimacode-hub/Awesome_Python_Scripts#100]
It'll be a beautiful message-sender and will serve as a bot for this repo.

**Comment by hr1shu** [comment]
Yeah, as I'm working on another issue first, @Jyoti6828 you can ask the mentor in the slack community for the same.

**Comment by prathimacode-hub** [comment]
You should never close the issues from your end @hr1shu

**Comment by prathimacode-hub** [comment]
@Jyoti6828 You have raised an issue for AQI prediction. Kindly give a response to that issue.

**Comment by hr1shu** [comment]
> You should never close the issues from your end @hr1shu

Sry, it'll not happen again!!

**Comment by prathimacode-hub** [comment]
That's ok, mistakes do happen. It doesn't matter much but yeah i'm letting you know it. @hr1shu
