### ISSUE TITLE
Scale Chart for Musical Compostion

### ISSUE THREAD

**Issue by theshredbox** [prathimacode-hub/Awesome_Python_Scripts#1004]
The project aims at building a dynamic scale chart for guitar that displays the notes to be played on a virtual fretboard.
Module Description- GUI built using Tkinter

Hacktoberfest '21 Participant

Repo- GUI Scripts

**Comment by prathimacode-hub** [comment]
Also mention that you're contributing as a part of hacktoberfest. @theshredbox

**Comment by prathimacode-hub** [comment]
Issue assigned to @theshredbox

**Comment by prathimacode-hub** [comment]
By when are you expected to do? Fest is about to end? @theshredbox

**Comment by theshredbox** [comment]
Ma'am you have already merged the PR. I guess I forgot to mention the issue number in the PR. My bad. Sincere apologies ma'am. I have completed 5 PRs for the fest and have successfully completed Hacktoberfest'21.

**Comment by theshredbox** [comment]
You can close the issue 😄

**Comment by prathimacode-hub** [comment]
Great might be. My bad then. Lots to remember and low on storage. Haha. 😀@theshredbox
