### ISSUE TITLE
Google Meet Automation

### ISSUE THREAD

**Issue by Knighthawk-Leo** [prathimacode-hub/Awesome_Python_Scripts#1007]
## Google Meet Automation Script
It is as simple as it's name it will help a student to plan his online class time table and this script will help him to attend the online classes ontime.
So no need to check the time table again n again.
No need to find the joining link again n again.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Knighthawk-Leo

**Comment by prathimacode-hub** [comment]
When are you expected to do? Fest is about to end. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
Ma'am Can you Review the PR @prathimacode-hub
