### ISSUE TITLE
Password Checker script

### ISSUE THREAD

**Issue by hr1shu** [prathimacode-hub/Awesome_Python_Scripts#101]
This python script checks how many times your password has been pawned or had been under hacker radars.
I've used a paid API of the website: https://haveibeenpwned.com/

**Comment by prathimacode-hub** [comment]
Oh, that's great. Kindly follow the issue template to get it assigned. It's to know you are an LGM-SOC participant. To know how template looks like, you can check with other assigned issues. You can work on only 1 issue at a time. And is that welcome bot a python script? @hr1shu

**Comment by hr1shu** [comment]
Title: Password_Checker Script
About: I will try to implement a Python Script that checks how many times your password has been pawned or had been under hacker radars.
Name: Rishav Kumar
Label: 
Assignee: ''

Define You:
 LGM-SOC'21 Participant
 
Describe the solution you'd like...
I will use the API of the website: https://haveibeenpwned.com/, and my Python knowledge to implement it.

**Comment by prathimacode-hub** [comment]
Great, this issue is assigned to you. @hr1shu

**Comment by hr1shu** [comment]
> Oh, that's great. Kindly follow the issue template to get it assigned. It's to know you are an LGM-SOC participant. To know how template looks like, you can check with other assigned issues. You can work on only 1 issue at a time. And is that welcome bot a python script? @hr1shu

Welcome bot is an app by github under Probot feature, I'll get back on this after #101 issue.

**Comment by prathimacode-hub** [comment]
Good to know. @hr1shu
