### ISSUE TITLE
Image Distortion Correction Using OpenCV

### ISSUE THREAD

**Issue by theshredbox** [prathimacode-hub/Awesome_Python_Scripts#1010]
---
Title: Image Distortion Correction Using OpenCV
About: The project aims at calculating the distortion coefficients of a given set of images to aid camera calibration
Name: YourName
Label: Feature Request
Assignee: <code>https://github.com/prathimacode-hub</code>

---

Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Digital equipment can capture images at resolutions and with detail that far surpasses the human vision system. Computers can also detect and measure the difference between colors with very high accuracy. But making sense of the content of those images is a problem that computers have been struggling with for decades. To a computer, the above picture is an array of pixels, or numerical values that represent colors.

**Describe the solution you'd like...**
* Camera calibration is the process of estimating intrinsic and/or extrinsic parameters. Intrinsic parameters deal with the camera's internal characteristics, such as, its focal length, skew, distortion, and image center. While, extrinsic parameters describe its position and orientation in the world. 
* The goal of the process is to find the 3×3 matrix K, the 3×3 rotation matrix \mathbf{R}, and the 3×1 translation vector \mathbf{t} using a set of known 3D points (X_w, Y_w, Z_w) and their corresponding image coordinates (u, v). When we get the values of intrinsic and extrinsic parameters the camera is said to be calibrated.

**Describe alternatives you've considered?**

The project can also be used to make other image processing functions to improve the image quality.

**Additional context**
MODULE USED- OPENCV
The cross-platform and open-source library plays a significant role when it comes to the growth of computer vision due to several intuitive factors. With its focus on real-time vision, this library assists students, professionals, and researchers in efficiently implementing computer vision projects, as it provides them with robust machine learning infrastructure which was previously available only in a few mature research labs.

**Comment by prathimacode-hub** [comment]
Issue assigned to @theshredbox for documentation
