### ISSUE TITLE
Empty Folder Cleaner

### ISSUE THREAD

**Issue by dark-coder-cat** [prathimacode-hub/Awesome_Python_Scripts#1011]
**Empty Folder Cleaner**
--
made with `Python3` could remove all empty folders in system. Works for **Android** and **Windows** both.
`( only the folders system allows, not like [android/] [C://system32] etc. folders)`
- --
- No any additional packages required to install. 
 `Only used built-in modules used like system, platform and time. `
- It is a Command line based program.
- To run on Android i used Pydroid3.

- --
Repo - `BasicPythonScripts`
Repo Folder - `Empty Folder Cleaner`
Hacktober fest ' 21 participant
--
**`Plz assign me this issue😀`**
--

**Comment by prathimacode-hub** [comment]
Issue assigned to @dark-coder-cat
