### ISSUE TITLE
Add SMS sending script

### ISSUE THREAD

**Issue by advaita-saha** [prathimacode-hub/Awesome_Python_Scripts#1013]
python script using kaleyra API to run sms campaign for businesses and also for individuals
Kaleyra is the leading SMS service provided in the industry

I want to contribute this Script. Please assign me this task @prathimacode-hub

**Comment by advaita-saha** [comment]
---
Title: Kaleyra auto SMS
About: python script using kaleyra API to run sms campaign for businesses and also for individuals
Name: Advaita Saha
Label: Feature Request
---

Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

This script solves the problem people have while running SMS campaign using Kaleyra API. This script provides a simple CLI to send SMS and run bulk campaign

**Comment by advaita-saha** [comment]
@neelshah2409 please assign me this one

**Comment by prathimacode-hub** [comment]
Issue assigned to @advaita-saha
