### ISSUE TITLE
Text Image to Hand written Image Converter

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#102]
Title:  Text Image to Handwritten Text Image Converter 
About:  I will try to implement a Python Script that will convert Text to Handwritten text.
Name:  Satyam Tripathi 
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
This image-based script will collect your data using **Tesseract** and **Pillow**, and then convert it to handwritten text using **Pywhatkit**.

**Comment by prathimacode-hub** [comment]
That sounds wonderful. Follow the template to get issue assigned to you. @Iamtripathisatyam

**Comment by prathimacode-hub** [comment]
Go on. This issue is assigned to you. @Iamtripathisatyam
