### ISSUE TITLE
MADLIBS_Game

### ISSUE THREAD

**Issue by Ashi-00** [prathimacode-hub/Awesome_Python_Scripts#1048]
---
Title: Madlibs_Game
About: Its a super fun game wherein the user enters certain words based on the description (i.e. noun, adjective) and the code
fills up these words in the blanks of a preformed story template to complete the story and give it a meaning that super funny!
    i have added 4 story templates - 1)Harry Potter  2) F.r.i.e.n.d.s  3)Avengers   4)Ratatouille

Name: ASHI DUBEY
Label: Hacktoberfest'21
Assignee: Ashi-00

---

Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
Issue assigned to @Ashi-00
