### ISSUE TITLE
AQI Prediction using Python 

### ISSUE THREAD

**Issue by Jyoti6828** [prathimacode-hub/Awesome_Python_Scripts#105]
I would like to  do this project.I am taking parameter and calculate value for AQI. Can you please allow me to do this project?

**Comment by prathimacode-hub** [comment]
Hey, follow the template to raise an issue, refer other assigned issues to know how template looks like. @Jyoti6828

**Comment by prathimacode-hub** [comment]
It comes under which task? Can you also elaborate the project more briefer? @Jyoti6828

**Comment by prathimacode-hub** [comment]
It's been very long you had raised an issue, but no response yet. So unfortunately I had to close this issue, you can create up a new issue to show ur interest if you are willing to work on this script. @Jyoti6828
