### ISSUE TITLE
 Temperature of CPU using Python

### ISSUE THREAD

**Issue by Vaibhav-Vipin** [prathimacode-hub/Awesome_Python_Scripts#1052]
Title:- CPU Temperature
About:- It will be a simple script of python, which when runned by the user it will print the current CPU temperature on the screen.
It will use simple python library (psutil).

Name: Vaibhav Vipin
Label: Basic Python Script, Hacktoberfest'21
Assignee: ""

Define You:-
- [x] Hacktoberfest2021 Participant 
- [X] Contributor

**Comment by prathimacode-hub** [comment]
Issue assigned. @Vaibhav-Vipin
