### ISSUE TITLE
Vowel Remover

### ISSUE THREAD

**Issue by Rahuls66** [prathimacode-hub/Awesome_Python_Scripts#1054]
---
Title: Vowel Remover
About: This Python script removes vowels from the given input text using Regular Expression.
Name: Rahul Shah
Label: BasicPythonScript
Assignee: ''

---

Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
Issud assigned. @Rahuls66
