### ISSUE TITLE
Multiplication Table Generator

### ISSUE THREAD

**Issue by Rahuls66** [prathimacode-hub/Awesome_Python_Scripts#1055]
---
Title: Multiplication Table Generator
About: This Python script generates Multiplication Table for the given input number from the user.
Name: Rahul Shah
Label: BasicPythonScript
Assignee: ''

---

Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
Issue assigned. @Rahuls66
