### ISSUE TITLE
Plagiarism Checker In Python

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#106]
Title: Plagiarism Checker In Python
About: I will submit the Python code for detecting plagiarism between two files.
Name: Aditya Trivedi
Label: Feature Request
Define You:
- [x] LGM-SOC'21 Participant
- [ ] Contributor

**Solution For Issue:**
This plagiarism checker will compare all the data between 2 files using the **SequenceMatcher** class, which is in the **difflib** module. It will display the percentage of plagiarism between 2 files.

**Comment by prathimacode-hub** [comment]
Well needed script. All the best. This issue is assigned to you. @Aditya8821

**Comment by prathimacode-hub** [comment]
Is everything going fine? No update from you yet. @Aditya8821
