### ISSUE TITLE
Pie Chart Creator

### ISSUE THREAD

**Issue by Khushi-sharma07** [prathimacode-hub/Awesome_Python_Scripts#1071]
Title-: Pie Chart Creator
About:- Here I will add the code for basic python script where we can add a simple code by which the user will enter the data and a pie chart will be created.

Name: Khushi Sharma
Label: Basic Python script, Hacktoberfest'21
Assignee: ""

Define You:-

- [x] Hacktoberfest2021 Participant

Please assign this to me mam under hacktoberfest. @prathimacode-hub

**Comment by Khushi-sharma07** [comment]
Mam please assign this to me under hacktoberfest @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned. @Khushi-sharma07

**Comment by prathimacode-hub** [comment]
Hope you know today is last date? @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Mam I will submit it in an hour I created the P.R after I generated the code in my pc. Thank you mam for assigning

**Comment by prathimacode-hub** [comment]
Sure. Welcome. @Khushi-sharma07
