### ISSUE TITLE
Faker API

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#1072]
Hey Hacktoberfest participants, good to see you.

Repo : API Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by photon149** [comment]
I would like to work on the same .I will provide a detaield explaination of the API with , examples of the function done by the API.

**Comment by prathimacode-hub** [comment]
Issue assigned. @photon149
