### ISSUE TITLE
Image-to-Text Converter Project

### ISSUE THREAD

**Issue by nirbhay12345** [prathimacode-hub/Awesome_Python_Scripts#1076]
---
Title: Image to Text converter
About: An image to text converter which converts written text images to actual text based on Tesseract-OCR
Name: Nirbhay Chaplot
Label: Image Processing, Optical Character Recognition
Assignee: ''

---

Define You:

- Contributor

Please assign this to me @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @nirbhay12345. You can proceed.
