### ISSUE TITLE
Registration Form Web App

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#1093]
Title: Registration Form Web App
Directory: GUIScripts
Name: Satyam Tripathi 

### Define You:

- [X] Hacktoberfest2022 Participant 
- [X] Contributor

### Description:
I will create a registration form using the PyWebIO module. This is a Python module mostly used to create simple and interactive interfaces on the local web using Python Programming. 

@prathimacode-hub Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Iamtripathisatyam. You can proceed.

**Comment by Iamtripathisatyam** [comment]
> Issue assigned to @Iamtripathisatyam. You can proceed.

Thank you!
