### ISSUE TITLE
Web Scraping Flipkart website using BeautifulSoup Library of Python [WebScrapingScripts Folder ]

### ISSUE THREAD

**Issue by singhmansi25** [prathimacode-hub/Awesome_Python_Scripts#1095]
☑️ Title : Web Scraping using BeautifulSoup in Python
☑️ Name : Mansi Singh
☑️ Contribution Type :

- [ ]  Hacktoberfest2022 Participant

- [ ] Contributor

☑️ Assignee : Prathima Kadari
☑️ Approach : I will be using various web scraping libraries in python to scrape data from flipkart website (mobile phones).

@prathimacode-hub Please assign me this issue, as I want to participate in Hacktoberfest 2022.

**Comment by prathimacode-hub** [comment]
Issue assigned to @singhmansi25. You can proceed working.
