### ISSUE TITLE
Build a Digital clock using python

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#110]
---
Title: Digital Clock using python
About: Building a digital clock using tkinter
Name: Jayapritha N
Label: Feature Request
Assignee: ``

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by coding-geek21** [comment]
Mam , I'm getting this template only after pasting the same given in readme file , @prathimacode-hub can you please check

**Comment by prathimacode-hub** [comment]
Can you describe your project? @coding-geek21

**Comment by coding-geek21** [comment]
Yes it's basically a GUI script which will display the digital clock in HH:MM:SS format

**Comment by prathimacode-hub** [comment]
Cool. This issue is assigned to you. @coding-geek21

**Comment by coding-geek21** [comment]
> Cool. This issue is assigned to you. @coding-geek21

Thanks a lot :)

**Comment by Debashish-hub** [comment]
No update yet from your end since 4 days, Everything fine @coding-geek21

**Comment by coding-geek21** [comment]
> No update yet from your end since 4 days, Everything fine @coding-geek21 

Sorry I was not feeling well , I will make PR today

**Comment by Debashish-hub** [comment]
> > No update yet from your end since 4 days, Everything fine @coding-geek21
> 
> Sorry I was not feeling well , I will make PR today

No problem. Health comes first
