### ISSUE TITLE
Image Blending using opencv

### ISSUE THREAD

**Issue by sherin527** [prathimacode-hub/Awesome_Python_Scripts#111]
---
Title: Image Blending
About: I want to implement Image Blending using OpenCV one of the image processing technique
Name: Sherin Shibu
Label: Image Processing Script
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 

**Describe the solution you'd like...**
I would like to implement the Image Blending technique in which there will be two images and the output image will be the corresponding pixel values of these two input images. I will be using OpenCV for implementing this.

@prathimacode-hub ma'am, pls assign this issue to me.

**Comment by prathimacode-hub** [comment]
Welcome again, yes this issue is assigned to you. @sherin527
