### ISSUE TITLE
Animated Image Generator

### ISSUE THREAD

**Issue by SeminKim** [prathimacode-hub/Awesome_Python_Scripts#1111]
Title: Animated Image Generator
About: This Python script makes an animated image file(.gif or .webp) from frame images.
Name: seminkim
Label: ImageProcessingScripts

---
Define You:

- [x] Hacktoberfest2022 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
Issue assigned to @SeminKim
