### ISSUE TITLE
Collage Maker using python

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#113]
Title: Collage Maker Using Python
About: I will try to implement a python script that will convert two image into a single collage.
Name: Amit Gupta
Label: Feature Request
Assignee: ''

Define You:

- [X] LGM-SOC'21 Participant
- [ ] Contributor
Describe the solution you'd like...
This python script will take two input image from the user and will collage the image into one. I will use numpy and PIL module.

**Comment by prathimacode-hub** [comment]
Sounds interesting. Go ahead. @AmitGupta700
