### ISSUE TITLE
spirograph 

### ISSUE THREAD

**Issue by shreyamalogi** [prathimacode-hub/Awesome_Python_Scripts#116]
can I work on this for lgm-soc

**Comment by prathimacode-hub** [comment]
Elaborate the project? What's the project title? Create an issue using the template given in README file of the project, else you can check up with the assigned issues to know the template. @shreyamalogi

**Comment by shreyamalogi** [comment]
Title: The Spirograph
About: I will try to implement a GUI Python Script that is very interesting geometrical figure which is often symmetrical to both the axes.
Name: Malogi Shreya
Label: Feature request
Assignee: ''

Define You:
LGM-SOC'21 Participant

Describe the solution you'd like...
Here, I will be using python turtle graphics. I will use a range of colors to draw circles.

**Comment by prathimacode-hub** [comment]
That sounds interesting. this issue is assigned to you. @shreyamalogi
