### ISSUE TITLE
Encryption and Decryption of Data

### ISSUE THREAD

**Issue by Shivam-Chauhan** [prathimacode-hub/Awesome_Python_Scripts#118]
Hi, I am LGMSoC'21 participant I want to make a Python script than hashes data inputted by user using Fernet Hashing. 

Summary :- 
The data is hashed with a unique key and whenever user want to retrieve the data it decrypt that one with the same unique key.
The uniqueness of the key is checked by a set data structure and all the information is stored in dictionary having email as key of dictionary to identify the user and value in the form of a tuple (encrypted data, key).

Dictionary [email] --> (encrypted data, it's encryption key)

Language used :- Python 
Module used :- Fernet Hashing 
Data structure used :- Dictionary and Sets

It's fine ma'am @prathimacode-hub ??

**Comment by Shivam-Chauhan** [comment]
Ok, should I close this issue and open a new one??

**Comment by prathimacode-hub** [comment]
You just edit your comment in this raised issue. Replace it with template and fill it up accoding to your project. BrIef the project. I didn't get your project yet. @Shivam-Chauhan

**Comment by Parth-Shete** [comment]
@prathimacode-hub I would like to work on this issue.

**Comment by prathimacode-hub** [comment]
@Parth-Shete I already said raise your own issue to work on using the template given in README file of the project. Don't comment on other's issue.
