### ISSUE TITLE
All in one converter

### ISSUE THREAD

**Issue by tannu945** [prathimacode-hub/Awesome_Python_Scripts#119]
Title: Collage Maker Using Python
About: I will try to implement a python script that will convert currency, temperature, length, area and weight.
Name: Amit Gupta

**Comment by prathimacode-hub** [comment]
Elaborate the project? What kind of script is this? Follow the template. Your username is tannu945 but name is some thing else? Project title in issue is something else, and in comment other script. Have you copy pasted? @tannu945

**Comment by Ashu-1309** [comment]
Can you assign me this project I want  to work on tis project.
