### ISSUE TITLE
weather  notification script

### ISSUE THREAD

**Issue by Komal-99** [prathimacode-hub/Awesome_Python_Scripts#120]
Title: Weather Notification Using Python
About: I will try to implement a python script that will get weather notification of any city on youscreen
Name: Koaml
Label: Feature Request
Assignee: ''

Define You:

- [X] LGM-SOC'21 Participant
- [X] Contributor

Describe the solution you'd like...
It is python program which uses beautifulsoup  library and fetch the data from google and display it on your desktop as a notification reminder after every 20 seconds when program executed.

**Comment by prathimacode-hub** [comment]
What kind of script is this? Is it a GUI or API? Elaborate the project? @Komal-99

**Comment by Komal-99** [comment]
![image](https://user-images.githubusercontent.com/74819092/121662852-6e20aa00-cac3-11eb-941a-502f945fc7f3.png)
 like this on running the file you will get notification in every 20 sec until you close it.

**Comment by Komal-99** [comment]
okay kindly add LGMSOC label and difficulty level label

**Comment by prathimacode-hub** [comment]
LGMSOC label is added, level labels would be added only after PR is ready to merge. @Komal-99

**Comment by prathimacode-hub** [comment]
Add up the solution in the template I had updated above to your project. @Komal-99

**Comment by Komal-99** [comment]
Okay

**Comment by Komal-99** [comment]
Add up the solution means like i have to add code in comment? as in local i have made folder in  Automation script with readme and requirements files so shall i create PR
