### ISSUE TITLE
Color game using Python GUI

### ISSUE THREAD

**Issue by queenish001** [prathimacode-hub/Awesome_Python_Scripts#121]
I would like to contribute a Color game using Tkinter (Python GUI)
Kindly assign this issue to me 
:)

**Comment by prathimacode-hub** [comment]
This game is already in this repository. Kindly take up an another issue. And also while creating an issue, follow the template. You can know how template looks like by checking on with assigned issues. @queenish001

**Comment by queenish001** [comment]
Oh, Okay

**Comment by prathimacode-hub** [comment]
You should never close an issue or PR from your end. Just letting you know. @queenish001

**Comment by queenish001** [comment]
Oh, Sorry.
I'll keep that in mind.

**Comment by prathimacode-hub** [comment]
That's Ok. Glad you know now.
