### ISSUE TITLE
Sorting Algorithm Visualizer

### ISSUE THREAD

**Issue by queenish001** [prathimacode-hub/Awesome_Python_Scripts#122]
Title: Sorting Visualizer
About: Visualize Different Sorting Algorithms
Name: Nishi
Label: Sorting Algorithm Visualizer
Assignee: ''

 LGM-SOC'21 Participant
Description:-
I would like to use PyGame to visualize sorting algorithms (Bubble sort, Merge sort and Insertion sort), 
Visualizing these concepts helps to get a better and clearer understanding of how these algorithms actually work.

@prathimacode-hub Kindly Assign this issue to me. :)

**Comment by prathimacode-hub** [comment]
Yes, I had assigned this issue to you. Go ahead. All the best. @queenish001
