### ISSUE TITLE
Lane Detection

### ISSUE THREAD

**Issue by suvrashaw** [prathimacode-hub/Awesome_Python_Scripts#123]
---
Title: Road Lane Detection
About: I want to create an image processing python script that will detect the lanes of a road through a sample image using the OpenCV library.
Name: Suvra Shaw
Label: Feature Request
Assignee: ''

---

Define You:

- [✔️ ] LGM-SOC'21 Participant 
- [✔️ ] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

I want this program to detect the lanes of the road displayed in the sample image. Any image can be processed in this manner with a little tweak of the input coordinates.

**Describe alternatives you've considered?**

I am planning to implement this script into a video, by obtaining its frames.

**Approach to be followed (optional):**

I will use the OpenCV library of python to process the NumPy array of the sample image (obtained after conversion). Firstly, I will use the canny function to trace the edges in the image. Then I will mask the array to the required portion. Finally, I will use Hough Lines to detect the lanes and draw the detections obtained.

**Additional context**

None, curently.

**Comment by prathimacode-hub** [comment]
This issue is assigned it to you. Wonderful choice of the project. @suvrashaw

**Comment by suvrashaw** [comment]
Can I submit an ipynb? or it has to just python (.py)?

**Comment by Debashish-hub** [comment]
No update yet from your end. Is everything  good.  @suvrashaw

**Comment by suvrashaw** [comment]
I'm a bit off due to vaccination after effect and end semesters. will be clearing this issue by tomorrow. program is completed markdown is to be adjusted. Sorry for the delay ma'am.

**Comment by prathimacode-hub** [comment]
That's fine as long as you inform timely. Carry on. @suvrashaw

**Comment by Debashish-hub** [comment]
Hey @suvrashaw Is everything fine

**Comment by prathimacode-hub** [comment]
No update from you. @suvrashaw

**Comment by prathimacode-hub** [comment]
Sorry to say, but unfortunately I have to assign this issue to someone else as there was no response from you since past 15 days. You can take up a new issue to work on, when you could give your time. Issue can't held for this long. @suvrashaw

**Comment by prathimacode-hub** [comment]
Why have you closed the issue? Neither you have shown interest in replying to the concern nor you have raised your PR.  Any say on this? @suvrashaw

**Comment by harshved** [comment]
I am glad to work on this issue, I have bit knowledge of OpenCV, So it would be great to work on this issue and came out with solution.

**Comment by prathimacode-hub** [comment]
That's great, glad to know. But contributions would count from 10th of July, 2021. The issues will be alloted on first come first serve basis. Starting then, you could express interest and get it assigned to you. So stay alerted. All the best for your open source journey ahead. @harshved

**Comment by harshved** [comment]
Is it alright to work on this issue at present? I am participant from devIncept Jul 2021

**Comment by prathimacode-hub** [comment]
Sure, you can work on it, but only if you could give time to it. @harshved

**Comment by prathimacode-hub** [comment]
Add the issue template here, fill up the details and get this issue assigned to you.

**Comment by harshved** [comment]
> Sure, you can work on it, but only if you could give time to it. @harshved

Yess, I will gave the time that's for sure.

**Comment by harshved** [comment]
> Add the issue template here, fill up the details and get this issue assigned to you.
@prathimacode-hub Sorry but I'm new to the open source contribution will you please guide me about this, that how to get assigned tag on this issue.

**Comment by prathimacode-hub** [comment]
Just add up the issue template here in comments and do the changes according to your approach and your details. Once you do that, I shall assign the issue to you. Issue template is provided in README file of the project. If you have any doubts, feel free to ask. @harshved

**Comment by harshved** [comment]
Title: Road Lane Detection
About: I want to create an image processing python script that will detect the lanes of a road through a sample image using the OpenCV library.
Name: HARSH VED
Label: Feature Request
Assignee: ''
 

Define You:

[✔️ ] DCP21 Participant
[✔️ ] Contributor
Is your feature request related to a problem? Please describe.

Describe the solution you'd like...

Firstly, I will create program for the image and then i will try to create program for streaming video which will detect the road lanes.

Describe alternatives you've considered?

I am planning to implement this script into a video, by obtaining its frames.

Approach to be followed (optional):

I will use the Python's Open CV library and import NumPy and Matplot lib to process the image, and for the edge detection will use the canny's edge detection function. Then use the Hough line detection to detect the side road lanes.

Additional context

None, curently.

**Comment by harshved** [comment]
@prathimacode-hub Is it enough for the process?

**Comment by prathimacode-hub** [comment]
Yes, obsolutely. Issue assigned. @suvrashaw

**Comment by harshved** [comment]
@prathimacode-hub I just created pull-request for the code. But now I don't know how to readme file, to describe the code. Please help me with that.
