### ISSUE TITLE
QR Code Scanner

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#126]
Title:  QR Code Scanner Web Application

About:  This Python Script will scan your Image and check whether the Image is QR or not, if it's a QR then it will fetch the data and provide you with the decoded form.'

Name: Satyam Tripathi
 
Label: Feature Request

Defines you: 
- [x] LGM-SOC'21 Participant
- [x] Contributor

Describe the Approach: 
In this script I'll be using **pywebIo**, **pyzbar**, **Pillow**, and so forth for making it more functional.

**Comment by prathimacode-hub** [comment]
Issue is assigned to you. @Iamtripathisatyam
