### ISSUE TITLE
Youtube Video Downloader

### ISSUE THREAD

**Issue by skimran2000** [prathimacode-hub/Awesome_Python_Scripts#127]
---
Title: Youtube video downloader
About: Using Youtube library from pytube module and writing python code to download videos
Name: Shaik Imranuddin
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**

There is a python library named as ‘pytube’. pytube is a lightweight, dependency-free Python library which is used for downloading videos from the web. pytube is not the native library. You need to install it with pip3 before using it.

**Comment by prathimacode-hub** [comment]
Sorry to say, but youtube video downloader is already assigned to someone else yesterday. You can take up a URL shortener issue. @skimran2000

**Comment by prathimacode-hub** [comment]
If you want to work on this issue, after PR is merged by other person, you can add an enhancement to it. @skimran2000

**Comment by Adarsh357** [comment]
Can u assign url shortener proJect

**Comment by Adarsh357** [comment]
What's the procedure to get the assignment

**Comment by Debashish-hub** [comment]
@Adarsh357 Find an issue or create an issue to work on it. Describe everything as per the issue template, Then a mentor will assign you if that's good enough and new.

**Comment by Adarsh357** [comment]
Ok
