### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by skimran2000** [prathimacode-hub/Awesome_Python_Scripts#129]
---
Title: URL Shortener
About: Writing a python script to make a URL short using API
Name: Shaik Imranuddin
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**

Writing a python script to make a long URL into short using the API

**Comment by prathimacode-hub** [comment]
I assigned this issue to you. Proceed. So this is an API script? @skimran2000

**Comment by Debashish-hub** [comment]
No update yet from your end. Is everything good. @skimran2000

**Comment by skimran2000** [comment]
Sorry, was busy with my college assignments.
I have made a PR #256
