### ISSUE TITLE
ATM Machine System

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#131]
Title: ATM Machine System
About: Writing a python script to make a small view about how this system works.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

-> LGM-SOC'21 Participant
   Contributor
Describe the solution you'd like...
I will make a script in which there will be system where you can check balance ,withdraw money or deposit money for a particular account.

**Comment by prathimacode-hub** [comment]
Sure, go ahead. Issue is assigned to you. Where would this script belong to? @neelshah2409

**Comment by neelshah2409** [comment]
I would do this problem in python.

**Comment by prathimacode-hub** [comment]
Yeah, obviously repo is on python. But to which sub folder would this script fit into? @neelshah2409

**Comment by neelshah2409** [comment]
sorry mam , in basic python scripts. And even I had created a PR for that.
