### ISSUE TITLE
More Chocolates Please !!!

### ISSUE THREAD

**Issue by singhmansi25** [prathimacode-hub/Awesome_Python_Scripts#134]
About : The Problem focuses on how you can get more chocolates in return of the wrappers of same.  
Name : Mansi Singh
Label : Feature Request
Define you : LGM-SOC'21 Participant
Problem Statement : Let's solve the chocolate problem where Let's you have m rupees and cost of each chocolate is c rupees. Shopkeeper gives away k chocolates for w wrappers. Can you find now how many chocolates you will be able to eat?
Solution : Using Basic-python knowledge and Math's, we can easily find out the solution.

Sample input:  15, 2, 3, 2
Sample output: 'Yay you got 17 Chocolates . Enjoy '.
Explanation:
m = 15, c = 2, w = 3, k = 2 
You have 15 rupees, buy 7 chocolates for 2 rupees each.
now you have 7 wrappers, exchange 6 of them for 4 more chocolates.
now you have 5 wrappers and exchange 3 of them for 2 more chocolates.
now you have 4 wrappers and exchanges 3 of them for 2 more chocolates.
now you have 3 wrappers and exchange them for 2 chocolates making a total of 17 chocolates.

**Comment by prathimacode-hub** [comment]
Maths into python, cool. Issue is assigned to you. @singhmansi25

**Comment by Debashish-hub** [comment]
No update yet from your end. Is everything going good. @singhmansi25

**Comment by singhmansi25** [comment]
@Debashish-hub yes, I'm facing problem in adding the project
Please help me out, I'm unable to contribute

**Comment by Debashish-hub** [comment]
yes, What's the problem @singhmansi25

**Comment by prathimacode-hub** [comment]
Do you need any guidance, don't hesitate to ask. @singhmansi25

**Comment by Debashish-hub** [comment]
Hey @singhmansi25 Feel free to ask if you are facing any problem
