### ISSUE TITLE
Current Stock Price Web Scraping

### ISSUE THREAD

**Issue by jigar-sable** [prathimacode-hub/Awesome_Python_Scripts#138]
---
| Title | About | Name | Label | Assignee |
|-------|-------|------|-------|----------|
| Current Stock Price  | Fetch Current Stock Prices using Web Scraping(Beautiful Soup) | Jigar | Feature Request  |

---

Define You:

- [x] LGM-SOC'21 Participant

**Describe the solution you'd like...**
I'll use Beautiful Soup and Requests module to web scrap the details of current stocks of few companies.
It will fetch live details and shows the output.

**Additional context**
![image](https://user-images.githubusercontent.com/64949957/121741683-7f49d500-cb1c-11eb-8ac7-efe5b40b053a.png)
  **Sample Program**

**Comment by jigar-sable** [comment]
@prathimacode-hub please assign me this issue I'd solved my all previous issues.

**Comment by prathimacode-hub** [comment]
Yes, this issue is assigned to you. Carry on. So this is a webscraping script. @jigar-sable

**Comment by jigar-sable** [comment]
Thank you ma'am. Yeah I'll add it in WebScrapingScripts.
