### ISSUE TITLE
COWIN API SCRIPT

### ISSUE THREAD

**Issue by Bhuvanaa28** [prathimacode-hub/Awesome_Python_Scripts#140]
# API SCRIPT - COWIN API

Title | About | Name | Label | Assignee
----- |-------- | ------ | ------ | ----------
COWIN API SCRIPT |  In this project, details of available vaccination <br> slots is displayed upon request to the API | Bhuvanaa28 | Feature Request |

- [x] LGM-SOC'21 Participant 

The approach I would like to follow is to use the requests library, make a request to the API, obtain the details of available vaccination slots and display the details to the user.

**Comment by prathimacode-hub** [comment]
Sure, proceed with your work. This issue is assigned to you. @Bhuvanaa28

**Comment by Bhuvanaa28** [comment]
Thank you Mam
