### ISSUE TITLE
Facebook Messenger Automation

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#141]
About : Here we will automate message in messenger using pyautogui and time library.
Name : Neel Shah
Label : Feature Request
Define you : LGM-SOC'21 Participant
Problem Statement : Why to write message yourself let it be done automatically through script.
Solution : Using pyautogui and time we will automate msg in messenger.

**Comment by prathimacode-hub** [comment]
Yup, interesting. This issue is assigned to you. Go ahead. @neelshah2409
