### ISSUE TITLE
Add links to the badges

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#145]
Title: Add links to the badges in main README.md file
Name: Umesh Singh
Label: Enhancement Request
Define You
- [x] LGM-SOC'21 Participant
- [ ] Contributor

Solution For Issue:
I will add links to the badges present in the readme (see the below image)

![image](https://user-images.githubusercontent.com/83420185/121767516-2870e980-cb76-11eb-84e5-6a5e77b4168a.png)

**To Do**
- [x] Add some links in the general badges like contributors, etc.
- [x] Add some links in the badges of PRs, Issues, Stars, etc.
- [x] Format text to align it to the center

**Comment by Umesh-01** [comment]
@prathimacode-hub should I work on this??

**Comment by prathimacode-hub** [comment]
Sure, you can work on this. Are you a LGMSOC participant or as a contributor? @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub 
yes I am LGMSOC participant, pls assign some labels to it

**Comment by Umesh-01** [comment]
And I also want to contribute for three scripts in python-
- [ ] one for jokes
- [ ] second for poems of any author
- [ ] third for quotes related to any person or author

@prathimacode-hub mam should I create separate issues for these??
And for these also I will contribute as a **LGMSOC** participant 🙂

**Comment by prathimacode-hub** [comment]
Labels are assigned only after PR is created. Do create separate issues for the projects you want to contribute with project title and right templates as mentioned in README file of the project. It also has a project structure to follow. Kindly note that. And all the bets. Welcome to the repo once again. You can work on this issue. I shall assign this to you. Follow the contributing guidelines. You will be alloted with only 1 issue at a time. I had also enclosed a document in project channel in slack. Do check it to clarify out your queries. Anything else, don't hesitate to ask. @Umesh-01

**Comment by prathimacode-hub** [comment]
Even for this issue, you need to create it using right template. That is to know you as a LGMSOC participant. @Umesh-01

**Comment by Umesh-01** [comment]
okk mam, got it...
