### ISSUE TITLE
jumbled words guessing game

### ISSUE THREAD

**Issue by Harshitha-246** [prathimacode-hub/Awesome_Python_Scripts#146]
Title | About |  Name  |  Label  | Assignee |
---- |---------|---------|--------|------------|
Jumbled words Guessing game | In this project we make the user guess right word from the jumbled word displayed | Harshitha-246 | Feature Request| 

- [x] LGM-SOC'21 Participant

My approach would be from a list of words , I would choose a random word using random and jumble the letters of the word and make the user guess the word and check if the user found the right word

**Comment by prathimacode-hub** [comment]
It's fun. Go ahead. Issue is assigned to you. @Harshitha-246

**Comment by Harshitha-246** [comment]
thank you mam
