### ISSUE TITLE
Real-Time Bitcoin Price in INR

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#149]
Title: Real-Time Bitcoin Price in INR
About: I will submit the Python code for checking the Real-time rate of Bitcoin in INR.
Name: Aditya Trivedi
Label: Feature Request
Define You:
 
 - [x] LGM-SOC'21 Participant
 - [ ] Contributor

Solution For Issue:
This project informs us of the current value of bitcoin in Indian National Rupees. This is accomplished with the help of the BeautifulSoup library, which extracts data from HTML and XML files. It will show the rate in Indian Rupees (INR).

**Comment by prathimacode-hub** [comment]
So, it's a webscraping project? Good selection of your issue. Sure, go ahead. This issue is assigned to you. @Aditya8821

**Comment by Aditya8821** [comment]
Yes mam it's a webscraping one as we are extracting real time rate from google itself. 
Thanks mam for assigning this.
