### ISSUE TITLE
Bitcoin Mining using Python

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/Awesome_Python_Scripts#151]
---
Title: BitCoin Mining Script
About: The idea here is to mine BTC Using this script
Name: Neeraj Ap
Label: Feature Request

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

The Script Which I Provide Helps to Mine Bitcoins.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can go ahead. 👍@NEERAJAP2001
