### ISSUE TITLE
Twitter Data Streaming

### ISSUE THREAD

**Issue by dhruv-varshney** [prathimacode-hub/Awesome_Python_Scripts#152]
Title: Twitter Data Streaming
About: The idea here is to stream the twitter data by using API keys
Name: Dhruv Varshney
Label: Feature Request

### Define You:

- [x]  LGM-SOC'21 Participant

The Script Which I Provide Helps to stream the Twitter data

**Comment by prathimacode-hub** [comment]
This issue is already been taken and merged as well. You can take up an another issue to work on. @dhruv-varshney

**Comment by dhruv-varshney** [comment]
ok ma'am
