### ISSUE TITLE
Adding Welcome Bot to the repo

### ISSUE THREAD

**Issue by hr1shu** [prathimacode-hub/Awesome_Python_Scripts#154]
---
Title: Welcome Bot
About: Suggest an idea for this project
Name: Rishav Kumar
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 

**Is your feature request related to a problem? Please describe.**

The bot will automatically send welcome message, first PR message, new issue created message,etc.

**Describe the solution you'd like...**

Github provides an APP for this, I'll be implementing it for the repo.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
There is config.yml file in .github though it isn't interactive. Or is this a bot implemented individually. @hr1shu

**Comment by hr1shu** [comment]
Yeah, I'll be making some changes in config.yml and will try to make it interactive.

**Comment by prathimacode-hub** [comment]
Ok, sure this issue is assigned to you. @hr1shu

**Comment by hr1shu** [comment]
Hey, after doing all possible research from my end I came to conclusion that this app need to be installed on your main repo. I can't  find any ways to push the app from branch to main.
Enlight me if I'm wrong.

**Comment by prathimacode-hub** [comment]
Can you elaborate it more? How does it work? @hr1shu

**Comment by hr1shu** [comment]
Yeah sure,
You have to head over to the website : https://github.com/apps/welcome and follow the guidelines.
If it's ok may I start with a new issue now??

**Comment by prathimacode-hub** [comment]
Yeah, you can start with a new issue. @hr1shu
