### ISSUE TITLE
Add a Python script for Jokes

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#155]
Title: Add a script to get jokes using Python
Name: **Umesh Singh**
Label: Feature Request
Define You
- [x] LGM-SOC'21 Participant
- [ ] Contributor

Solution For Issue:
I will be using a python library for getting the jokes. I will also add a python script file with the readme file and the screenshots for it's working.

**Comment by prathimacode-hub** [comment]
Yeah, get into the issue. Interesting. It's assigned to you. @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam, i think u forget to close this issue...!!

**Comment by prathimacode-hub** [comment]
It automatically closes, when it's merged. I guess something wrong. No issues, I shall close from my end as issue is merged. @Umesh-01
