### ISSUE TITLE
Text-based Snakes and Ladders game in python which can be played by 2 players

### ISSUE THREAD

**Issue by chandu6111** [prathimacode-hub/Awesome_Python_Scripts#156]
**Title:** Text-based Snakes and Ladders game in python which can be played by 2 players
**Name**: Chandana (chandu_6111)
**Label**: Feature Request

**Description of the Game**:

1. The program will ask both the players for inputting their names.
2. It randomly throws a dice and the number will be displayed.
3. The number displayed should be added to the total scores of the players respectively.
4. This continues until the end of the board is reached(until the maximum available score on the board is achieved by either of the players) or until either of them wishes to quit the game.

- [x] LGM-SOC'21- participant

**Comment by chandu6111** [comment]
@prathimacode-hub please assign me this issue under **LGM-SOC'21**

**Comment by prathimacode-hub** [comment]
Yeah, sure. This issue is assigned to you. It's a fun game.  @chandu6111

**Comment by chandu6111** [comment]
Thank you @prathimacode-hub
