### ISSUE TITLE
AI Guess my number-Game

### ISSUE THREAD

**Issue by Suryadipsinh** [prathimacode-hub/Awesome_Python_Scripts#157]
A python based game in which user will guess a number and AI will find that number and we have to give hint about guessed number to AI. This is an example of how to use variables to keep track of information in a program that also makes use of loops in this program.
I would like to add this game here.
Thank you.

**Comment by prathimacode-hub** [comment]
This game is already in this repository and one more thing, while raising a issue and PR, do it using the templates given in README file of the project. You can take up an another issue to work on. @Suryadipsinh

**Comment by Suryadipsinh** [comment]
Thank you ma'am, will keep in mind.
