### ISSUE TITLE
whatsapp_messaging

### ISSUE THREAD

**Issue by Pratik57** [prathimacode-hub/Awesome_Python_Scripts#159]
> Title: Send whatsapp message without saving number
> Name: **Pratik**
> Label: Feature Request
> Define You
> 
> * [x]  LGM-SOC'21 Participant
> * [ ]  Contributor
> 
> Solution For Issue:
> I will be using python script to send messages to unknown number without saving it

**Comment by prathimacode-hub** [comment]
Can you elaborate the issue, as how this works? @Pratik57

**Comment by Sidrahsheikh** [comment]
I would like to work on this, it will be helpful if you explain it a little bit.

**Comment by prathimacode-hub** [comment]
This issue is already done. You can create up a new issue to work on. But make sure, it isn't already in the repo. All the best. @Sidrahsheikh
