### ISSUE TITLE
Add Air Canvas

### ISSUE THREAD

**Issue by sambit221** [prathimacode-hub/Awesome_Python_Scripts#160]
---
Title: Air Canvas
About:Track all the movement of the target(finger of the user) in the air and display it to an output screen.
Name: Sambit Kumar Tripathy
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Solution For Issue:
I will be using openCV and numpy module to take input of the live video stream and process it, to achieve the desired objective.

**Comment by prathimacode-hub** [comment]
This script would go into which repository? Sounds fascinating. All the best. This issue is assigned to you. @sambit221

**Comment by sambit221** [comment]
i will put this script into ImageProcessingScripts. As i will be using openCV i.e, an image processing module

**Comment by prathimacode-hub** [comment]
That's awesome @sambit221

**Comment by Debashish-hub** [comment]
Hey @sambit221 Is everything going good. No updates since 5 days.

**Comment by sambit221** [comment]
I am sorry. i am a bit late because of my exams. I have managed my time and completed it. Thank you
