### ISSUE TITLE
Grammar Correction

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#161]
Title: Grammar Correction
About: Here we can solve our silly grammar mistakes by just  running the script.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

-> LGM-SOC'21 Participant
  Contributor
Solution For Issue:
I would like to write a python script for this problem which will help to correct grammar and for that I will use gingerit library.

**Comment by prathimacode-hub** [comment]
Good going. You can proceed with the script. This issue is assigned to you. @neelshah2409
