### ISSUE TITLE
English Dictionary

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#165]
Title | About | Name | Label | Assignee
----- |-------- | ----- | ------ | ----------
English Dictionary | Implementation of an English dictionary using GUI | Sonali Bedade | Feature Request |

- [x] LGM-SOC'21 Participant 

An alternative to conventional English language dictionaries where user can type the desired word in the text box and by clicking on the search button, the meaning will appear on the display.

**Comment by prathimacode-hub** [comment]
Yeah, good going. This issue is assigned to you. All the best. 👍@sonaliBedade
