### ISSUE TITLE
Covid Cases Bot

### ISSUE THREAD

**Issue by Komal-99** [prathimacode-hub/Awesome_Python_Scripts#166]
---
Title: Covid-19 cases bot script using python
About: Desktop notifier for covid-19 cases
Name: Komal
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

yes I did

**Describe the solution you'd like...**

**Additional context**

**Comment by prathimacode-hub** [comment]
Add the solution of your script you would expect in the template above. Always be elaborative. @Komal-99

**Comment by Komal-99** [comment]
@prathimacode-hub  kindly add difficulty level label
