### ISSUE TITLE
Minesweeper

### ISSUE THREAD

**Issue by Nihir2904** [prathimacode-hub/Awesome_Python_Scripts#170]
------------------------------------------------------------------------------------------------------------------------------------
Title | About | Name | Label
---|---|---|---
Minesweeper | Play minesweeper on your command line | Nihir Shah | Feature Request

## Assignee: 

----------------------------------------------------------------------------------------------------------------------------------

Define You:
- [x] LGMSOC Participant
- [ ] Contributor

LGM-SOC'21 

Solution For Issue:
Using oops in python, play minesweeper on your command line.

**Comment by prathimacode-hub** [comment]
Interesting game. This issue is assigned to you. You can start working on it. All the best. @Nihir2904

**Comment by Nihir2904** [comment]
Thanks!

**Comment by Debashish-hub** [comment]
Hey @Nihir2904 No updates since 5 days. Is everything going good?

**Comment by Nihir2904** [comment]
yeah everything is fine, will be creating a pull request today.

**Comment by prathimacode-hub** [comment]
> yeah everything is fine, will be creating a pull request today.

Good to know. @Nihir2904

**Comment by prathimacode-hub** [comment]
Is it all going fine? @Nihir2904

**Comment by prathimacode-hub** [comment]
Sorry to say, but unfortunately I have to close this issue as there was no response from you since past 12 days. You can take up a new issue to work on, when you could give your time. Issue can't held for this long. @Nihir2904
