### ISSUE TITLE
PC Cleaner

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#171]
---
Title: PC Cleaner
About: Implementation of a PC Cleaner using **OS** module.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'll write a Python script to clean all the files in their respective folders, such as "**.jpg**" photos and "**.pdf**" files in a folder. As a result, this python script will place all pdf files in the **PDF** folder, as well as all images in the **Images** folder, and so forth.

**Comment by prathimacode-hub** [comment]
Wow, very much useful script needed. Yup, you're allowed to proceed further. Get on with your issue. This issue is alloted to you. @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Thank you so much ma'am
