### ISSUE TITLE
Calculator GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#173]
Title: Calculator GUI
About: Implementing calculator using tkinter
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

-> LGM-SOC'21 Participant
    Contributor
Solution : I will create a calculator GUI using tkinter library which will be similar to the calculator which is there in our pc/phone.

**Comment by prathimacode-hub** [comment]
Sorry to say, but calculator is already taken. You can take up some other issue. @neelshah2409

**Comment by prathimacode-hub** [comment]
You should not close issues from your end. @neelshah2409
