### ISSUE TITLE
Matchmaker Game

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#176]
Title: Matchmaker Game
About: Implementing game with tkinter and random library
Name: Satyam Tripathi
Label: Feature Request
Assignee: ''

Define You:

-> LGM-SOC'21 Participant
    Contributor

Description: I would like to write a script using tkinter ,random and time library in which there will be some shapes hidden if you found correct match then it will be unhidden else it will hide again.

**Comment by prathimacode-hub** [comment]
Yeah, interesting one. You can proceed. @neelshah2409
