### ISSUE TITLE
Random email generator

### ISSUE THREAD

**Issue by pankaj892** [prathimacode-hub/Awesome_Python_Scripts#177]
Title - Random Email Generator
About - The script would generate random email addresses for the user
Name - Pankaj Biradar
Label - Feature Request

Define You - 
-> LGM-SOC'21 Participant
Contributor

Description - I would like to add a script using random library which will generate random email addresses based on popular domains

**Comment by prathimacode-hub** [comment]
Follow the issue template to get it assigned. @pankaj892

**Comment by pankaj892** [comment]
@prathimacode-hub is the template correct now?

**Comment by prathimacode-hub** [comment]
Yeah, it's better. I shall assign this issue to you. You can proceed. @pankaj892
