### ISSUE TITLE
I would like to add weather app in python !

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/Awesome_Python_Scripts#178]
Title: Weather app
About: weather app using tkinter and api
Name: Siddhi Bhanushali 
Label: Feature Request
Assignee: ''

Define You -
-> LGM-SOC'21 Participant
Contributor

Description - I would like to add a script using tkinter and api that will give uh weather of city you input !

**Comment by Debashish-hub** [comment]
Please fill the issue template and do check if it's already there or not?

**Comment by siddhi-244** [comment]
Where is the issue template?

**Comment by siddhi-244** [comment]
@Debashish-hub  done !

**Comment by Debashish-hub** [comment]
Issue Template :
https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/.github/issue_template/feature_request.md

There is already an issue for weather report in python GUI , Do check. If you are going to do something different then go ahead
https://github.com/prathimacode-hub/Awesome_Python_Scripts/issues/83

**Comment by siddhi-244** [comment]
@Debashish-hub  I am going to implement it using tkinter and openweathermap api and it will show only some things like temp,description etc not whole report and the input will be taken from the user !

**Comment by prathimacode-hub** [comment]
This issue is already in the repo under APIScripts. 
Link : https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/APIScripts/OpenWeatherMap%20API

Also ,Weather Report in GUI is already assigned.

If you want, you can enhance this project else take up a new issue. That's upto you. @siddhi-244

**Comment by siddhi-244** [comment]
But it's without gui maam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes, but with GUI PR is as well ready. No  problem, you cna take some other issue to work on. @siddhi-244
