### ISSUE TITLE
add API scripts 🚀 

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#18]
I think u must add a folder for the python code that uses any kind of API to perform some task @prathimacode-hub

**Comment by prathimacode-hub** [comment]
I don't think many would like to contribute separately for python projects on API. So I had generalized. But it's a good idea. Do suggest some more folders which would go well into this repository. If anything fits the clause. you can a create PR of it for the same. @Umesh-01

**Comment by prathimacode-hub** [comment]
Good to see your initiation of API scripts repository and adding up a OpenWeather API. It was a good add-on. Keep giving wonderful suggestions as you do. 👌✔
