### ISSUE TITLE
Distance Between Two Places 

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#180]
---
Title:: Distance Finder
About: Implementation of a Distance Finder using **geodesic** and **Nominatim**.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'll develop a Python script that uses latitude and longitude to calculate the distance between two points. I'll be utilizing the **geopy** module, which will assist us in determining the precise distance between two points.

**Comment by prathimacode-hub** [comment]
Perfect, add the project title as "Distance Finder". So are you going to use API? @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
No, ma'am, I'll use **geopy** and a **Google map** to get the precise **longitude** and **latitude** of that city, and then **geodesic** and **Nominatim**, which are both specified inside geopy, will assist in determining the distance.

**Comment by prathimacode-hub** [comment]
Got you. Sure, this issue is allotted to yu.You can proceed. @Iamtripathisatyam

**Comment by Debashish-hub** [comment]
Hey @Iamtripathisatyam No updates since 5 days

**Comment by Iamtripathisatyam** [comment]
Sorry sir, I am working on making my project.

**Comment by Debashish-hub** [comment]
> Sorry sir, I am working on making my project.

Ok. Complete it as soon as possible @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Ok, sir 
Thank you so much

**Comment by prathimacode-hub** [comment]
@Debashish-hub, this project is approved and merged.

@Iamtripathisatyam, you finished this project. Have you forgotten?
