### ISSUE TITLE
2048 game

### ISSUE THREAD

**Issue by Harshitha-246** [prathimacode-hub/Awesome_Python_Scripts#181]
Title  | About | Name | Label | Assignee |
----- | --------|--------|-------|-----------|
2048 | To create 2048 game in Python | Harshitha-246 | Feature request

Define You:
- [x] LGM-SOC'21 Participant
- [ ] Contributor

I would like to create a 2048 game using tkinter and random library.

**Comment by prathimacode-hub** [comment]
Can you elaborate the game? @Harshitha-246

**Comment by Harshitha-246** [comment]
in this game user has to merge tiles with same numbers so that it will add up and the user wins if he adds the numbers to 2048 .

**Comment by prathimacode-hub** [comment]
Ok, sounds interesting. Issue is assigned to you. Go ahead. @Harshitha-246

**Comment by Harshitha-246** [comment]
thank you mam
