### ISSUE TITLE
Real-Time Petrol Price

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#183]
Title: Real-Time Petrol Price
About: Getting Real-Time Petrol Price by using BeautifulSoup and pandas.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

 - [x] LGM-SOC'21 Participant
 - [ ] Contributor
 
I'll write a Python script that uses some BeautifulSoup functions to extract data from an HTML page and then uses pandas to create a 2d table with a list of petrol prices in some major Indian cities. It also displays the previous day's petrol price.

**Comment by prathimacode-hub** [comment]
You can proceed with the issue. It's assigned to you. @Aditya8821
