### ISSUE TITLE
Canny Edge Detection 

### ISSUE THREAD

**Issue by sherin527** [prathimacode-hub/Awesome_Python_Scripts#185]
---
Title: Canny Edge Detection
About: I want to implement Canny Edge detection one of the Image processing technique
Name: Sherin Shibu
Label: Image Processing Script
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**

I want to implement canny edge detection which is one of the image processing techniques. I will be using Opencv to implement it. It's basically an edge detection technique wherein all the edges of the images will be detected sharply.

@prathimacode-hub ma'am, can I implement this. Pls, assign this issue to me.

**Comment by prathimacode-hub** [comment]
Sure, you can. This issue is assigned to you. Kindly proceed. @sherin527

**Comment by Komal-99** [comment]
@sherin527  are you implementing or adding readme for same?

**Comment by prathimacode-hub** [comment]
Any issue @Komal-99

**Comment by Komal-99** [comment]
> Any issue @Komal-99

No no i was just asking because is she is only implementing i can do its readme
