### ISSUE TITLE
Real-time currency converter

### ISSUE THREAD

**Issue by Bhuvanharsha16** [prathimacode-hub/Awesome_Python_Scripts#186]
Title | About | Name | Label | Assignee
-- | -- | -- | -- | --
Real-time currency exchange rate| Converts INR to other currency and vice-versa | Kodali Bhuvan SriHarsha | Feature Request | &nbsp;

- [x]  LGM-SOC'21 Participant

I would like to write a currency exchange rate Python script that can convert given INR value to foreign currency and the other way around.

**Comment by Bhuvanharsha16** [comment]
@prathimacode-hub  please assign me this issue

**Comment by prathimacode-hub** [comment]
Definitely, this issue is assigned to you. You can proceed. @Bhuvanharsha16
