### ISSUE TITLE
Bubble Catcher Game

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#191]
Want to add Bubble Catcher game in python.

The game will be single player mode.

The player needs to  catch as many as bubble he/she wants, and score increases accordingly.

The gui window will be under using tkinter module

**Comment by akash435** [comment]
@prathimacode-hub , Please assign this to me under LGM SOC, want to add this game under PyGames scripts.

**Comment by Debashish-hub** [comment]
Please follow the issue template to create the issue @akash435

**Comment by akash435** [comment]
---
Title: Bubble Catcher Game
About: It's a game created with tkinter GUI in python
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [ ] Contributor


I will create a python script to create a game called bubble catcher. In this game needs to catch as many as bubble he/she wants, and score increases accordingly. Also there are many other features in game.

**Comment by akash435** [comment]
@prathimacode-hub , i have updated the issue according to template, please check it.

**Comment by prathimacode-hub** [comment]
Yup, sure. This issue is assigned to you. You can start working on it. @akash435

**Comment by akash435** [comment]
thanks for assigning

**Comment by akash435** [comment]
just one ques, that label of level will be added while merging i guess.

**Comment by Debashish-hub** [comment]
> just one ques, that label of level will be added while merging i guess.

yes, that will be done by admin

**Comment by akash435** [comment]
ok

**Comment by akash435** [comment]
@prathimacode-hub , created a pr for this issue, please check it
