### ISSUE TITLE
Minesweeper Game Using 2D Implementation of Python

### ISSUE THREAD

**Issue by codeaholic-shub** [prathimacode-hub/Awesome_Python_Scripts#193]
Title: Minesweeper Game
About: User can input and enjoy the game Easily.
Name: Shubhankar Poddar
Label: Feature Request

Assignee: ''

 Define You:
 
 * [x]  LGM-SOC'21 Participant
 * [ ]  Contributor

I am going to write python code using 2D implementation for this Game.

Hello @prathimacode-hub ,
Kindly assign this issue to me,
So, I can work on this as soon as Possible !

**Comment by Debashish-hub** [comment]
Can you elaborate the game @codeaholic-shub

**Comment by codeaholic-shub** [comment]
> Can you elaborate the game @codeaholic-shub

Yes , Its the Game in which users enter their input according their will in row and column order ,
Through their input the digging process starts in the game !


### Snapshots of Game Output for clear understanding -

![First Projedct – minesweeper py PyCharm 13-06-2021 20_26_34](https://user-images.githubusercontent.com/65807708/121844086-0788cf80-cd01-11eb-8208-9002d057e11b.png)
![First Projedct – minesweeper py PyCharm 13-06-2021 20_26_45](https://user-images.githubusercontent.com/65807708/121844107-11123780-cd01-11eb-92c5-a1686d4839b9.png)

**Comment by prathimacode-hub** [comment]
Sure, you can proceed further. This issue is assigned to you. @codeaholic-shub
