### ISSUE TITLE
Add another news scraping script

### ISSUE THREAD

**Issue by pragyakhanna11** [prathimacode-hub/Awesome_Python_Scripts#197]
Title | About | Name |Label | Assignee | 
--- | --- | --- | --- |--- 
News Scraping| scrape title, author, time and news details and save them in a txt file | Pragya Khanna | Feature Request|  | 

- [x] LGM SOC participant

**Describe the solution you would like:**
Scrape the above mentioned things from inshorts and save the scraped text to a separate txt file

![image](https://user-images.githubusercontent.com/75221153/121856189-d9f85200-cd11-11eb-8248-93a4196202c0.png)

**Comment by prathimacode-hub** [comment]
News Scraping is already up there in "WebScrapingScripts". News API is as well there in "APIScripts". If you want to work on it. You can enhance the script. Else, you can take up an another issue. So what do your say? @pragyakhanna11

**Comment by prathimacode-hub** [comment]
Sorry, it's been 14 days. And no response on it, about your interest on working as an enhancement. I had to close this issue. If you want to work on this issue, you can raise it up again. @pragyakhanna11
