### ISSUE TITLE
Qrcode Generator

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#198]
Title: Qrcode Generator
About: generating qrcode automatically using pyqrcode lib.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

-> LGM-SOC'21 Participant
  Contributor

Solution: I would like to write script using pyqrcode lib. and generating qrcode whose size and colour can be customized .

**Comment by prathimacode-hub** [comment]
There's one project called QRCode Scanner. Here comes, QR code generator. Sounds good. You can proceed with the issue. @neelshah2409
