### ISSUE TITLE
Image to ASCII Art Converter

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#199]
---
Title: Image to ASCII Art Converter 
About: Implementation of an ASCII Art Converter using the **pywhatkit** module.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'll write a Python script that converts the image to ASCII art using the **image_to_ascii_art** function inside **pywhatkit**.

**Comment by prathimacode-hub** [comment]
Good selection of project. I shall assign this task to you. 👍@Iamtripathisatyam
