### ISSUE TITLE
Hey , I have python project can i add into this repo ?

### ISSUE THREAD

**Issue by Kushal997-das** [prathimacode-hub/Awesome_Python_Scripts#20]

**Comment by prathimacode-hub** [comment]
Yes, sure. You are most welcome to add your python script. @Kushal997-das

**Comment by Kushal997-das** [comment]
> Yes, sure. You are most welcome to add your python script. @Kushal997-das

Please [`Check this out`](https://github.com/prathimacode-hub/Awesome_Python_Scripts/pull/21)

**Comment by prathimacode-hub** [comment]
I have reviewed it. Need few changes in file and folder names. Go through the changes required through PR. @Kushal997-das

**Comment by Kushal997-das** [comment]
> I have reviewed it. Need few changes in file and folder names. Go through the changes required through PR. @Kushal997-das

I replied
