### ISSUE TITLE
GUI Calendar 

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#200]
---
Title: GUI Calendar 
About: Implementation of a GUI Calendar using **tkinter** and  **calendar** module.
Name: Amit Gupta
Label: Feature Request
Assignee: ''
---
Define You:

- [x] LGM-SOC'21 Participant
 Contributor

I'll write a Python script to create a GUI calendar that will take input "Year" as input and As a result, it will give a GUI-based calendar.

**Comment by prathimacode-hub** [comment]
That sounds interesting. Issue is assigned to you. @AmitGupta700
