### ISSUE TITLE
Want to add a script for COVID cases 

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#205]
Title: want to add a script for COVID cases
Name: **Umesh Singh**
Label: Feature Request
Define You
- [x] LGM-SOC'21 Participant
- [ ] Contributor

### Solution
I want to add a Python script under Web Scraping scripts to fetch the Covid-19 cases for any country. I will be fetching the data from a website to show the details like total cases, death, etc.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can start working on it. @Umesh-01
