### ISSUE TITLE
Editable Restaurant MenuCard

### ISSUE THREAD

**Issue by AK-Subodh** [prathimacode-hub/Awesome_Python_Scripts#207]
---
Title | About | Name | Label | Assignee |
----- | ------- |------- | ------ | ---------- | 
Editable Restaurant MenuCard |Use of tkinter to create a restaurant's menu card which has two types of user logins- Admin and customer. Admin could edit the daily menu. Customers could view it. |AK-Subodh |Feature Request

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.** :
- For restaurants who decide daily specials or different menu for each day, they've to change display everyday. Thus, preparing an application like this where they could just simply add/ remove dishes or add/remove descriptions freely while maintaining beautiful UI without having to reprint/change everyday.

**Approach to be followed :**

- Use of classes to create all the functions for each day.
- User login using tkinter- Admin and Customer
- Design of UI using tkinter

**Comment by prathimacode-hub** [comment]
Kindly do the changes for your PR before you get this issue assigned to you. Do you need help to your PR. @AK-Subodh

**Comment by prathimacode-hub** [comment]
This issue is interesting, but issues can be assigned only one at a time. Any help, don't hesitate to ask. @AK-Subodh

**Comment by AK-Subodh** [comment]
> 
> 
> This issue is interesting, but issues can be assigned only one at a time. Any help, don't hesitate to ask. @AK-Subodh

@prathimacode-hub Mam, can you please assign this issue to me now?

**Comment by prathimacode-hub** [comment]
Yes, this issue is assigned to you. @AK-Subodh

**Comment by AK-Subodh** [comment]
Status Update: GUI completed, Classes for functionality are made. Adding functionality and compilation of code is remaining .

**Comment by prathimacode-hub** [comment]
Ok, cool. All the best. Try to complete PR asap. @AK-Subodh

**Comment by prathimacode-hub** [comment]
Any update. @AK-Subodh

**Comment by AK-Subodh** [comment]
> Any update. @AK-Subodh 

I'll upload the code by today, It's almost done. Sorry for the delay Mam!

**Comment by AK-Subodh** [comment]
@prathimacode-hub  Mam, Created the Pull Request. Please review.
