### ISSUE TITLE
Backup WhatsApp Chats to Excel Sheet

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#210]
---
Title: Backup WhatsApp Chats to Excel Sheet
About: Implementation of WhatsApp Backup Chats using some major libraries like **pandas**, **pushbullet**, **OS**, and **requests**.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'll write a Python script that will Backup all the WhatsApp chats and feed them to the excel sheet, we will take the help of some major libraries of python.

**Comment by prathimacode-hub** [comment]
Wow, this is amazing. This issue is assigned to you. You can proceed. @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Ok ma'am, Thanks a lot
