### ISSUE TITLE
TIC TAC TOE in python

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#211]
---
Title: TIC TAC TOE 
About: It's a game created with tkinter GUI in python
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I will create a python script to create a game called TIC TAC TOE. 
In this game player need to play against computer.
The code is developed such that computer will also play optimally against the use.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC, want to add this game in PyGames Script.

**Comment by prathimacode-hub** [comment]
Tic Tac Toe Game, this issue is already been taken and got assigned. You can take up some other issue. All the best. @akash435

**Comment by akash435** [comment]
ok, thnx

**Comment by prathimacode-hub** [comment]
You should never close an issue or PR from your end. @akash435

**Comment by akash435** [comment]
ok sorry , should i reopen this?

**Comment by prathimacode-hub** [comment]
That's Ok. It's already done. Don't repeat it again. @akash435

**Comment by akash435** [comment]
ok
