### ISSUE TITLE
Sending HTML Email 

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#212]
Title: Sending HTML Email using Python
About: Sending HTML syntax Email using yagmail module in python.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

 - [x] LGM-SOC'21 Participant
 - [ ] Contributor

I'll write a Python script that will send HTML email from sender to receiver using just a single module i.e yagmail and 2 of its functions.

**Comment by prathimacode-hub** [comment]
Sounds good. You can proceed with it. @Aditya8821

**Comment by Aditya8821** [comment]
Yes mam it helps to send email contents under HTML tags like h1,h2... and many other syntax.
