### ISSUE TITLE
Tracking Phone Number 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#215]
Title: Tracking phone number
About: Here we can search the location of phone by getting the country code
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

I would like to write a python script using phonenumber library which helps us to detect the location of phone number(it doesn't give live location but it gives the location where phone number was given)

**Comment by prathimacode-hub** [comment]
Sure, go ahead with the issue. Issue assigned. @neelshah2409
