### ISSUE TITLE
ADD: Bank Management System

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [prathimacode-hub/Awesome_Python_Scripts#216]
This is an DataBase Management system for Bank's employee. I will made it using `python`, `tkinter` and `sqlite3`.

**Comment by thegautamkumarjaiswal** [comment]
assign me to it please.

**Comment by prathimacode-hub** [comment]
There is already a Database Management System but it's on daily routine. Would you like to work on this issue? @thegautamkumarjaiswal

**Comment by thegautamkumarjaiswal** [comment]
> There is already a Database Management System but it's on daily routine. Would you like to work on this issue? @thegautamkumarjaiswal

Because It's different from that database management system. It is for Banks to maintain their employees data.

**Comment by prathimacode-hub** [comment]
Sounds interesting. You can start working. @thegautamkumarjaiswal
