### ISSUE TITLE
Website Blocker

### ISSUE THREAD

**Issue by Rutuj-Runwal** [prathimacode-hub/Awesome_Python_Scripts#218]
Title: Website Blocker
About:I would like to build a GUI based website blocker.I'll write a Python script to create a GUI Website blocker that will take input the sites one wants to block as input and As a result, that site will remain blocked for some particular time.
Name: Rutuj Runwal
Label: Feature Request

Define You:

- [x]  LGM-SOC'21 Participant  

Please assign @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Kindly follow the issue template to get it assigned to you. It's an interesting project. You can change up according to your project using the template here in comment. For reference you can check up with the assigned issues. @Rutuj-Runwal

**Comment by Rutuj-Runwal** [comment]
> Kindly follow the issue template to get it assigned to you. It's an interesting project. You can change up according to your project using the template here in comment. For reference you can check up with the assigned issues. @Rutuj-Runwal

I have updated the issue as per template

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can start working. @Rutuj-Runwal
