### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#221]
---
Title: Login System
About: This small project will contain features of login and signup systems as we saw in your daily life.
Name: Amit Gupta
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
 Contributor
I'll write a Python script that wil contain features of login and signup systems as we saw in your daily life. Using this project, you will come to know a little information about how the login systems of all websites/applications work. I will use tkinter module.

**Comment by prathimacode-hub** [comment]
Perfect. This issue is assigned to you. @AmitGupta700
