### ISSUE TITLE
Image pyramiding 

### ISSUE THREAD

**Issue by Komal-99** [prathimacode-hub/Awesome_Python_Scripts#222]
---
Title: Image pyramising
About: feature
Name: Komal
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Describe the solution you'd like...**
I want to add image pyramiding (guassian and laplace ) script in image processing folder. Its implementation and its readme.

**Additional context**
![image](https://user-images.githubusercontent.com/74819092/121944672-85d08a80-cd70-11eb-8d0e-a2ca360943a0.png)

**Comment by Debashish-hub** [comment]
Are you not working on your previous issue #166

**Comment by Komal-99** [comment]
Doing will complete today

**Comment by Debashish-hub** [comment]
Please complete your previous issue first to get it assigned

**Comment by Komal-99** [comment]
Okay

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can proceed. @Komal-99
