### ISSUE TITLE
You_or_ME

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#226]
---
Title: You_or_ME
About: This is a python game where 2 players can play. If the player gets 4 color balls in same line, then the person wins.
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

I thought of making a game. where two people can play easily. As we see, this lockdown we don't know what to do. So, I designed this game. 

**Approach to be followed (optional):**
I will be using python to implement this game.
Please assign this issue to me, I would like to work on this  @prathimacode-hub mam @Debashish-hub sir

**Comment by Debashish-hub** [comment]
Sounds good! This issue is assigned to you @manognyaa . Go ahead
By the way it will come under which script?

**Comment by manognyaa** [comment]
> Sounds good! This issue is assigned to you @manognyaa . Go ahead
> By the way it will come under which script?

Thank you sir.
It will come under PyGameScripts @Debashish-hub

**Comment by manognyaa** [comment]
hello @prathimacode-hub @Debashish-hub 
I have created a pr. 
please guide me if any changes required .
