### ISSUE TITLE
BlackJack Game

### ISSUE THREAD

**Issue by archismansaha** [prathimacode-hub/Awesome_Python_Scripts#227]
---
Title: Black jack Game 
About: This game is made where you will play with computer it's a simplfy version of black jack game but it follows the rules of that game
Name: Archisman Saha
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Though in lockdown we can't go outside of house i build this . It's made with python a simplify version of blackjack game .

**Comment by Debashish-hub** [comment]
Can you please elaborate the game @archismansaha

**Comment by archismansaha** [comment]
yes here we have to pick cards though it's simple version I will show it by list some of the rules is : addition of your cards may not cross 21 if it then you will loss and show bust . if your cards addition is less than 17 you have to pick a card. In the case of the card Ace you can choose it's value by yourself 1 or 11 depending on your condition when on you stopped choosing card delaer(here computer) will reveal the cards winner  will be the higher ones who has higher value in total and if you both had same total it will show a draw

**Comment by Debashish-hub** [comment]
Go ahead @archismansaha

**Comment by Parth-Shete** [comment]
@archismansaha I would like to work on this issue and I will get this issue done in 1-2 days.

**Comment by prathimacode-hub** [comment]
This issue is already taken and ready to be merged. See the label. If you want to work on any issue, kindly open up using the template given. @Parth-Shete
