### ISSUE TITLE
PIP UPGRADE SCRIPT

### ISSUE THREAD

**Issue by hr1shu** [prathimacode-hub/Awesome_Python_Scripts#228]
Title: PIP UPGRADE SCRIPT
About: This is a python automation script made with tkinter framework, it upgrades your pip version.
Name: Rishav Kumar
Label: Feature Request
Assignee: ''

Define You:

 LGM-SOC'21 Participant

Is your feature request related to a problem? Please describe.

I thought upgrading pip without running pip upgrade cmnd and without opening cmd prompt would be cool.

Approach to be followed (optional):
I will be using python to implement this script.

**Comment by Debashish-hub** [comment]
It will come under which scripts @hr1shu

**Comment by hr1shu** [comment]
It's an automation script with gui, so I'll suggest it under automation.
Your call will be final though.

**Comment by prathimacode-hub** [comment]
Yup, you can proceed. Issue is assigned to you. @hr1shu
