### ISSUE TITLE
MEMORY_PUZZLE_GAME

### ISSUE THREAD

**Issue by HitainKakkar** [prathimacode-hub/Awesome_Python_Scripts#231]
Greetings Sir/Mam,

I would like to work on this project and contribute!!
Kindly assign me this issue.
This is regarding LGMSOC.

{Description of project}
This is a match game made using python's gaming module pygame. The program runs a memory game that allows you to turn over cards by clicking the mouse. Each grey box represents the image of an animal hidden by default. If there is a match, the two cards will disappear, leaving a blank white space and giving a message "MATCHED". If not, they will flip back over.
![Memory_Puzzle_game_1](https://user-images.githubusercontent.com/64975064/121996950-2356a900-cdc7-11eb-9225-345b7845d3b2.jpg)
![Memory_Puzzle_game_2](https://user-images.githubusercontent.com/64975064/121996962-294c8a00-cdc7-11eb-829f-3b2d47fce645.jpg)
![Memory_Puzzle_game_3](https://user-images.githubusercontent.com/64975064/121996964-2a7db700-cdc7-11eb-9f09-598ad953a631.jpg)
![Memory_Puzzle_game_4](https://user-images.githubusercontent.com/64975064/121996966-2b164d80-cdc7-11eb-855f-5e9986af3462.jpg)
![Memory_Puzzle_game_5](https://user-images.githubusercontent.com/64975064/121996982-2e113e00-cdc7-11eb-8139-a721c46e30c5.jpg)

**Comment by Debashish-hub** [comment]
Go ahead @HitainKakkar . Issue is assigned to you

**Comment by HitainKakkar** [comment]
Thank you for assigning me this issue!!
I will work on this and make a PR soon!!

**Comment by HitainKakkar** [comment]
I have made a PR for this issue.
Kindly check.
#246

**Comment by HitainKakkar** [comment]
Greetings Mentors!!
Kindly assign this issue a level , so that it can be considered for scoring in LGMSOC.
Thank you!!

**Comment by Debashish-hub** [comment]
> Greetings Mentors!!
> Kindly assign this issue a level , so that it can be considered for scoring in LGMSOC.
> Thank you!!

You have not created a valid PR for this @HitainKakkar

**Comment by HitainKakkar** [comment]
No Problem!!
I will create a new  PR!!

**Comment by prathimacode-hub** [comment]
You should never close issues or PR from your end. @HitainKakkar

**Comment by prathimacode-hub** [comment]
I reopened this issue. Are you going to work on it? You had created and closed the issue. But haven't got any PR regarding the same. @HitainKakkar

**Comment by HitainKakkar** [comment]
Sure!!
I will make a PR soon!!

**Comment by prathimacode-hub** [comment]
Cool, good to know. 👍@HitainKakkar

**Comment by HitainKakkar** [comment]
I have made a new PR , after making the required link.
Kindly close this PR and check the PR #481
