### ISSUE TITLE
All Information About Country

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#233]
Title: All Information About Country
About: We can find all the information  like currency ,time zone , capital and many more.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:
- [x] LGM-SOC'21 Participant
- [ ] Contributor

I would like to write a script which will give all the information like area , border area , capital ,currency and many more using the countryinfo library.

**Comment by Debashish-hub** [comment]
Get your previous issue #215 completed first to get it assigned @neelshah2409

**Comment by neelshah2409** [comment]
Yes sir , I had made a PR for that so please kindly review it.
And after completing that I will continue with this.

**Comment by Debashish-hub** [comment]
> Yes sir , I had made a PR for that so please kindly review it.
> And after completing that I will continue with this.

Issue is assigned to you
