### ISSUE TITLE
Text Extractor from PDF 

### ISSUE THREAD

**Issue by Sakalya100** [prathimacode-hub/Awesome_Python_Scripts#234]
Title: Text Extractor from PDF 
About: We can extract the text in any PDF file using this script
Name: Sakalya Mitra
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem

The script will extract text from any pdf file. We can use this script to extract text and then perform various manipulation on the text.

**Comment by Debashish-hub** [comment]
Can you please elaborate @Sakalya100

**Comment by Sakalya100** [comment]
Yes sure @Debashish-hub . The script I will make is using a module named PyPDF2 which will allow you to extract text from any pdf file. I am also thinking of adding a feature where we can extract text, modify the text in pdf file and convert that into a pdf file. Thats what my issue is about.

**Comment by prathimacode-hub** [comment]
Ok, sure. this issue is allotted to you. You can go ahead. @Sakalya100
