### ISSUE TITLE
Voice Assistant using Python

### ISSUE THREAD

**Issue by Paras0-7** [prathimacode-hub/Awesome_Python_Scripts#235]
I want to add a voice assistant which can perform tasks such as : 
i) get information and read it
ii) play music
iii) send emails.
@prathimacode-hub @Debashish-hub  can you please assign it to me under LGM-SoC.

**Comment by prathimacode-hub** [comment]
Yup, this issue is assigned to you. You can proceed. @Paras0-7

**Comment by Paras0-7** [comment]
> Yup, this issue is assigned to you. You can proceed. @Paras0-7

Thanks @prathimacode-hub .
