### ISSUE TITLE
Notes panel

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#237]
---
Title: Notes 
About: I would like to create a notes panel where we can note down the important things.
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
As, I am a student I face many issues noting down. sometimes I may not find a book to note the points. So, thought of making a notes app where you can add anything you like. 
for instance: you can add the groceries list, vegetables list.. etc.

**Approach to be followed (optional):**
I will be using python for this issue.

please assign this issue to me, I would like to work on this @prathimacode-hub @Debashish-hub

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can start working. @manognyaa

**Comment by manognyaa** [comment]
> This issue is assigned to you. You can start working. @manognyaa

Thank you mam @prathimacode-hub
