### ISSUE TITLE
Movie Information Detailer

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#241]
Title: Movie Information Detailer
About: We can find all the information like year of release , full name of movie , cast of movie.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

I would like to write a script which will give all the information about movie like year and cast of the movie using imdb library.

**Comment by prathimacode-hub** [comment]
Is this an API script? Can you please elaborate? @neelshah2409

**Comment by neelshah2409** [comment]
no mam we are not using api but using imdb library for getting year of release and  movie cast .

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. @neelshah2409
