### ISSUE TITLE
Event Handling

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#247]
---
Title: Event Handling
About: Event Handling In Tkinter Python means to bind the keyboard or mouse buttons to the Tkinter and use them to call some functions.
Name: Amit Gupta
Label: Feature Request
Assignee: ''
---
Define You:

- [x] LGM-SOC'21 Participant
 Contributor
I'll write a Python script to bind the keyboard or mouse buttons to the Tkinter and use them to call some functions.
We use the bind() function to bind keys and functions to each other.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed with the issue. @AmitGupta700
