### ISSUE TITLE
Extracting Info from IP Address (Using API)

### ISSUE THREAD

**Issue by its-me-debk007** [prathimacode-hub/Awesome_Python_Scripts#248]
**Title:**  Extracting Info from IP Address (Using API)

**About:** Gives you info related to the IP Address that is entered.
                  

**Name:** Debashish Kundu

**Label:** Feature Request

**Assignee:** ''

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
A python program that uses API to extract information about a particular IP Address.
By default, gives the info related to the IP Address of the current user.
This program is related to APIScripts.

**Comment by Debashish-hub** [comment]
Please follow the issue template @its-me-debk007

**Comment by its-me-debk007** [comment]
> Please follow the issue template @its-me-debk007

Oh Sorry! @Debashish-hub
