### ISSUE TITLE
The Indian Flag

### ISSUE THREAD

**Issue by shreyamalogi** [prathimacode-hub/Awesome_Python_Scripts#251]
---
Title: The Indian Flag
About: To draw an Indian Flag
Name: Malogi Shreya
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Describe the solution you'd like...
Here, I will be using python turtle graphics. (GUI)

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can proceed. @shreyamalogi
