### ISSUE TITLE
Voting System

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#252]
Title: Voting System
About: I would like to create a simple voting system in which if the voter is eligible or he had done the voting all the things can be done
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor
Describe the solution you'd like...
As all have doubt at some point how voting system might be working at some point but for that I would like to write a script in which if voter is eligible for voting, he had voted previously and at last the results of election can be seen.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can start working. @neelshah2409
