### ISSUE TITLE
Twitter Tweet Sentimental Analysis Web App

### ISSUE THREAD

**Issue by shantamsultania** [prathimacode-hub/Awesome_Python_Scripts#253]
I am thinking of creating a web app in which a person may enter a topic and that topic will be web scraped from Twitter and on the result we can also perform sentimental analysis and divide the same into multiple areas 
if possible assign me this under LGM - SOC  for GUI based Script 
thanks

**Comment by prathimacode-hub** [comment]
It's been very long since you had raised an issue, but no response yet. So unfortunately I had to close this issue, you can create up a new issue to show ur interest if you are willing to work on this script again. @shantamsultania
