### ISSUE TITLE
Real-Time Stock Price

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#261]
Title | About | Name | Label | Assignee
---- | -------- | ------ | ------ | ---------
Real-Time Stock Price | web-scraping script for getting real time stock price | Sonali Bedade | Feature Request |

- [x] LGM-SOC'21 Participant

It will be a web scraping script which will fetch the current stock price for companies that are listed in an excel sheet and calculates the total profit/loss.

**Comment by prathimacode-hub** [comment]
This issue is already done and merged. Kindly take up an another issue to work on. @sonaliBedade
