### ISSUE TITLE
Real Time Currency Converter

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#262]
Title: Real-Time Currency Converter
About: Implementation of the script which converts the currency rate from one to other according to real-time rate.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

 - [x] LGM-SOC'21 Participant
 - [x] Contributor
I'll write a Python script which will convert the inputed currency in to the currency which user selects. It is done by using (GUI)tkinter, API and some other modules of python.

**Comment by prathimacode-hub** [comment]
This issue is already done and merged. Kindly take up an another issue. @Aditya8821

**Comment by Aditya8821** [comment]
Ok mam
