### ISSUE TITLE
Extracting Information from IP Address (Using API)

### ISSUE THREAD

**Issue by its-me-debk007** [prathimacode-hub/Awesome_Python_Scripts#266]
**Title:**  Extracting Information from IP Address (Using API)

**About:** Gives you information related to the IP Address that is entered.
                  

**Name:** Debashish Kundu

**Label:** Feature Request

**Assignee:** ''

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
A python program that uses API to extract information about a particular IP Address.
By default, gives the info related to the IP Address of the current user.
This program is related to APIScripts.

**Comment by prathimacode-hub** [comment]
It's a different script. Good choice. This issue is assigned to you. You can proceed. @its-me-debk007

**Comment by its-me-debk007** [comment]
Thank you very much @prathimacode-hub  ma'am!
This is my first project in LGMSoc :)

**Comment by prathimacode-hub** [comment]
Welcome to the repo. All the best.
