### ISSUE TITLE
Get movie data

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#268]
Title | About | Name | Label | Assignee
----- | ------ | ------- | ------ | ----------
Get movie data | Getting information of any movie using imdb library | Sonali Bedade | Feature Request |

- [x] LGM-SOC'21 Participant

This program will fetch details like year of release, cast, etc of any movie using imdb library

**Comment by prathimacode-hub** [comment]
This issue is already taken and merged. Sorry to say, but kindly take up an another issue. Before you raise, do check if the script you want to work on is assigned or merged. So that your efforts don't go wasted. @sonaliBedade
