### ISSUE TITLE
Flames

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#270]
---
Title: Flames
About: This game will result the output of relationship status like friends, enemy, sibilings, etc.
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
It is the common game where everyone once in there life have used or played. So, I created this game for those who don't know.
**Approach to be followed (optional):**
I will be using python.
and this will come under Pygame script.

@prathimacode-hub @Debashish-hub 
please assign this issue to me, I would like to work on this.

**Comment by prathimacode-hub** [comment]
Yes, this issue is assigned to you. Interesting. You can proceed. @manognyaa
