### ISSUE TITLE
Can i implement tower of hanoi in python.

### ISSUE THREAD

**Issue by richabh456** [prathimacode-hub/Awesome_Python_Scripts#272]

**Comment by prathimacode-hub** [comment]
Yes you can, But add proper template to get issue assigned to you. @richabh456

**Comment by richabh456** [comment]
Tower of hanoi is a mathematical puzzle where we have 3 rods and n disk, the main objective of this puzzle is to move the entire stack to one rod, by obeying some rules.

**Comment by prathimacode-hub** [comment]
Yes, but to get issue assigned and to know you as a LGMSOC participant. There is a template you need to follow while creating an issue or PR. You can find that in README file of the project
All the details are been provided in README and CONTRIBUTING GUIDELINES to get better understanding of how to proceed. @richabh456

**Comment by richabh456** [comment]
Name: Richa Bharti
Implementation : tower of hanoi
label : feature request

**Comment by prathimacode-hub** [comment]
> Name: Richa Bharti
> Implementation : tower of hanoi
> label : feature request

full template needed

**Comment by richabh456** [comment]
Title: Tower of hanoi
About: This is a puzzle game which contains 3 rods and n disk.
Name: Richa Bharti
Label : feature requested
Assignee:

Defines you: Lgmsoc'21 Participant.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Ma'am i am not getting the full template. i am a Lgmsoc'21 participant

Yes, I know. But to assign the labels template is important. You shall check up with assigned PR's

To make things simple, this is the sample template.

https://github.com/prathimacode-hub/Awesome_Python_Scripts/issues/266 @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub is it sufficient ma'am?

**Comment by prathimacode-hub** [comment]
It's good if you add a solution you would expect out of this issue. That's minimum. Anyways I shall assign the issue to you. Next time, you can make it better. @richabh456

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can proceed. @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub SURE ma'am i will improve myself.

**Comment by richabh456** [comment]
@prathimacode-hub Thank you for your help ma'am i will try for sure.

**Comment by Debashish-hub** [comment]
Hey @richabh456  Any update?

**Comment by Ashu-1309** [comment]
@prathimacode-hub can you assign me this work ? I want to work on it .

**Comment by prathimacode-hub** [comment]
We shall wait for a day more, if no response issue will be assigned to you. @Ashu-1309
