### ISSUE TITLE
Convert Image into Pencil Sketch

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#273]
Title: Convert Image into Pencil Sketch
About: Implementation of this script is done by using the cv2 module and some of its functions are used.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

 -[x] LGM-SOC'21 Participant
 -[x] Contributor
I'll write a Python script that will convert the image into its pencil sketch, this is done by use of cv2 module and its functions.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can proceed. @Aditya8821
