### ISSUE TITLE
Video To Audio

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#275]
Title: Video To Audio
About: Here we will convert video(.mp4) to audio(.mp3)
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor
Describe the solution you'd like...
Here using pytube lib. we will get the youtube video and using the os lib we will convert video to audio.

**Comment by prathimacode-hub** [comment]
Yes, absolutely. You can add both video and audio in "Media" folder. And add the link to the README. This issue is assigned to you. @neelshah2409
