### ISSUE TITLE
Fibonacci sequence generator 

### ISSUE THREAD

**Issue by palakagarwal5230** [prathimacode-hub/Awesome_Python_Scripts#277]
**Problem:**
Implement a python generator for a Fibonacci sequence.
Title: Fibonacci sequence generator
About: It will implement a python generator for a Fibonacci sequence.
Name: PALAK AGARWAL
Label: Feature Request
Assignee: ''

Define You:

[ ] LGM-SOC'21 Participant
[ ] Contributor
Describe the solution: I would write a python script for this problem

**Comment by palakagarwal5230** [comment]
I am a LGM-SOC'21 Participant and has opened this issue. Assign me to solve this

**Comment by prathimacode-hub** [comment]
Kindly follow the template given to get issue assigned to you. @palakagarwal5230

**Comment by Parth-Shete** [comment]
@palakagarwal5230  I would like to work on this issue.

**Comment by prathimacode-hub** [comment]
@Parth-Shete You kindly raise your own issue, you want to work on. Participants raise their own issue to show their interest and get assigned to.

**Comment by Priyanshi-Rai** [comment]
@prathimacode-hub i would like to contribute in this project

**Comment by palakagarwal5230** [comment]
> Kindly follow the template given to get issue assigned to you. @palakagarwal5230

Done!

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can proceed. @palakagarwal5230

**Comment by prathimacode-hub** [comment]
No update from you yet. @palakagarwal5230

**Comment by palakagarwal5230** [comment]
@prathimacode-hub my laptop is not working, I will be able to complete it after 28 june only

**Comment by prathimacode-hub** [comment]
That would be so long, Are you sure you would complete it then? @palakagarwal5230

**Comment by ainy-123** [comment]
> That would be so long, Are you sure you would complete it then? @palakagarwal5230

I am LGM-SoC'21 participant. I want to work on this issue. will you please assign this to me?
I'll raise the PR within 24 hrs of issue assignment.

**Comment by palakagarwal5230** [comment]
> That would be so long, Are you sure you would complete it then? @palakagarwal5230

  
I've no other option

**Comment by prathimacode-hub** [comment]
Ok, hopefully. @palakagarwal5230

**Comment by prathimacode-hub** [comment]
Sorry to say, but unfortunately I have to assign this issue to someone else to be fair enough with others. You can take up a new issue to work on, when your laptop is ready. Issue can't be held for this long. @palakagarwal5230

**Comment by Priyanshi-Rai** [comment]
I would love to work on this project with some other additional features.  Assign it to me

**Comment by prathimacode-hub** [comment]
Sure, issue is assigned. @Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
Thank you so much Ma'am . I'll make all the necessary changes in this according to me and create a PR as soon as possible.

**Comment by prathimacode-hub** [comment]
> Thank you so much Ma'am . I'll make all the necessary changes in this according to me and create a PR as soon as possible.

Good to see your dedication. @Priyanshi-Rai
