### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by sahilsingh2402** [prathimacode-hub/Awesome_Python_Scripts#278]
**Title:** Snake Game
**About:** This game will be a python game based on the original 'Snake' game which first appeared in 1997 on the Nokia 6110.
**Name:** Sahil Singh

Describe the solution you'd like: **It is the very first mobile games which was launched in the year 1997. Everyone would have played it once in there lifetime. I would like to create this game  in python.**
Approach to be followed (optional):
**I will be using python libraries such as turtle, pygame and others.** 

@prathimacode-hub @Debashish-hub 
Please assign this issue to me, I would like to work on it.

**Comment by prathimacode-hub** [comment]
This issue is already taken and merged as well. You can take up an another issue to work on. All the best. Welcome to the repository. @sahilsingh2402

**Comment by sahilsingh2402** [comment]
Ok

**Comment by prathimacode-hub** [comment]
You should never close an issue or PR from your end. @sahilsingh2402
