### ISSUE TITLE
Contrast image enhancement

### ISSUE THREAD

**Issue by BryanMed** [prathimacode-hub/Awesome_Python_Scripts#280]
**Title:** contrast image enhancement
**About:** Contrast is the difference in luminance that makes an object distinguishable from other objects in an image, I'll try to enhance the image of low contrast images
**Name:** Bryan Medina
**Label:** Feature Request
Assignee: ''

**Define You:**
- [ ] LGM-SOC'21 Participant
- [x] Contributor

**Describe the solution you'd like:**
Using histogram equalization, we can convert a low contrast image into a high contrast image, useful in medical image applications

**Comment by prathimacode-hub** [comment]
Wow, that sounds interesting. You can go ahead. Welcome to the repo. @BryanMed
