### ISSUE TITLE
Music player using Pygame

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#282]
---
Title: Music player using Pygame
About: A simple music player which has a list of music , among which we can select one and play it, there are several options like play, stop, resume and pause , Here GUI (tkinter) is used for display purposes
Name:  Jayapritha N
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Cool. This issue is assigned to you. You can start working on it. @coding-geek21
