### ISSUE TITLE
Registration Form Interface

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#289]
Title: Registration Form Interface Using Tkinter
About: Implementation of this script is done by using Tkinter module and took the help of some of its functions.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

-[x] LGM-SOC'21 Participant
-[x] Contributor
I'll write a Python script that will display an interface for a registration form, this is done only by the use of Tkinter and its functions.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. @Aditya8821
