### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#290]
Title: Currency Converter
About: Here we will convert currency using the currency dictionary which we will get from google.
Name:  Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
 - [ ] Contributor

Description: We can convert currency from one to another we just need information about all currency and rate from google and convert and keep it in a file as a dictionary so we can convert easily.

**Comment by prathimacode-hub** [comment]
This issue is already taken and merged as well. Kindly take up an another issue. @neelshah2409
