### ISSUE TITLE
Real Time Face Detection using OpenCv

### ISSUE THREAD

**Issue by Nithin2528** [prathimacode-hub/Awesome_Python_Scripts#292]
I am a LGMSOC participant . Can I contribute this script.
About: Detects the human faces in real time using the webcam
Modules: OpenCv

**Comment by prathimacode-hub** [comment]
This issue is already been taken and merged. You can take up an another issue, but also make sure you follow the  issue template for it. @Nithin2528

**Comment by Nithin2528** [comment]
I'm sorry im new to open source , what's template issue template?
and Shall i close this Issue? @prathimacode-hub

**Comment by prathimacode-hub** [comment]
That's Ok. No, you should never close issue or PR from your end. I shall do that.
All the templates are provided in README file of the project. To know more briefer of how template should look like, you can refer up with the assigned issues. That'll give you the answer. No worries, if you're new to open source. I can guide you further. @Nithin2528

**Comment by Nithin2528** [comment]
Okay.
How to add those templates I'm unable to add them while creating the issue? @prathimacode-hub

**Comment by prathimacode-hub** [comment]
You can check with the assigned issues to know how templates look like. Why did you close the issue? You should never close it from your end. @Nithin2528

**Comment by Nithin2528** [comment]
I've checked that ma'am I understood that but I didn't understand how to use them.
I did not close the issue ma'am ☹️ @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Ok, but it says, issue is closed from your end, Never mind. You can create up a new issue to work on if you're interested to. By the way this issue is already done. @Nithin2528

**Comment by Nithin2528** [comment]
I have many ideas to raise but I didn't understand the templates and all how to use them so I didn't raise any @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> I have many ideas to raise but I didn't understand the templates and all how to use them so I didn't raise any @prathimacode-hub

Ok, are you on slack or discord. Ping me personally. I shall guide you.
