### ISSUE TITLE
Job Search Tool

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#293]
Title | About | Name | Label | Assignee
----- | ------- | ------ | ------ | ----------
Job Search Tool | Fetching job data from indeed website | Sonali Bedade | Feature Request | 

- [x] LGM SOC'21 Participant

A web scraping project which will fetch details of job from indeed website

**Comment by prathimacode-hub** [comment]
Welcome to Webscraping. Yup, this issue is alloted to you. You can proceed. @sonaliBedade
