### ISSUE TITLE
Image to icon converter

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#298]
---
Title: Image to icon converter
About: It's a GUI script in python
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this i will create a GUI Script that takes any .png, .jpg, or any image and convert it to .ico file i.e. icon file.
This icon file is used to change the icon in any website title bar, or and gui window title bar, etc.

**Comment by prathimacode-hub** [comment]
Interesting issue. That's awesome. This issue is allotted to you. You can proceed. @akash435

**Comment by akash435** [comment]
Thanks
