### ISSUE TITLE
Battery Automation Script

### ISSUE THREAD

**Issue by pankaj892** [prathimacode-hub/Awesome_Python_Scripts#30]
@prathimacode-hub I wish to add a Python Script that automatically provides a notification to user when battery level changes

**Comment by prathimacode-hub** [comment]
That's a wonderful script. It goes into this [repository](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/AutomationScripts)

**Comment by prathimacode-hub** [comment]
You had done an exceptional job. Well done. ✔👍 @pankaj892

**Comment by pankaj892** [comment]
Thanks @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Mention not @pankaj892
