### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [prathimacode-hub/Awesome_Python_Scripts#303]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@prathimacode-hub pls assign this issue to me.

**Comment by ishitakapoor26** [comment]
Like this

![score card](https://user-images.githubusercontent.com/78542333/122353172-6c486200-cf6d-11eb-8ba0-70426ccaab5f.PNG)

**Comment by prathimacode-hub** [comment]
Do you want to work on thism like you did for other repo? @ishitakapoor26

**Comment by ishitakapoor26** [comment]
> Do you want to work on thism like you did for other repo? @ishitakapoor26

ya sure!

**Comment by prathimacode-hub** [comment]
Go ahead. Issue assigned. @ishitakapoor26
