### ISSUE TITLE
Python script to get the map of a city.

### ISSUE THREAD

**Issue by Paras0-7** [prathimacode-hub/Awesome_Python_Scripts#305]
This python script will get the map of the location provided by the user.
@prathimacode-hub  Can you assign me this issue under LGM -SOC'21.

**Comment by Debashish-hub** [comment]
Please be elaborative and follow the issue template @Paras0-7

**Comment by prathimacode-hub** [comment]
Why did you close the issue? @Paras0-7

**Comment by Paras0-7** [comment]
> Why did you close the issue? @Paras0-7

I thought I need to create a new one.

**Comment by prathimacode-hub** [comment]
You should never close from your end. Kindly remember that next time. @Paras0-7
