### ISSUE TITLE
Chess Game

### ISSUE THREAD

**Issue by sahilsingh2402** [prathimacode-hub/Awesome_Python_Scripts#306]
**Title :** Chess Game in python
**About :** Two player chess game in python
**Name :** Sahil Singh
**Label :** Feature Request
**Assignee :**

**LGM-SOC'21:** Participant

**Description :** I would like to create a simple two player chess game in python using some of its libraries. Please assign this to me. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. This issue is assigned to you. @sahilsingh2402

**Comment by prathimacode-hub** [comment]
Is it all fine? No update from you. @sahilsingh2402

**Comment by sahilsingh2402** [comment]
It's just about to finish. I am fixing all the minor bugs, and would commit the final one to the master branch. I just want one more day of time :( @prathimacode-hub
