### ISSUE TITLE
Converting Text To Audio

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#307]
Title: Converting Text To Audio 
About: Here we will convert text to audio using pyttsx3 and pyPDF library of python.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description: Many times we get bored of reading so why not we convert that pdf to audio book .We can do that using pyttsx3 and pyPDF library .Here we can also specify the page number from which we need to start to read.

**Comment by prathimacode-hub** [comment]
This issue is already done. You can take up an another issue to work on.👍 @neelshah2409
