### ISSUE TITLE
Checking an Armstrong/Narcissistic number

### ISSUE THREAD

**Issue by Priyanshi-Rai** [prathimacode-hub/Awesome_Python_Scripts#311]
Title : Is it an Armstrong or not

About : We will check here whether the number is an armstrong no. or not by using some basic python commands.
Name : Priyanshi Rai
Label : Feature request
Script : BasicPythonScript

Define you:
- [x] LMG SOC'21 Participant
- [x] Contributor
-------------------------------------------------------------------------------------------------------------------------------------------

**What is an ARMSTRONG number?**
In simple words , an Armstrong number in a given number that is equal to the sum of its own digits each raised to the power of the number of digits.
e.g
153=1^3+5^3+3^3
1643=1^4+6^4+4^4+3^4

**### description** : we will use looping and conditional statements to perform this task.

**Comment by prathimacode-hub** [comment]
Your issue needsa template. You can check up with other assigned issues to know how template looks like. @Priyanshi-Rai

**Comment by prathimacode-hub** [comment]
All the best, this issue is assigned to you. Welcome to the repo. @Priyanshi-Rai
