### ISSUE TITLE
Rock paper Scissor Game

### ISSUE THREAD

**Issue by Nithin2528** [prathimacode-hub/Awesome_Python_Scripts#312]
Rock Paper Scissor Game using Python.

**Comment by prathimacode-hub** [comment]
This is already done. Take up an another issue to work on. Before you raise an issue, check if it's already in the repo or it's been assigned. One more thing while raising an issue, follow the template given to get issues assigned to you.
@Nithin2528

**Comment by Nithin2528** [comment]
Where can I check if the issue's already been raisen? 
Ma'am I didn't get to know how to add those templates or labels of LGMSOC 
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
You can refer other assigned issues to know how template looks like. And to see if issue is been raised, you can check up with issues that are already assigned. Also in the repo, to see if issue is already available or not. @Nithin2528

**Comment by Nithin2528** [comment]
Okay ma'am@prathimacode-hub
