### ISSUE TITLE
Script to display the calendar of the given date

### ISSUE THREAD

**Issue by DhirajChauhan40** [prathimacode-hub/Awesome_Python_Scripts#315]

**Comment by prathimacode-hub** [comment]
This issue is already taken and follow the template given to raise the issue. @DhirajChauhan40

**Comment by DhirajChauhan40** [comment]
sorry my bad
Next time i will make sure

**Comment by prathimacode-hub** [comment]
You should never close issue or PR from your end. @DhirajChauhan40

**Comment by DhirajChauhan40** [comment]
@prathimacode-hub 
I'm so sorry, I didn't know about that, 
I'm new to this open-source, I will make sure next time
 I won't do that mistake 
should i open again?

**Comment by DhirajChauhan40** [comment]
@prathimacode-hub I wanted to ask if I wanna add some existing features to an already merged issue, can I do it?

**Comment by prathimacode-hub** [comment]
Yes, you can enhance the project more deeper. @DhirajChauhan40

**Comment by DhirajChauhan40** [comment]
@prathimacode-hub i would like to make a mad libs game , is this already taken?

**Comment by prathimacode-hub** [comment]
It's already taken and merged. @DhirajChauhan40

**Comment by DhirajChauhan40** [comment]
@prathimacode-hub can you tell me a way to search the issues and merged things, without going into every folder?

**Comment by prathimacode-hub** [comment]
This is how it's checked. No shortcuts. You can check through issues and pr tab. @DhirajChauhan40
