### ISSUE TITLE
Adventure Based Game(Text Game)

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#318]
Title: Adventure Based Game
About: It will be a adventure like fun game ,here questions will be prompted like you want to run or jump and at the end if you give all correct answer then you won.  
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
 - [ ] Contributor
Describe the solution: I would write a python script for this adventure like fun game.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. you can proceed. @neelshah2409
