### ISSUE TITLE
Can i add Checklist app in python

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/Awesome_Python_Scripts#320]
Title: Checklist app in python
About: It will be basically a todo list app where you can add, delete and save your tasks
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

Define You:

[x] LGM-SOC'21 Participant
 Contributor
Describe the solution: I would write a python script for this app

**Comment by prathimacode-hub** [comment]
Kindly follow the issue template to get issue assigned to you. You can refer with other assigned issues, to know how it looks like. @siddhi-244

**Comment by siddhi-244** [comment]
@prathimacode-hub  done

**Comment by prathimacode-hub** [comment]
You can proceed. This task is assigned to you. @siddhi-244

**Comment by siddhi-244** [comment]
Thank you !

**Comment by siddhi-244** [comment]
Maam I am done with the project can uh tell me the further steps to make a pr! @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> Maam I am done with the project can uh tell me the further steps to make a pr! @prathimacode-hub

Sure, I shall guide you. Are you new to github? @siddhi-244

**Comment by siddhi-244** [comment]
No no I can make a pr but there must be some documentation rules !

**Comment by siddhi-244** [comment]
I want to know about the documentation rules

**Comment by prathimacode-hub** [comment]
Documentation rules are provided in README and CONTRIBUTING GUIDELINES of the project repo. @siddhi-244

**Comment by siddhi-244** [comment]
Ok thank you I will be doing it till the eve.

**Comment by siddhi-244** [comment]
Please check my pr @prathimacode-hub
