### ISSUE TITLE
Desktop Notification

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#321]
Title: Desktop Notification
About: In this busy schedule people always forget to take a break so it will be great if we remind them so we can make a desktop notifier which can show them a notification conveying them like it had been 2 hours working take a break.  
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor
Describe the solution: So  using time and plyer library I would write a script which will send a notification on desktop after particular time.

**Comment by prathimacode-hub** [comment]
One by one please. Other issue is already assigned to you. 
@neelshah2409

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can proceed. @neelshah2409
