### ISSUE TITLE
Zodiac Sign Finder

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#326]
---
Title: Zodiac Sign Finder
About: It's a GUI script in python
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this user will input his/her date and month of his/her D.O.B. (Date Of Birth), and output will get is his/her correspoding gui, with little information about corresponding zodiac sign.

The GUI will be totally under tkinter.

**Comment by akash435** [comment]
@prathimacode-hub , if this is valid please assign this to me under LGM SOC, can add this under GUIScripts.

**Comment by prathimacode-hub** [comment]
Yeah, sure. This issue is assigned to you. You can start working on it. @akash435

**Comment by akash435** [comment]
thanks
