### ISSUE TITLE
Distance Between Two Places

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#332]
Title : Distance Between Two Places
About : We can find distance by getting their longitude and latitude using geopy library.
Name : Neel Shah
Label : Feature Request
Assignee :

- [x] LGM-SOC'21: Participant

Description : So here we can find distance between any two places places using geopy library by getting their longitudes and latitudes.

**Comment by Ashu-1309** [comment]
I want to work on this code . can you assign me this work.

**Comment by prathimacode-hub** [comment]
This issue is already taken and merged, kindly take up an another issue to work on. @neelshah2409 

There is already an issue assigned to you. @Ashu-1309
