### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#333]
I would like to create a converter that will be use to convert Celsius into Fahrenheit and vice versa.

**Comment by Ashu-1309** [comment]
Can you assign me this work.

**Comment by Debashish-hub** [comment]
Do follow the issue template and be elaborative @Ashu-1309

**Comment by Ashu-1309** [comment]
Title : Temperature  Converter 
About : Through this code, we will able to convert Celsius into Fahrenheit and Fahrenheit into Celsius.
Name : ASHUTOSH KUMAR SAW
Label : Feature Request
Assign:"

Define You:
LGM-SOC'21 Participant
Contributor

**Comment by prathimacode-hub** [comment]
Yup, this issue is assigned to you. You can start working on it. @Ashu-1309

**Comment by Ashu-1309** [comment]
Thank you

**Comment by prathimacode-hub** [comment]
Why had closed your PR? @Ashu-1309

**Comment by Ashu-1309** [comment]
It was done by mistake .

**Comment by prathimacode-hub** [comment]
> It was done by mistake .

You should never close your issues or PR from your end. Kindly reopen the PR and work on your project. @Ashu-1309

**Comment by Ashu-1309** [comment]
I open the PR .it is ready to merge , Can you please check it .

**Comment by prathimacode-hub** [comment]
> I open the PR .it is ready to merge , Can you please check it .

I had checked and reverted with the things to be done.
