### ISSUE TITLE
encode decode

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#334]
---
Title: Encode Decode
About: This issue is all about to encode and decode messages using a common key. 
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**

**Approach to be followed (optional):**
I will be using python for this work.

@prathimacode-hub mam, @Debashish-hub sir, please assign this issue to me, I would like to work on this.

**Comment by prathimacode-hub** [comment]
Yes, this issue is assigned to you. You can proceed. @manognyaa
