### ISSUE TITLE
Grade Calculator GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#335]
Title: Grade Calculator GUI
About : We will check here grade of three subjects and it will calculate average ,total and Pass/Fail. 
Name : Neel Shah
Label : Feature request

Define you:

- [x] LMG SOC'21 Participant
    Contributor

Description: We will use tkinter to generate a gui grade calculator ,so we just need to give the marks of subject as input and we will get average ,total and status of a student.

**Comment by prathimacode-hub** [comment]
I thought, you would take up a higher level issue next time. Are u sure you want to work on this? 🙂@neelshah2409

**Comment by neelshah2409** [comment]
Okay mam Please assign me another issue first then this.

**Comment by rammya29** [comment]
I want to work on this. Even though it is small project I would like to implement some new features, can you assign this to me?

**Comment by prathimacode-hub** [comment]
You can raise it on own by creating up a new issue. @rammya29
