### ISSUE TITLE
Wifi Password Fetcher

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#338]
Title: Wifi Password Fetcher
About : We will get all the wifi passwords from the device using the subprocess library and its function and copying to our clipboard using pyperclip.
Name : Neel Shah
Label : Feature request

Define you:

- [x]  LMG SOC'21 Participant
- [ ] Contributor

Description: Here we will fetch all the wifi passwords that were once used on the device using subprocess lib and then copying it to clipboard using pyperclip.

**Comment by prathimacode-hub** [comment]
Oh, interesting project. Shall I assign this issue to you. @neelshah2409

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned it to you. You can proceed. @neelshah2409

**Comment by neelshah2409** [comment]
yes mam ,Please assign me.
