### ISSUE TITLE
Add Splash Screen to Zodiac Sign Finder script in GUIScripts

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#342]
---
Title: Add splash screen to Zodiac Sign Finder Script
About: It's a GUI script in python
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In the Zodiac Sign Finder Script that is in GUI script, want to add splash screen before the main window opens.
The splash screen will appear for 10 sec before the application opens
And after the 10 secs are over, the splash screen will get close and the main application window will open.

The splash will be like this, gif image,
![splash](https://user-images.githubusercontent.com/57003737/122577794-d138b080-d070-11eb-9b44-6efe986e05cb.gif)

**Comment by akash435** [comment]
@prathimacode-hub , if this enhancement is script is valid then please assign me this under LGM SOC, I can add this splash screen before the main window of Zodiac Sign Finder Script opens.

**Comment by prathimacode-hub** [comment]
Sure, you can add up your enhancement. Only thing is create separate README file for the work you do. Others can be brought out together. Good Initiation. @akash435
