### ISSUE TITLE
Facts_Generator

### ISSUE THREAD

**Issue by Adarsh357** [prathimacode-hub/Awesome_Python_Scripts#344]

**Comment by prathimacode-hub** [comment]
First, you have to create an issue and get it assigned to you. Then you have to start working on it and do a PR. This is not the right format. And also all templates are mentioned in README file of the project. @Adarsh357

**Comment by Adarsh357** [comment]
Ok

**Comment by prathimacode-hub** [comment]
It's been 10 days, do you really want to work on this issue. @Adarsh357

**Comment by chandu6111** [comment]
@prathimacode-hub 
I think this issue is about generating random facts in a program and then printing it to the console, is it right?
If that is so, this is quite a small code, please assign me this issue. I will complete it

**Comment by prathimacode-hub** [comment]
Yes, right. First complete the earlier issue assigned, then you can work on this. If this isn't taken up by anyone.
You can work on only 1 issue at a time. @chandu6111

**Comment by pratimakush10** [comment]
Can I work on this issue under LGMSOC'21

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Issue assigned. @pratimakush10
