### ISSUE TITLE
Current Time Stamps Using Pendulum Library

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#345]
---
Title: Current Time Stamps Using Pendulum Library
About: Implementation of Current Time Stamps Using Pendulum Library
Name: Amit Gupta
Label: Feature Request
Assignee: ''
---
Define You:

- [x] LGM-SOC'21 Participant
 Contributor

I'll write a Python script to create a current timestamp using the **pendulum** library. As a result, it will give the current date and time of your current zone and the data you will enter. It will also work on **Speak Automation**.

**Comment by Debashish-hub** [comment]
Please complete the previous issues assigned to you first  to get another issue @AmitGupta700

**Comment by AmitGupta700** [comment]
> Please complete the previous issues assigned to you first to get another issue @AmitGupta700

Sir I have completed and it is merged.

**Comment by Debashish-hub** [comment]
#200 #130

**Comment by AmitGupta700** [comment]
> #200 #130

Sir I have seen both it is completed

**Comment by Debashish-hub** [comment]
> > #200 #130
> 
> Sir I have seen both it is completed

Sorry for the inconvenience, You can now work on this issue. It is assigned to you @AmitGupta700 
Great work till now and a lot more to get from you
