### ISSUE TITLE
Unscramble the Word game in Python

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#347]
---
Title: Unscramble the Word game 
About: It's a script under PyGames Script.
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this games we will be given some unscrambled word and we need to correct it, and finally see the result.

Following is the screenshot how it looks like,
![1](https://user-images.githubusercontent.com/57003737/122628783-dda32480-d0d5-11eb-92ff-bf3c77aa4824.jpg)

In this will be adding some new frame for showing the result and all.

**Comment by akash435** [comment]
@prathimacode-hub , please assign me this under LGM SOC, can add this under PyGames Scripts.

**Comment by Debashish-hub** [comment]
A similar script is already there  #175
You can choose some other issue @akash435

**Comment by akash435** [comment]
ok
