### ISSUE TITLE
Caterpillar Game GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#348]
Title: Caterpillar Game GUI
About : Here we will have a game using turtle in which there will be caterpillar and it needs to grass to survive so as it eats grass, its speed increases and as soon as it leaves the frame the game ends.
Name : Neel Shah
Label : Feature request

Define you:

- [x]  LMG SOC'21 Participant
 - [ ] Contributor

Description:
Here using the turtle and random library we make a game in which the caterpillar moves slowly firstly but as soon as it starts eating leaf the speed goes increasing and if it goes outside the frame then game ends.

**Comment by Debashish-hub** [comment]
Sound interesting. This issue is assigned to you @neelshah2409
