### ISSUE TITLE
Reddit Bot

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/Awesome_Python_Scripts#349]
Title : Reddit Bot
About : Reddit is a handy platform, and many people want to be online as much as they can. I can program a bot that monitors subreddits and reports whenever they find something useful. It will save Redditors a lot of time and provide helpful information with it.
Name : Abhishek Sharma
Label : Feature Request

Define you:
- [x] LGMSOC Participant

Description : 
This reddit bot will pick a subreddit to scan, designate  a specific comment to search for and finally reply according to the script written in Python.

**Comment by prathimacode-hub** [comment]
Interesting, this issue is assigned to you. You can proceed. @abhisheks008
