### ISSUE TITLE
Color Game with tkinter

### ISSUE THREAD

**Issue by MuditCh57** [prathimacode-hub/Awesome_Python_Scripts#35]

**Comment by prathimacode-hub** [comment]
Have you used GitHub earlier? Do you know how to contribute your project and create a pull request? @MuditCh57

**Comment by MuditCh57** [comment]
Yes I used GitHub just to add my own projects. But I don't know how to create a pull request.

**Comment by prathimacode-hub** [comment]
**Process to follow** 👍

Fork the repository. You are now in your profile repositories
You can see a "Add File" option in the local repository
You can add files or folders using the 2options given
Create new file option helps in creating both file and sub repository within this repository.
Example : You want to add up your a script of a game using tkinter to this repository
Go to "PyGamesScripts" repository. Select "create a new file" option,
It opens up like this - /Awesome_Python_Scripts/PyGamesScripts
To add up your repository and file you do :
/Awesome_Python_Scripts/PyGamesScripts/Your Project Name/README.md
This add up would not only add 'Your Project Name' as repository but also adds an empty README.md file.
You can add your README content in README.md file and commit the changes
Now you have created a repository of your desired script, you are yet to add your python program
From the very same "Add File" option, select "Upload files" and add your python program from your local drive of your system.
Make sure the script file name is file_name.py before you upload the file to this repository.
You have successfully added up your required files needed.
Now select "Contribute" option above and select Open Pull request, and add a defined title o the project, a commit message of what project does in a description.
Finally, create a pull request option to synchronize your fork to the committed repository. You are done.
Congrats, on learning how to create a PR in a easier way. No much fuss around to deal with.
PR can be created without the use of command line terminal, but preferrably that way to show professionalism.
Contribution is all that matters, so start contributing and feel free to do more PR in future.
Make sure you follow the contributing guidelines before you start with the process. Keep going.
If you found this helpful and easier to try, you can do create the PR of the script you are about to contribute.

Looking forward to merge the upcoming PR from you. Thank You. @MuditCh57

**Comment by MuditCh57** [comment]
Thank You very much for helping me through out the process @prathimacode-hub.
I will surely contribute more to this repository. 
Thank You @prathimacode-hub 👍

**Comment by MuditCh57** [comment]
But I have some doubts. Why you told me to open an issue? How my repository will sync with this main repository?

**Comment by prathimacode-hub** [comment]
> But I have some doubts. Why you told me to open an issue? How my repository will sync with this main repository?

The reason I said so, is earlier issue was a generalized one to get knowledge of how contributions can be done. But when you open up a new issue and specifying the code you are going to contribute, you can link your issue number to your pull request to show a reference that PR is raised in concerning with the issue you have created. And also by doing this, it will automatically sync your name in contributors. Hope you got my point. @MuditCh57

**Comment by prathimacode-hub** [comment]
That's great to know. You're most welcome to contribute.  Did i say this, you're a quick learner. Keep rocking. 👏@MuditCh57

**Comment by MuditCh57** [comment]
> That's great to know. You're most welcome to contribute. Did i say this, you're a quick learner. Keep rocking. 👏@MuditCh57

Thank You!
