### ISSUE TITLE
Mobile Recharge Plan Detailer

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#354]
Title: Mobile Recharge Plan Detailer
About : we can get all the recharge plans by fetching it from website using requests and bs4 libraries
Name : Neel Shah
Label : Feature request

Define you:

- [x] LMG SOC'21 Participant
- [ ] Contributor

Description: We ca get all the plans of all service providers (i.e. jio , airtel , etc.) by running a script having requests and bs4 libraries   and it will be easier to find the best plan through script.

**Comment by prathimacode-hub** [comment]
You have changes to be addressed in your last PR, once you do that, this issue would be assigned to you. @neelshah2409

**Comment by neelshah2409** [comment]
Mam please see this and assign me.

**Comment by neelshah2409** [comment]
@Debashish-hub @prathimacode-hub Please assign this issue.

**Comment by prathimacode-hub** [comment]
Cool, this issue is assigned. You can proceed. @neelshah2409
