### ISSUE TITLE
Add Splash Screen and Logo to Calculator App

### ISSUE THREAD

**Issue by Khushi-sharma07** [prathimacode-hub/Awesome_Python_Scripts#357]
Title: Add Splash Screen and Logo to Calculator App In GUI Scripts
Name: Khushi Sharma
Label: Feature Request 
Assignee: ''  ---  
Define You:  - 

- [x]  LGM-SOC'21 Participant  
- [ ] - Contributor   

Have you talked to any of the Moderators or Project Admin (Prathima Kadari) before creating this issue? Yes 

Description: 
In the Calculator App that is in GUI Script the logo is missing and also there is no splash screen.

The changes I will make:
1. Add the splash screen gif at the beginning of the application which will give some effects to the application. 
2. Add the logo to the title bar. 
3. I will also resize the window for better designing and also the buttons inside it are resized and spacing is given between the buttons.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. All the best. @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Thank you mam
