### ISSUE TITLE
Missing Alphabet Game in Python

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#358]
---
Title: Missing alphabet game in python
About: It's a PyGames script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Want to add this game under PyGames script.

In this the user will be given one by one upto 20 words with missing alphabet, and user input to enter the correct missing alphabet,
And at any time user can look into how many correct , wrong and skipped and he has.

Also at the end of game , the final score is made visible in frame.

**Comment by prathimacode-hub** [comment]
Interesting, this project is assigned to you. You can proceed. @akash435

**Comment by akash435** [comment]
Thanks mam
