### ISSUE TITLE
ALL IN ONE CONVERTER

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#359]
> Title: -All type of Converter                      
> About:- The program will be used to convert Currency , Lenght, area,weight	  
>Name :-	   Ashutosh Kumar Saw	
>Label:- Feature Request
> ## Assignee:
> Define You:
> 
> * [x]  LGMSOC Participant
> * [x]  Contributor
> 
> LGM-SOC'21
> 
> Solution For Issue:
> Python

**Comment by prathimacode-hub** [comment]
Kindly first finish off the changes I had asked for in your earlier PR. And as well don't hurry. Go one by one. This template is not right.
