### ISSUE TITLE
WhatsApp Message Automation using python

### ISSUE THREAD

**Issue by chandu6111** [prathimacode-hub/Awesome_Python_Scripts#363]
**Title**: WhatsApp Message Automation using Python
**Name**: Chandana (chandu6111)
**Label**: Feature Request

**Description of the Script**:
It's a script to send a message to a person on WhatsApp, the program takes 3 inputs:
- phone number of the person to whom the message is to be sent
- The text the user wants to send
- Time at which message has to be sent
- And it sends the message at that time by opening WhatsApp web automatically.
No need to log in again, it will automate the whole process.

- [x]  **LGM-SOC'21- participant**

**Comment by chandu6111** [comment]
@prathimacode-hub please assign me this issue under LGM-SOC'21

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed working. @chandu6111

**Comment by chandu6111** [comment]
Where should I add the code @prathimacode-hub
Should I add under Automation Scripts?

**Comment by prathimacode-hub** [comment]
> Where should I add the code @prathimacode-hub
> Should I add under Automation Scripts?

Yes, right under Automation.
