### ISSUE TITLE
Web Browser Creation using Python

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/Awesome_Python_Scripts#364]
Project Name : Creating a Web Browser using Python script

Description : Python programming language is used here to create a web browser, which will work as a common web browser those we are using in our daily life like, google chrome, mozilla firefox, microsoft edge etc.

Libraries used : Tkinter, re and many more basic libraries.

- [x]  LGMSOC Participant

Task Taken : Creating the Web Browser with a proper GUI.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can go ahead. @abhisheks008
