### ISSUE TITLE
Sentiment Classifier in Python

### ISSUE THREAD

**Issue by ishitakapoor26** [prathimacode-hub/Awesome_Python_Scripts#369]
Project Name:
Sentiment Classifier

Description:
A Sentiment Classifier is a program which will detect how positive or negative each tweet is. Also I will add a csv file, which contains columns for the Number of Retweets, Number of Replies, Positive Score (which is how many happy words are in the tweet), Negative Score (which is how many angry words are in the tweet), and the Net Score for each tweet. At the end, I will upload the csv file to Excel or Google Sheets, and produce a graph of the Net Score vs Number of Retweets.

[x]-LGM-SOC-21

Task Taken: Sentiment Classifier in Python

**Comment by ishitakapoor26** [comment]
@prathimacode-hub pls assign this issue to me.

**Comment by Debashish-hub** [comment]
Please follow the issue template to get an issue assigned to you and prior to that complete the previous issue assigned to you @ishitakapoor26

**Comment by ishitakapoor26** [comment]
> Please follow the issue template to get an issue assigned to you and prior to that complete the previous issue assigned to you @ishitakapoor26

I've completed the previous issue but my pr is not merged yet.

**Comment by Debashish-hub** [comment]
> > Please follow the issue template to get an issue assigned to you and prior to that complete the previous issue assigned to you @ishitakapoor26
> 
> I've completed the previous issue but my pr is not merged yet.

You have been asked for changes there @ishitakapoor26

**Comment by prathimacode-hub** [comment]
Yes, kindly do those changes for earlier PR. I don't think this is a sole python script. It comes under NLP. @ishitakapoor26

**Comment by prathimacode-hub** [comment]
Why had you closed it? You should not close it from your end? @ishitakapoor26
