### ISSUE TITLE
Learning opensource

### ISSUE THREAD

**Issue by archismansaha** [prathimacode-hub/Awesome_Python_Scripts#37]
As a complete beginnner I want to learn by doing and start by opensourcejourney and start contributing in opensource with python .I had not much knowledge about python and its libraries .So this issue is created for taking help and how to start and for resources and need guidance towards open source. There are many projects or ideas but dont know how to build them by own so need help and want to build something by own.(like image processing or something like discord bot etc. )

**Comment by prathimacode-hub** [comment]
That's great. It's a good way to learn while doing. I shall provide you with the resources needed to learn python programming. It's very first thing you need to initiate your contribution before you get into github and opensource. I shall educate you about github and open source. Do look here to learn [python](https://github.com/prathimacode-hub/Learn-Python-For-Beginners). To get all the resources at single space, kindly share your Email Id. That would help me to share my notes regarding the same. Once you get fair grip on it, i can guide you further. @archismansaha

**Comment by archismansaha** [comment]
Thx mam and this is my email id: archimansaha@gmail.com

**Comment by prathimacode-hub** [comment]
I had shared tutorials, book and a course suggestion to your mail id. I as well deleted your mail id here for privacy reasons. Do check it out. @archismansaha

**Comment by archismansaha** [comment]
ya I had recieved thx mam

**Comment by prathimacode-hub** [comment]
How is the progress going? @archismansaha

**Comment by archismansaha** [comment]
Mam It's going good learned a lot new things 😊

**Comment by prathimacode-hub** [comment]
That's great. Good to know. Once you get basics on it. I shall guide you on opensource and github. To get some idea on how projects look like. You can refer this [repo](https://github.com/prathimacode-hub/Pythonista_ForAll). Didn't update it fully. But yeah, it would help you in structuring your programs by own and initiating projects on python. 🙌👏@archismansaha

**Comment by archismansaha** [comment]
Ohk thx a lot mam 😊

**Comment by prathimacode-hub** [comment]
Shall I close this issue, if you had learnt open source. @archismansaha

**Comment by archismansaha** [comment]
@prathimacode-hub yes mam.. thx for guiding me 😊 if I would have any problem I will reach you

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub yes mam.. thx for guiding me 😊 if I would have any problem I will reach you

Sure, you're always welcome to reach me out. @archismansaha
