### ISSUE TITLE
Scientific calculator

### ISSUE THREAD

**Issue by prakhar07msd** [prathimacode-hub/Awesome_Python_Scripts#371]
Title: Scientific calculator 
About: It's a scientific calculator using tkinker GUI
Name: Prakhar Agarwal
Label: feature request
Assignee: ''

Define You:

 LGM-SOC'21 Participant

In this project, scientific calculator is used for scientific calculations and this one is made using tkinker GUI in python

**Comment by prathimacode-hub** [comment]
Sure, this is issue is assigned to you and can go ahead. @prakhar07msd

**Comment by prathimacode-hub** [comment]
No update from you yet. @prakhar07msd

**Comment by prakhar07msd** [comment]
> No update from you yet. @prakhar07msd

Please check my PR
