### ISSUE TITLE
Crack Any Password

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#372]
---
Title: Crack Any Password Using python
About: Implementation of Crack Any Password Using Python with a brute force attack.
Name: Amit Gupta
Label: Feature Request
Assignee: ''
---
Define You:

- [x] LGM-SOC'21 Participant
 Contributor

I'll write a Python script to create a program that will crack any password using python with a brute force attack. So, the process is something like that we will ask the user to enter some characters i.e. password, and then we will try to guess the password using a brute force attack.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can start working. @AmitGupta700
