### ISSUE TITLE
preview your link

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#373]
---
Title: Preview your link
About: Once, the person will enter the link where in the person want to preview, the computer will provide with title, description, and link of the website that the URL points to.
Every entry will have a time limit after which it will be updated (Data expires after 7 days)
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
I will be using python mam.

please assign me this issue @prathimacode-hub @Debashish-hub , I would like to work on this issue.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. @manognyaa
