### ISSUE TITLE
A Notepad app in python

### ISSUE THREAD

**Issue by girija0707** [prathimacode-hub/Awesome_Python_Scripts#378]
Title:- Notepad app in python
About:- This app will help people write creative ideas and edit text
Name:- Girija Gupte
label:- Features request

Define you
LGMSOC'21 PARTICIPANT 
Define your solution:- I would like to add python script for this app

**Comment by prathimacode-hub** [comment]
Sorry to say, but this issue is already taken and got merged. Kindly take up an another issue to work on. @girija0707
