### ISSUE TITLE
Send Push Notification To Your Phone

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#379]
---
Title: Send Push Notification To Your Phone
About: Implementation of Push Notifier system using numerous libraries of Python.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I'll write a Python script that will send Push Notification to your phone using the Pushbullet module in Python.

**Comment by prathimacode-hub** [comment]
Can you elaborate the issue? @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Ya, ma'am sure, 
Essentially, this project will deliver notifications to all devices from a single system. We must first download the Pushbullet app on our phone or PC, then share the access token, and last, I will use that token to send you the notification on your device.

**Comment by prathimacode-hub** [comment]
Ok, that's great. There was a similar script of sending notifications to mail, reason I asked for. But this is different, I had assigned this issue to you. @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Ok ma'am

**Comment by prathimacode-hub** [comment]
No update from you. Is everything fine? @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Ya ma'am, I am working on it. It will be updated soon, and I'll try to push it today.

**Comment by prathimacode-hub** [comment]
> Ya ma'am, I am working on it. It will be updated soon, and I'll try to push it today.

That's great @Iamtripathisatyam
