### ISSUE TITLE
Secure Password Maker

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#380]
---
Title:  Secure Password Generator
About: This is a application which will make our password more secure in such a way that it can also be remembered by us easily, this application will be built using basic python scripts
Name: Jayapritha N
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Sorry to say, but this issue is already taken and merged. You can come up with an another issue to work on. @coding-geek21

**Comment by coding-geek21** [comment]
> Sorry to say, but this issue is already taken and merged. You can come up with an another issue to work on. @coding-geek21

No problem @prathimacode-hub I will look for another issue. But this application will not generate password for us , instead if we give a password it will just make secure by adding uppercases and special characters ,

**Comment by prathimacode-hub** [comment]
That's interesting but sounds similar right. You can do something. Later, you can add it as an enhancement to the existing project. @coding-geek21

**Comment by coding-geek21** [comment]
> That's interesting but sounds similar right. You can do something. Later, you can add it as an enhancement to the existing project. @coding-geek21

Sure

**Comment by coding-geek21** [comment]
@prathimacode-hub Can i work on documentation?  I found that the contributors list is not updating automatically , and it's tedious task to add the contributors in readme file. Can i change that?

**Comment by prathimacode-hub** [comment]
Ok, sure. You can work on documentation issues as well, but raise a separate issue stating the same. @coding-geek21

**Comment by coding-geek21** [comment]
> Ok, sure. You can work on documentation issues as well, but raise a separate issue stating the same. @coding-geek21

Okay should i follow same template used for feature request?

**Comment by prathimacode-hub** [comment]
> > Ok, sure. You can work on documentation issues as well, but raise a separate issue stating the same. @coding-geek21
> 
> Okay should i follow same template used for feature request?

Yes
