### ISSUE TITLE
[Documentation]  Automatically update the contributors list in Readme

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#381]
---
Title:  Automatically update the contributors list in Readme
About: Automatically update contributors using builtin code
Name: Jayapritha N
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Go ahead. @coding-geek21
