### ISSUE TITLE
Text to Speech Converter

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/Awesome_Python_Scripts#383]
Title:- Text to Speech Converter
About:- The text to speech converter tool is used to create a spoken sound version of the text.
Label:- Features request

Define you:-
LGMSOC'21 PARTICIPANT
Define your solution:- I would like to add python script for this app.

**Comment by prathimacode-hub** [comment]
This issue is already taken and merged. Kindly take up an another issue to work on. @Jagannath8
