### ISSUE TITLE
Creating Address Book 

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#384]
Title: Creating Address Book Using Tkinter
About: Implementation of this script is done by using the Tkinter module and took the help of some of its functions.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

-[x] LGM-SOC'21 Participant
-[x] Contributor
I'll write a Python script that will create an address book like interface, this is done only by the use of Tkinter and its functions.

**Comment by prathimacode-hub** [comment]
Yup, interesting. This issue is assigned to you. You can go ahead. @Aditya8821
