### ISSUE TITLE
Time Zone Converter

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#386]
---
Title: Time Zone Converter
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this GUIScript, we will be able to convert from one time zone to another time zone.
like IST to PST, GMT to IST, UTC TO GMT, and there are many more.
there are almost 28 Time zone, and this application will allows us to convert from any one time zone to another.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this under LGM SOC, can add this script under GUIScripts section.

**Comment by Debashish-hub** [comment]
Seems interesting, This issue is assigned to you @akash435 . Keep it up

**Comment by akash435** [comment]
Thanks
