### ISSUE TITLE
Text Translator

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#390]
Title: Text Translator
About: GUI script
Name: Pooja Deshpande
Label: feature request
Assignee: ''

Define You:

 LGM-SOC'21 Participant

In this project, a gui will have text input which can be converted to another language of user's choice.

**Comment by prathimacode-hub** [comment]
This issue is already taken up and merged. Kindly take up an another issue to work on. @cybot-des
