### ISSUE TITLE
Spelling Corrector in GUIScripts

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#391]
---
Title: Spelling Corrector
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this GUIScript, In this script, the user can enter any word, either correct or misspelled
And on clicking on the correct button can get the correct spelled word for that entered word.

**Comment by akash435** [comment]
@prathimacode-hub , please assign me this under LGM SOC, can add this under GUI Scripts.

**Comment by prathimacode-hub** [comment]
Go ahead, this issue is assigned to you. You can get going. @akash435
