### ISSUE TITLE
News Application Gui

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#392]
Title: News Application GUI
About: GUI script
Name: Pooja Deshpande
Label: feature request
Assignee: ''

Define You:
 LGM-SOC'21 Participant

In this project you can enter the topic for which you want to fetch news items and number of topics to be fetched(max 100).
Will be done using tkinter and news api

**Comment by prathimacode-hub** [comment]
Sorry, this issue is already done. Do check up with the repo and issues assigned to see if it's available so that you can think of  script you could work on. @cybot-des
