### ISSUE TITLE
Email Sender In Bulk

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#393]
Title: Email Sender In Bulk
About: Implementation of this script is done by using the csv ,email ,smtplib libraries.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description: Here we will fetch all the information from excel/csv file and then connect it to sever and send the same message to multiple person at a same time.

**Comment by prathimacode-hub** [comment]
You can go ahead. This issue is assigned to you. @neelshah2409
