### ISSUE TITLE
Countdown Timer for an Event

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#395]
---
Title:  Countdown Timer
About: This application will countdown the days and time left for an event , This will be built using GUI Tkinter
Name: Jayapritha N
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by Debashish-hub** [comment]
Go ahead @coding-geek21 Issue is assigned to you
