### ISSUE TITLE
Rolling dice game in python

### ISSUE THREAD

**Issue by bindaldhara** [prathimacode-hub/Awesome_Python_Scripts#396]
In this game it gets the value of dice i.e. btw 1 and 6 and tells user if the number is divisible by 2 or not

**Comment by Debashish-hub** [comment]
Please follow the issue template @bindaldhara

**Comment by bindaldhara** [comment]
Title: Rolling dice game  Using python
About: In this game it asks the user to enter a value btw 1 and 6 and tells user if the number entered is divisible by 2 or not 
Name: Dhara Bindal
Label: Feature Request
Assignee: ''
Define You:

 LGM-SOC'21 Participant
Contributor

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. @bindaldhara
