### ISSUE TITLE
Open WebCam

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#397]
---
Title: Open WebCam Using python
About: Implementation of WebCam using python
Name: Amit Gupta
Label: Feature Request
Assignee: ''
---
Define You:

- [x] LGM-SOC'21 Participant
 Contributor

I'll write a Python script to create a program that will open your WebCam. I will use the cv2 module.

**Comment by prathimacode-hub** [comment]
Yup, this issue is assigned to you. @AmitGupta700
