### ISSUE TITLE
Age Predictor Chatbot

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#398]
Title: Age Predictor Chatbot
About: Implementation of chatbot and calculating age and several other functions from bot.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Here I will create a chatbot which can predict your age and it also performs some other functions like printing the series upto some numbers which user gives and asking them questions.

**Comment by prathimacode-hub** [comment]
Interesting, this issue is assigned to you. @neelshah2409
