### ISSUE TITLE
snake game

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#40]
hello sir,
i would like to add snake game using python . please assign this to me @Kushal997-das @kevinkurian7 @pankaj892

**Comment by Kushal997-das** [comment]
@manognyaa Yes you can add your project here ,if you need any kind of help you can contact me over [`linkedin`](https://www.linkedin.com/in/kushal-das-7337421a9/l)

**Comment by prathimacode-hub** [comment]
Yeah, you can add your project here. Assigned. 👍 @manognyaa

**Comment by manognyaa** [comment]
Thank You very much mam @prathimacode-hub

**Comment by manognyaa** [comment]
> @manognyaa Yes you can add your project here ,if you need any kind of help you can contact me over [`linkedin`](https://www.linkedin.com/in/kushal-das-7337421a9/l)

okay sorry for the inconvenience caused ;(

**Comment by muskantayal123** [comment]
@prathimacode-hub mam,   i want to  do this project, please assign me this

**Comment by prathimacode-hub** [comment]
Raise a new issue the template mentioned in README. You can check the template through the assigned issues to know how template should like. Brief the project, so that I can assign the issue to you. @muskantayal123

**Comment by prathimacode-hub** [comment]
Only 1 issue is assigned at a time. if you want to work on this, create a new issue. @muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub  okay mam .

**Comment by muskantayal123** [comment]
@prathimacode-hub  mam where i can find the template?

**Comment by prathimacode-hub** [comment]
The template is in the README file of the project. Follow the feature_request template. If you find it tough, you can check with assigned issues. they had followed the template. @muskantayal123
