### ISSUE TITLE
Eyes & Smile detection

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#400]
Title: Eyes and Smile detection
About: Implementation of haar cascade to perform real time eyes and smile detection 
Name: Pooja Deshpande
Label: Feature Request
Assignee: ''

Define You:
 ✅LGM-SOC'21 Participant
       Contributor

In this project I will use opencv and haar cascades to perform real time eyes and smile detection through your web cam.

**Comment by prathimacode-hub** [comment]
That's already performed in Face Mask Detection and Emotion Detection. You can take up an another issue to work on. @cybot-des

**Comment by cybot-des** [comment]
Ok
