### ISSUE TITLE
Wikipedia GUI

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#402]
Title: Wikipedia GUI
About: GUI script project
Name: Pooja Deshpande
Label: Feature Request
Assignee: ''

Define You:

 ✅LGM-SOC'21 Participant
       Contributor
In this project I will make use of wikipedia api to fetch results related to users query term like summary description and information. I will make a gui for it.

**Comment by prathimacode-hub** [comment]
That's great. This issue is assigned to you. You can proceed. @cybot-des

**Comment by cybot-des** [comment]
Maam, I just want to make a correction that I will include it under GUI script as Wikipedia api is a python module...

**Comment by prathimacode-hub** [comment]
Ok,  if that's the case title should be changed as well to 'Wikipedia GUI' @cybot-des

**Comment by cybot-des** [comment]
Okay I will change it
