### ISSUE TITLE
Quiz game in python

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#406]
---
Title: Quiz Game
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this game , there will be some specific no of question will be given to user, and user need to enter correct ans. 
there also at the end score will be shown.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me , can add this under GUI Scripts

**Comment by prathimacode-hub** [comment]
That sounds fun. Yes, this issue is assigned to you. You can start working. @akash435

**Comment by akash435** [comment]
Thanks
