### ISSUE TITLE
want to add colour detection application

### ISSUE THREAD

**Issue by anandalisha** [prathimacode-hub/Awesome_Python_Scripts#407]
I want to add an application using which we can automatically automatically get the name of colour.

**Comment by prathimacode-hub** [comment]
Kindly follow the template. What kind of issue it is? Can you elaborate the project? @anandalisha

**Comment by anandalisha** [comment]
@prathimacode-hub 
In this color detection Python project, I will implement an application through which we can automatically get the name of the color by clicking on them. 
For it's implementation I will use a data file that contains the color name and its values and then calculate the distance from each color and find the shortest one.

**Comment by anandalisha** [comment]
@prathimacode-hub If you find it okay then please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
That sounds cool, this issue is assigned to you. @anandalisha

**Comment by prathimacode-hub** [comment]
By the way, there is no issue template in your issue. Do check and follow the template given whenever you create an issue. @anandalisha

**Comment by prathimacode-hub** [comment]
Why had you closed it? @anandalisha
