### ISSUE TITLE
Part Of Speech Calculator

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#408]
---
Title: Part Of Speech Counter
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this the user will be allowed to enter any sentence or paragraph, and the application will count the different parts of speech present in it.
for eg. , noun, verb, adverb, adjective, etc.

**Comment by akash435** [comment]
@prathimacode-hub , if this is OK, then please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Interesting, Issue is assigned to you @akash435
