### ISSUE TITLE
Library Management GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#409]
Title: Library Management GUI
About: Implementation of proper management of library using kivy
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x]  LGM-SOC'21 Participant
- [ ] Contributor

Every librarian finds difficulty for maintaining the logs and some may use software but that is not affordable by everyone so why not our script do that.
Here we will be making our script using kivy and taking input for student's name ,book title ,issue and return date ,fine/penalty and at last we will found all the logs as the output.

**Comment by Debashish-hub** [comment]
Go ahead @neelshah2409 , Issue is assigned to you
