### ISSUE TITLE
Adding turtle racing game

### ISSUE THREAD

**Issue by archismansaha** [prathimacode-hub/Awesome_Python_Scripts#410]
---
Title: Turtle Race
About: Suggest an idea for this project
Name: Archisman Saha
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

This game is simple game made with python where you have to make bate on a turtle you want to and you will see if the turtle wins among the all or not.

**Comment by Debashish-hub** [comment]
Great, Issue is assigned to you @archismansaha
