### ISSUE TITLE
Image Stitching Using Opencv

### ISSUE THREAD

**Issue by sherin527** [prathimacode-hub/Awesome_Python_Scripts#414]
`---
Title: Image Stitching
About: I want to implement Image stitching one of the Image processing techniques wherein the input images will be stitched together and will give an output as a single image.
Name: Sherin Shibu
Label: Image Processing Script.
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
I want to implement the Image stitching technique in which there will be two images that will be given as input and the output will be the one single image after the image stitching operation. I will be using OpenCV to implement this.

@prathimacode-hub ma'am, please assign me this issue.
`

**Comment by Debashish-hub** [comment]
Is it similar to collage maker as in #128  @sherin527

**Comment by sherin527** [comment]
@Debashish-hub,It basically implements a feature-based automatic image stitching algorithm wherein we input two images with overlapped fields, we expect to obtain a wide seamless panorama. This includes steps such as:
1.Feature extraction using SIFT descriptor of opencv
2.Matching correspondences between images 
3.Compute Homography
4.Warping & Stitching

**Comment by prathimacode-hub** [comment]
Ok, it merges perfectly and doesn't look like collage using the techniques you had enforced right? @sherin527

**Comment by sherin527** [comment]
yes @prathimacode-hub ma'am

**Comment by prathimacode-hub** [comment]
Ok, this issue is assigned to you. @sherin527

**Comment by sherin527** [comment]
Thank you ma'am
