### ISSUE TITLE
Invisible Clock using Python

### ISSUE THREAD

**Issue by rishabhrathore055** [prathimacode-hub/Awesome_Python_Scripts#417]
---
Title: Invisible Clock using Python
About: want to add  Invisible Clock using Python programming language
Name: Rishabh Rathore
Label: Feature Request
Assignee: ''

---
Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by rishabhrathore055** [comment]
@prathimacode-hub pls assign me this issues

**Comment by Debashish-hub** [comment]
Can you please elaborate @rishabhrathore055

**Comment by prathimacode-hub** [comment]
Elaborate the issue of how would you expect this to work? It would come under which script? @rishabhrathore055

**Comment by prathimacode-hub** [comment]
Kindly repond, if u r willing to work on this issue. @rishabhrathore055

**Comment by Cartikx3** [comment]
I am a LMG SOC participant , can you asssign this issue to me .

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. Issus is assigned. @Cartikx3
