### ISSUE TITLE
Egg catcher game using GUI

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#419]
---
Title: Egg catcher game using GUI
About: This is an egg catcher game using tkinter, here eggs will be falling down and we have to catch it using bowl(keyboard controls) lives and scores will be there.
Name: Jayapritha N
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Whoa, sounds interesting. You can proceed. @coding-geek21
