### ISSUE TITLE
calculator app

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#42]
hello sir,
I want to create a calculator app using python.
I would like to contribute to this project please assign this to me.

**Comment by prathimacode-hub** [comment]
By the way I'm not a sir. Assigned this issue to you. Sure, are you part of any open source program? @manognyaa

**Comment by manognyaa** [comment]
> By the way I'm not a sir. Is this calculator program a basic functionality or an app / GUI? Sure, are you part of any open source program? @manognyaa

hello mam, 
sorry for the inconvenience caused. this is a basic functionality mam with a color combination of black, sky blue and Persian blue mam. Adding to it, the numbers will be visible in white color.

**Comment by prathimacode-hub** [comment]
That's cool. So it's a basic GUI calculator script. @manognyaa

**Comment by manognyaa** [comment]
> That's cool. So it's a basic GUI calculator script. @manognyaa

yes mam @prathimacode-hub :)

**Comment by prathimacode-hub** [comment]
I had assigned it to you. Try to complete all the issues that are assigned before 10th June, 2021. Though you're free to contribute, but from 10th, this repo would be a part of an open source program. @manognyaa

**Comment by prakhar07msd** [comment]
can you assign me this??

**Comment by prathimacode-hub** [comment]
This issue is created 4 days ago. So it won't be considered. Do raise a new issue with the template given. You can check out with the reference template to follow through the assigned issues @manognyaa
