### ISSUE TITLE
BMI Calculator Using Python GUI

### ISSUE THREAD

**Issue by Khushi-sharma07** [prathimacode-hub/Awesome_Python_Scripts#420]
Title: BMI Calculator GUI
About: Add a script to create BMI Calculator using Python

Name: Khushi Sharma
Label: Feature Request
Assignee: "

Define You:

- [x]  LGM-SOC'21 Participant
- [ ]  Contributor

Solution:
It will be a GUI Python Script which will help a person to calculate his/her BMI ratio by entering the weight(in kgs) and height. It will tell whether the person is healthy or underweight or overweight.

**Comment by Khushi-sharma07** [comment]
Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. You can start working. @Khushi-sharma07
