### ISSUE TITLE
Gold Price Fetcher

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#421]
Title: Gold Price Fetcher
About: Implementation of web scrapping from the url using requests and bs4 library and fetching the price
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Every middle class person wants to buy gold but at the cheapest cost so our script will find the best price for them and our script will also show difference between the current and yesterday's price. Here we simply fetch the price from website.

**Comment by prathimacode-hub** [comment]
Unique script. This issue is allotted to you. You can get going. @neelshah2409
