### ISSUE TITLE
Sorting hat game

### ISSUE THREAD

**Issue by kamakshi829** [prathimacode-hub/Awesome_Python_Scripts#426]
Title: Sorting hat game
About: This is a game in which school assigns a hat to new students as in Harry Potter movie. 
Name: Kamakshi Singh
Label: Feature Request
Assignee: ''

Define You:

 LGM-SOC'21 Participant - Yes
 Contributor

It is a game as in schools there are some houses and students are assigned to one of those houses. Here those houses are called as hats and I will use tkinter to solve this. 
Please assign this issue to me.

**Comment by Debashish-hub** [comment]
Please elaborate @kamakshi829

**Comment by kamakshi829** [comment]
Ok @Debashish-hub  sir
 The Sorting Hat is an artefact used at Hogwarts in the Harry Potter books. The hat determines which of the four school houses (Gryffindoe, Slytherin, Hufflepuff and Ravenclaw) each new student is assigned to. The hat resembles a wide-brimmed wizard's hat, with folds and tears that make it appear to have eyes and a mouth. During the opening banquet at the beginning of each school year, the Hat is placed on every first-year student's head. The Hat announces its choice aloud, and the student joins the selected house.

**Comment by prathimacode-hub** [comment]
Sounds innovative script. This issue is assigned to you. You can proceed. @kamakshi829

**Comment by kamakshi829** [comment]
Thanku @prathimacode-hub  ma'am
