### ISSUE TITLE
Implement Search in GUI Script

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#430]
---
Title: Search bar in Python
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this , a search bar will be created.
And user will be allowed to any text, or paragraph or sentence.
and user will be able to search any word in it.

This application also searches word, count how many times it has come, and also the position,

**Comment by akash435** [comment]
@prathimacode-hub , if this is OK, please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Please elaborate it @akash435 
You need to complete the previous assigned issue to get another issue

**Comment by akash435** [comment]
In this user will be given a text area and in that text area user can enter any text or any paragraph.
and there will be a search button
using that search button user can search any word or text in that paragraph entered in the text area.

Also this lets us know where that word is located in the paragrah and how many times it present.

**Comment by prathimacode-hub** [comment]
OK, this issue is assigned to you. @akash435
