### ISSUE TITLE
Get location of any Country

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#432]
---
Title: Get location of any Country
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this, user will be able to get the location of any country on earth.
User just need to enter the country code or country name and can get the location of country in terms of longitude and latitude.

**Comment by akash435** [comment]
@prathimacode-hub , if this can be done then please assign this issue to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Great! Issue is assigned to you @akash435 Keep up the good work
