### ISSUE TITLE
I want to contribute socket programs

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#433]
## Related Issue 

- I want to contribute some socket programming codes, written using python

- [X] LGM-SOC'21 Participant 
- [X] Contributor

**Comment by prathimacode-hub** [comment]
Follow the proper issue template, write a project title to your issue, explain your approach. @kumarjeetray

**Comment by kumarjeetray** [comment]
---
Title: Word Transfer
About: Transfer of word from one computer to another through ports 
Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

---

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor




**Is your feature request related to a problem? Please describe.**



**Describe the solution you'd like...**



**Describe alternatives you've considered?**



**Approach to be followed (optional):**
I will take the IP address of the server and take a random port number above 1023 and bind the two. The IP of the server and the same port will be used by the client to connect to the laptop and then the transfer of word will begin from client to server. As the server will get the word it will check it against a list of words and return the result as to whether the word is present in the list or not


**Additional context**

**Comment by kumarjeetray** [comment]
Is this okay ?

**Comment by prathimacode-hub** [comment]
You're not getting my point. Raise separate issue for the program you are going to contribute. Not like this. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> You're not getting my point. Raise separate issue for the program you are going to contribute. Not like this. Template is right. But raise a issue which purely states only this project. @kumarjeetray

Can you please show me. I am surely not understanding this. I tried creating a different issue. I want to add a new project and not correct or add feature to an existing one. If possible can you please show me one. Please !!

**Comment by prathimacode-hub** [comment]
> > You're not getting my point. Raise separate issue for the program you are going to contribute. Not like this. Template is right. But raise a issue which purely states only this project. @kumarjeetray
> 
> Can you please show me. I am surely not understanding this. I tried creating a different issue. I want to add a new project and not correct or add feature to an existing one. If possible can you please show me one. Please !!

Issue is assigned to you. @kumarjeetray
