### ISSUE TITLE
Word Transfer

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#434]
---
Title: Word Transfer
About: Transfer of word from one computer to another through ports 
Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

---

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
I will take the IP address of the server and take a random port number above 1023 and bind the two. The IP of the server and the same port will be used by the client to connect to the laptop and then the transfer of word will begin from client to server. As the server will get the word it will check it against a list of words and return the result as to whether the word is present in the list or not

**Additional context**

**Comment by prathimacode-hub** [comment]
Now, this looks good and justified. This issue is assigned to you. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Now, this looks good and justified. This issue is assigned to you. @kumarjeetray

Thanks a lot

**Comment by kumarjeetray** [comment]
Should I created another Pull request or make changes in the existing one ?

**Comment by prathimacode-hub** [comment]
I had responded to your PR about you the changes to be done. You should create a new one. Follow the steps mentioned in my reply. @kumarjeetray
