### ISSUE TITLE
Wordcloud

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#435]
Title: Wordcloud
About: It's a GUI script 
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Here we will a image having most of the words from a text file ,here by using wordcloud library we can do that and to plat the figure properly we will use matplotlib.

Example:
![Screenshot (601)](https://user-images.githubusercontent.com/71593494/122968494-38c06a00-d3a9-11eb-9cf5-ad2f8e0b7166.png)

**Comment by Debashish-hub** [comment]
Please elaborate what's going to happen? @neelshah2409

**Comment by neelshah2409** [comment]
Sir in this we will extract all the words from text file and using matplotlib and wordcloud libraries we will make a figure as shown in example using  words from text file .Here we can customise background and size of letters that appear in figure.

**Comment by prathimacode-hub** [comment]
This sounds interesting. You can work on this once you complete earlier issue assigned to you. @neelshah2409

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. @neelshah2409
