### ISSUE TITLE
Finding Number of days in a Month

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#436]
Title :- Finding Number of Days in a month
About : Through this code, we will able to find number of days in a month.
Name : ASHUTOSH KUMAR SAW
Label : Feature Request
Assign:"

Define You:
LGM-SOC'21 Participant
Contributor
 
Programming Language : Python

**Comment by Debashish-hub** [comment]
Issue is assigned to you @Ashu-1309
