### ISSUE TITLE
Zip Files Extractor

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#439]
Title: Zip File Extractor
About: In this we will fetch all the zip file using zipfile library.
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description: Here using zipfile library we will fetch all the files from zip to the same directory in which zip is present.

**Comment by prathimacode-hub** [comment]
Well needed script. This issue is assigned to you. You can proceed. @neelshah2409
