### ISSUE TITLE
ISS Tracker and on board crew names

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#444]
Title: ISS Tracker and onboard crew names
About: Implementation of this script is done by using a module like JSON, turtle, requests, webbrowser, geocoder, time and many other useful functions.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

-[x] LGM-SOC'21 Participant
-[x] Contributor
I'll write a Python script that will display the  crew name in txt format along with the current latitude and longitude of the iss. Using that updated lat and lon the location of iss is updated in the map in every 5 sec.

**Comment by prathimacode-hub** [comment]
Can you elaborate your issue more? @Aditya8821

**Comment by Aditya8821** [comment]
Yes, mam actually it will use the API and then collect the data i.e containing onboard crew names and the current location of the ISS(International Space Station), and then using that current location we locate those latitude and longitude on the world mam. These latitude and longitude will update at every 5 sec and then according to that updated value the location changes automatically in the map. So by this the map refreshes in every 5 sec and updates the position of iss.

**Comment by prathimacode-hub** [comment]
Wow, interesting. This issue is assigned to you. @Aditya8821
