### ISSUE TITLE
Wikipedia Summary Generator using Python Tkinter

### ISSUE THREAD

**Issue by pratimakush10** [prathimacode-hub/Awesome_Python_Scripts#445]
Title : Wikipedia Summary Generator using Python Tkinter
About : This python script will generate summary of topic given by the user.
Name : Pratima Kushwaha
Label : Feature Request
Assignee :

LGM-SOC'21: Participant

Description : I would like to implement python script in which summary of wikipedia generated using wikipedia module of python with GUI python tkinter can you please assign this to me?

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can go ahead. @pratimakush10
