### ISSUE TITLE
Highlight any selected part of text

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#446]
---
Title: Highlight any selected part of text
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this , a a highlight button will be created.
And user will be allowed to any text, or paragraph or sentence.
and after that when user selects any text or any area of text, then clicking on the highlight button highlights the selected with color, both foreground and background.

here text can be anything, letters, numbers, symbols or anything.

**Comment by akash435** [comment]
@prathimacode-hub , if we can do something like this, then please assign this issue to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Actually, this sounds more like an enhancement to the existing projects than an individual script. Correct me, if I'm wrong. @akash435

**Comment by akash435** [comment]
Can you please tell me the existing project name so that i can check?

**Comment by akash435** [comment]
For this script, i mean i was going to implement like this,

![1](https://user-images.githubusercontent.com/57003737/123510294-38211f80-d698-11eb-816a-4d987c6564df.jpg)

![2](https://user-images.githubusercontent.com/57003737/123510296-3bb4a680-d698-11eb-8aab-1a3204eee3c9.jpg)

![3](https://user-images.githubusercontent.com/57003737/123510297-3e170080-d698-11eb-8532-d80bec392a3a.jpg)

![4](https://user-images.githubusercontent.com/57003737/123510301-41aa8780-d698-11eb-90dd-1f6bbe79b623.jpg)

![5](https://user-images.githubusercontent.com/57003737/123510303-45d6a500-d698-11eb-97b6-29d965113923.jpg)

![6](https://user-images.githubusercontent.com/57003737/123510305-48d19580-d698-11eb-8155-c2f308592708.jpg)

Did you got something?

**Comment by prathimacode-hub** [comment]
I had got one, but that's completely different script from what I could see from ur screenshots. So do you want to work on this? @akash435

**Comment by akash435** [comment]
If this can be added, then yes please assign me, can work on this.

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @akash435
