### ISSUE TITLE
Indian Food Information

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#447]
---
Title: Indian Food Information
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script, user will be able  to get the complete information about the Indian food.

user just need to select or enter Indian food name, and can get information about 
ingredients
diet
its preparation time
its cooking time
in which state it is popular 
and in which region of india

**Comment by akash435** [comment]
@prathimacode-hub , If this is OK, then please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
That's great. But what about an other issue, you had asked for? I said so, because there are many text based scripts where you could add up that feature as enhancement. Should I assign this issue to you? @akash435

**Comment by akash435** [comment]
yes mam i can do that as an enhancement, can you please suggest with which project it is related to?

**Comment by prathimacode-hub** [comment]
> yes mam i can do that as an enhancement, can you please suggest with which project it is related to?

I shall check up and let u know, meanwhile you can work on this script. This issue is assigned. @akash435

**Comment by akash435** [comment]
ok mam
