### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#449]
---
Title: File Transfer
About: Transfer of file from one computer to another through ports 
Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

---

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
I will take the IP address of the server and take a random port number above 1023 and bind the two. The IP of the server and the same port will be used by the client to connect to the laptop and then the transfer of file will begin from client to server. As the server receives the file it sends a message to the client that it has got the file.

**Additional context**

**Comment by prathimacode-hub** [comment]
Similar script is just added up few mins ago. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Similar script is just added up few mins ago. @kumarjeetray

This is different. File transfer is not there

**Comment by prathimacode-hub** [comment]
Can you elaborate your issue? @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Can you elaborate your issue? @kumarjeetray

Like this code can be used to transfer file from a computer's normal os to a virtual machine/or another computer which is otherwise very tidious/difficult.

**Comment by prathimacode-hub** [comment]
Ok, fine I shall assign this issue. @kumarjeetray
