### ISSUE TITLE
Stone_Paper_Pencil_Rubber_Scisso

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#450]
---
Title: Stone_Paper_Pencil_Rubber_Scissor
About: A single and multiplayer game of stone,paper,pencil,rubber and bscissor.
Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

---

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
There are two methods to play this game. Either one person can play with the PC or it can be played between two people. If there is one player than the pc chooses one option randomly among stone,paper,pencil,rubber and scissor and the other player has to choose another option. In the second mode one player chooses one option and the other player chooses and option and the score is calculated at the end round-wise and a winner is declared.

**Additional context**

**Comment by prathimacode-hub** [comment]
This script is already available. Though I'm not sure about pencil and rubber. @kumarjeetray

**Comment by prathimacode-hub** [comment]
Before you create issue, once check it in respective repo's if the script is available so that ur efforts don't go wasted @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> This script is already available. Though I'm not sure about pencil and rubber. @kumarjeetray

That one is different and this one is different. This has rubber and pencil + single player

**Comment by prathimacode-hub** [comment]
Can you elaborate it? @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Can you elaborate it? @kumarjeetray
There to play the game two players are compulsory but here the game can be played by both one and two player(s).

**Comment by prathimacode-hub** [comment]
Is this the only difference? It can be added up as an enhancement to existing project, but I guess it won't suffice for individual project. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Is this the only difference? It can be added up as an enhancement to existing project, but I guess it won't suffice for individual project. @kumarjeetray

But the two are entirely different from coding standpoint. Would you like to see the code once ?

**Comment by prathimacode-hub** [comment]
> > Is this the only difference? It can be added up as an enhancement to existing project, but I guess it won't suffice for individual project. @kumarjeetray
> 
> But the two are entirely different from coding standpoint. Would you like to see the code once ?

Yes

**Comment by kumarjeetray** [comment]
> 
> 
> > > Is this the only difference? It can be added up as an enhancement to existing project, but I guess it won't suffice for individual project. @kumarjeetray
> > 
> > 
> > But the two are entirely different from coding standpoint. Would you like to see the code once ?
> 
> Yes

Should I put it here ?

**Comment by kumarjeetray** [comment]
[Stone_paper_pencil_rubber_scissor.zip](https://github.com/prathimacode-hub/Awesome_Python_Scripts/files/6701695/Stone_paper_pencil_rubber_scissor.zip)

**Comment by prathimacode-hub** [comment]
Ha, but concept is same. Can you compile the project and share a screenshot here? @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Ha, but concept is same. Can you compile the project and share a screenshot here? @kumarjeetray

Sure Thing !!

**Comment by kumarjeetray** [comment]
![Stone_paper_pencil_rubber_scissor_player_1](https://user-images.githubusercontent.com/53223216/123097402-bf2e8780-d44d-11eb-8531-3eafd34bd8c0.jpg)
![Stone_paper_pencil_rubber_scissor_player_2](https://user-images.githubusercontent.com/53223216/123097407-bfc71e00-d44d-11eb-8faf-ba0f7cd11143.jpg)

**Comment by prathimacode-hub** [comment]
Cool, ok you can add this up in "BasicPythonScripts". @kumarjeetray
