### ISSUE TITLE
age calculator

### ISSUE THREAD

**Issue by anandalisha** [prathimacode-hub/Awesome_Python_Scripts#453]
**Is your feature request related to a problem? Please describe.**
This application will help in calculating  age. 
This application can be used anywhere for example (in forms) by taking birth date and current date as input it will give the current age of person.

![Screenshot (68)](https://user-images.githubusercontent.com/55910525/123109640-08380900-d459-11eb-8d70-bb55ab2b2476.png)

**Comment by anandalisha** [comment]
@prathimacode-hub If you find it okay then please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Already an issue is assigned to you. You can work on only 1 issue at a time. @anandalisha

**Comment by anandalisha** [comment]
@prathimacode-hub okay!!

**Comment by prathimacode-hub** [comment]
You should never close issue or PR from your end, it's better you remember this. @anandalisha
