### ISSUE TITLE
implement age calculator

### ISSUE THREAD

**Issue by anandalisha** [prathimacode-hub/Awesome_Python_Scripts#456]
Title: Age calculator
About: Implementation of age calculator system using different python libraries
Name: Alisha Anand
Label: Feature Request
Assignee: 

LGM-SOC'21: Participant
 
Description:
This application can be used anywhere for example (in forms) by taking birth date and current date as input it will give the current age of person as output. 
 I have implemented this application  using various python modules with GUI python tkinter .
Can you please assign this to me under LGM-SOC'21?

**Comment by anandalisha** [comment]
@prathimacode-hub if you find it okay, please assign

**Comment by prathimacode-hub** [comment]
Perfect, this issue is assigned to you. You can start working. @anandalisha
