### ISSUE TITLE
speech recognizer using python

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#459]
Title: want to make a speech recognizer  
Name: **Umesh Singh**
Label: Feature Request
Define You
- [x] LGM-SOC'21 Participant
- [ ] Contributor

### Solution
I want to make a speech recognizer using Python. With this human voice can be converted into text. It uses speech recognition module to do this job.

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @Umesh-01

**Comment by Umesh-01** [comment]
thank u mam

**Comment by chandu6111** [comment]
@prathimacode-hub I would like to extend this feature.
This script is basically about converting **voice to text**. I want to make a voice assistant which converts voice to text and then **replies back to the user via voice**. The voice assistant can:
1) speak
2) opens Notepad | Paint | Calculator | Twitter | LinkedIn | Facebook | WhatsApp | YouTube | Gmail | Google
It has some other functionalities. 
**So, should I open a new issue on that? Or can I add the features to this issue? Is there any possibity?**

Please do let me know.
Thank you:)
