### ISSUE TITLE
Virtual keyboard

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#460]
---
Title: Virtual keyboard
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
we will create a virtual keyboard, that allows user to take entry or input from that virtual keyboard.

And will try to embed this virtual keyboard under a button, clicking on which virtual keyboard opens.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC, can add this virtual Keyboard in GUIScripts.

**Comment by prathimacode-hub** [comment]
Sure, go ahead. Issue assigned. @akash435
