### ISSUE TITLE
Internet Speed Tracker GUI

### ISSUE THREAD

**Issue by Khushi-sharma07** [prathimacode-hub/Awesome_Python_Scripts#465]
Title: Internet Speed Tracker
About: Add a script to create Internet Speed Tracker using Python

Name: Khushi Sharma
Label: Feature Request
Assignee: "

Define You:

- [x]  LGM-SOC'21 Participant
- [ ]  Contributor

Solution:
It will be a GUI Python Script which will help a person to calculate the download speed, upload speed and ping of the network.

**Comment by Khushi-sharma07** [comment]
Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue is assigned to you. @Khushi-sharma07
