### ISSUE TITLE
Stock Visualiser

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#466]
Title: Stock Visualiser
About: Here we will see the growth of stock using mpl finance library for a time period which user can define.
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:

- [x]  LGM-SOC'21 Participant
- [ ] Contributor
In this script, using mpl finance we will fetch growth and then using pandas we will read the data and then using matplotlib we will  plot a graph for that. Here we will give an option for selecting the duration for visualizing the stock growth.

**Comment by Debashish-hub** [comment]
Interesting! Issue is assigned to you @neelshah2409
