### ISSUE TITLE
World bank GDP Ranking

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#467]
---
Title: World bank GDP Ranking
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
we will create an application in which we can get the GDP ranking of any World Bank 
along with its amount in US dollars.

**Comment by akash435** [comment]
@prathimacode-hub, please assign this issue to me under LGM SOC, will add this script under GUIScripts.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
