### ISSUE TITLE
Solitaire game 

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/Awesome_Python_Scripts#468]
Title: Solitaire game using Pyqt5 
About: Add a python GUI script to implement solitaire game 

Name: Akash Jain 
Label: Feature Request
Assignee: "

Define You:

LGM-SOC'21 Participant
Contributor
Solution:
It will be a GUI Python Script in which user a play a solitaire game.

**Comment by Akash20x** [comment]
@prathimacode-hub Please assign me this issue as a part of LGM-SOC'21.

**Comment by Debashish-hub** [comment]
Interesting! Issue is assigned to you @Akash20x

**Comment by Akash20x** [comment]
@Debashish-hub Please also add level tag

**Comment by Debashish-hub** [comment]
> @Debashish-hub Please also add level tag

This will be done after your PR is approved @Akash20x

**Comment by Akash20x** [comment]
> > @Debashish-hub Please also add level tag
> 
> This will be done after your PR is approved @Akash20x

OK

**Comment by Akash20x** [comment]
@Debashish-hub Please check my pull request
