### ISSUE TITLE
Air Quality Detector API

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#470]
Title: Air Quality Detector API
About: Here we can find the air quality index of a particular city using the  api.
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description: Here we can find air quality index through api using json and requests library and it will also show whether it  is good or bad index.

**Comment by prathimacode-hub** [comment]
That's interesting. This issue is assigned to you. You can get going. @neelshah2409
