### ISSUE TITLE
Grade Calculator 

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#471]
Title :- Grade Calculator.
About : Through this code will be use to calculate the grade of a student . 
Name : ASHUTOSH KUMAR SAW
Label : Feature Request
Assign:"

Define You:
LGM-SOC'21 Participant
Contributor

Programming Language : Python

**Comment by prathimacode-hub** [comment]
Ok, this issue is assigned to you. You can start working. @Ashu-1309
