### ISSUE TITLE
Collage Mosaic Generator

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#476]
---
Title: Collage Mosaic Generator
About: To make python script for creating mosaic images
Name: Rammya Dharshini
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

## Description : 

A collage mosaic that is made up of thousands of small images.

**Comment by prathimacode-hub** [comment]
Upto how many images would you fit into collage? @rammya29

**Comment by rammya29** [comment]
I think around 600-700 images but I try to look for 1000 images

**Comment by prathimacode-hub** [comment]
Ok, cool. Hope it would give enough clarity. All the best. You can proceed. This issue is assigned to you. And also congrats for being a winner at skillathon girlscript foundation. 🎊🧨@rammya29

**Comment by rammya29** [comment]
Tq for motivation and i have doubt, Am I the winner of Skillathon girlScript Foundation ?

**Comment by prathimacode-hub** [comment]
> Tq for motivation and i have doubt, Am I the winner of Skillathon girlScript Foundation ?

Yes, you are if you did participate. I saw your full name over there. If you want, I can share you the link of it. @rammya29
