### ISSUE TITLE
Add rock-paper-scissors-start game

### ISSUE THREAD

**Issue by tjanhvi** [prathimacode-hub/Awesome_Python_Scripts#478]

**Comment by prathimacode-hub** [comment]
This is done long back. Also read the README and CONTRIBUTING GUIDELINES of the project before you raise an issue. This issue doesn't have a template as well. Come up with another issue but make sure it isn't done. Also use the issue template given while creating up an issue. @tjanhvi

**Comment by tjanhvi** [comment]
okay :)
