### ISSUE TITLE
Add coffee machine game

### ISSUE THREAD

**Issue by tjanhvi** [prathimacode-hub/Awesome_Python_Scripts#479]
Please assign me this issue

**Comment by prathimacode-hub** [comment]
Add your issue template please. You can refer other assigned issues to know how template looks like. That is to know you as a LGMSOC participant. I hope you are. @tjanhvi

**Comment by tjanhvi** [comment]
Title: coffee machine game using python
About: Add a BasicPythonScripts to implement coffee machine game

Name: Janhvi Tiwari
Label: Feature Request
Assignee: "

Define You:
LGM-SOC'21 Participant

Solution:
It will be a BasicPythonScripts in which the user play a coffee machine game.

**Comment by prathimacode-hub** [comment]
Why did u close it? You just have to add your template. You should not close issue or PR from your end. @tjanhvi
