### ISSUE TITLE
tic tac toe game

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/Awesome_Python_Scripts#48]
Can I create a simple tic tac toe game? I'm a participant of LGM Soc21.

**Comment by prathimacode-hub** [comment]
Yeah, you can. But if you want your contribution to count under LGM SoC21, you should wait until June 10th. @Jagannath8

**Comment by Jagannath8** [comment]
Okay I'll wait till June 10

**Comment by prakhar07msd** [comment]
Hey can i create tic tac game?

**Comment by prathimacode-hub** [comment]
Create a new issue with the template given in README. You can refer assigned issues to know how template should look like. Once you do that, I can assign it to you @prakhar07msd

**Comment by prathimacode-hub** [comment]
As I said it's on FCFS basis after the given time, tic tac toe game is already is assigned. You can create some other issue. @Jagannath8

**Comment by Jagannath8** [comment]
Mam I've created the "tic tac toe game" issue on 7June.

**Comment by prathimacode-hub** [comment]
Yes, but FCFS basis is application only from 10th June, as contribution period starts only from 10th June. This is to be fair with everyone. @Jagannath8
