### ISSUE TITLE
Direct Flight Route Finder

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#480]
---
Title: Direct Flight Route Finder
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to first select the source airport and destination airport, 
and the script will tells us that if there is a direct route between them or not.

If there exist a direct route, then it also tells us about the source airport id and destination airport id.

**Comment by akash435** [comment]
@prathimacode-hub , if this can be added, then please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. Issue assigned. @akash435
