### ISSUE TITLE
bouncing ball

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#482]
---
Title: Bouncing ball
About: the image of the ball will bounce slowly from top to bottom , right top corner to left bottom corner, similarly, vice-versa.
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
I will be using python mam and this will come under Image processing script.

please assign this issue to me mam, I would like to work on this @prathimacode-hub mam.

**Comment by prathimacode-hub** [comment]
This issue is already done. You can take up an another issue to work on. @manognyaa
