### ISSUE TITLE
Text Editor using Python

### ISSUE THREAD

**Issue by chandu6111** [prathimacode-hub/Awesome_Python_Scripts#485]
**Title**: Text Editor using Python
**Name**: Chandana (chandu6111)
**Label**: Feature Request

**Description of the Script**:
This script comes under GUIScripts. I want to make a text editor (for example, notepad). These are the features of the script:
- It has a place where the user can type the text( Text area)
- It will have 3 Buttons:
1) **Save File**- This Button is used to save the text the user has typed in the editor.
2) **Open File**- This Button is used to enable users to select any text document from their local system i.e, it opens the file dialog and users can select any text document and view it in the editor.
3) **Clear**- This Button is used to clear the complete text in the editor.

- [x]  **LGM-SOC'21- participant**

**Comment by chandu6111** [comment]
@prathimacode-hub please assign me this issue under LGM-SOC'21

**Comment by Debashish-hub** [comment]
Is it similar to #239 @chandu6111

**Comment by chandu6111** [comment]
But that doesn't have these extra options of saving file, opening files etc. 
So that's why I tried opening this issue.

**Comment by prathimacode-hub** [comment]
You can work on this as enhancement, if you are interested to an existing project. @chandu6111

**Comment by prathimacode-hub** [comment]
Are you willing to work on this as an enhancement? @chandu6111

**Comment by chandu6111** [comment]
No @prathimacode-hub, you can close it, or make it up-for-grab, anything is fine for me

**Comment by prathimacode-hub** [comment]
Ok, sure. @chandu6111
