### ISSUE TITLE
SpaceX Mission Detailer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#486]
---
Title: SpaceX Mission Detailer
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the details about all the SpaceX mission that have occurred.

This will include all the mission starting from 2006 till present times.

This will detail about Launch date, Flight number, launch time, 
what was vehicle type , pyload type, payload mass and also the customer Name.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC, can add this under GUI Script

**Comment by Debashish-hub** [comment]
Sounds Interesting! Issue is assigned to you @akash435
