### ISSUE TITLE
Detect Language API

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#487]
Title: Detect Language API
About: API script project
Name: Pooja Deshpande
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant

In this project I will use Detect Language API module that will act as client library. With help of a API Key, a statement when provided, its language can be detected with confidence level and this project will be presented in GUI format.

**Comment by prathimacode-hub** [comment]
Can you elaborate more? @cybot-des

**Comment by cybot-des** [comment]
Yes, so in this gui user will provide any statement or paragraph of any language and upon clicking detect button we will get the output of the language to which it belongs

**Comment by cybot-des** [comment]
https://detectlanguage.com/
I will be generating api key from this site  and then I will use a client library in python for this api

**Comment by prathimacode-hub** [comment]
Cool, you can proceed. Issue assigned. @cybot-des
