### ISSUE TITLE
Acronym Of The Word

### ISSUE THREAD

**Issue by Khushi-sharma07** [prathimacode-hub/Awesome_Python_Scripts#488]
Title: Acronym Of The Word
About: Add a basic Python Script that will give the acronym of the word 
Name: Khushi Sharma
Label: Feature Request
Assignee: "

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Solution:
It will be a basic python script that will give the acronym of the word like if the user enters Artificial Intelligence then the output will be AI i.e. the initials of the word.

Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
That's fun. Get going.
