### ISSUE TITLE
Stopwatch GUI

### ISSUE THREAD

**Issue by aishwaryachand** [prathimacode-hub/Awesome_Python_Scripts#49]
I would like to work on a stopwatch GUI

**Comment by prathimacode-hub** [comment]
Glad to see your interest to contribute. Are you a LGM-SOC participant? @aishwaryachand

**Comment by aishwaryachand** [comment]
yes I am @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Great. You can start your contribution once period starts. You had created the issue for now. But to get it counted under LGM-SOC and for adding up a label, you should create a new issue with the template mentioned in README. That's when the issue can be assigned. @aishwaryachand

**Comment by rishabhrathore055** [comment]
@prathimacode-hub Pls assign this issue

**Comment by prathimacode-hub** [comment]
As there is no response from you since very long, i had to close this issue. If ur interested, you can raise an issue again.  @aishwaryachand
