### ISSUE TITLE
Fidget Spinner

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#492]
Title: Fidget Spinner
About: Its a game basically for fun  using turtle and distutils.
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

As the fidget were on the trends for sometime ,we will make a virtual fidget which will move as we press the space button and as fast we will press the button the speed of fidget increases.
Here we can customise all the things like colour , speed of fidget ,etc.

![output(fidget)](https://user-images.githubusercontent.com/71593494/123414115-1c9f1180-d5d1-11eb-86e2-e94cd89d77ba.png)

**Comment by prathimacode-hub** [comment]
Interesting, go ahead. @neelshah2409
