### ISSUE TITLE
Periodic Table Elements Information

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#493]
---
Title: Periodic Table Elements Information
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the details about the any periodic table elements.

This will include all the 118 element  that are in periodic table.

For each periodic element, it will show details about its
1.) symbol
2.) Appearance (how that element looks like)
3.) What is it's atomic number
4.) That element is present in  which group block of periodic table
5.) Period of the element
6.) The category of element to which it belongs

**Comment by akash435** [comment]
@prathimacode-hub , if this can be added under GUIScripts , then please assign me this under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned, creative script. @akash435
