### ISSUE TITLE
Dodge Charger Game

### ISSUE THREAD

**Issue by MuditCh57** [prathimacode-hub/Awesome_Python_Scripts#495]
---
Title: Dodge Charger Game
About: It is car based game made with python and pygame module. 
Name: Mudit Choudhary
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

You are driving on a highway in wrong way. You have to dodge 
your car and stay alive. 
Features :- 
1. You can collect coins and use them to buy different vehicles.
2. Collect heart to increase your car's health.
3. Enemy's car speed will also increase.

![pygame window 25_06_2021 6_28_05 pm](https://user-images.githubusercontent.com/74391865/123428499-80cad100-d5e3-11eb-80f8-e091681ddfe1.png)
![pygame window 25_06_2021 6_29_33 pm](https://user-images.githubusercontent.com/74391865/123428521-86281b80-d5e3-11eb-8f00-1cf844066d30.png)

**Comment by prathimacode-hub** [comment]
Interesting, you can proceed. @MuditCh57
