### ISSUE TITLE
Instagram Bot

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#499]
Title: Instagram Bot
About: here we will download profile picture and can follow someone and many more things through our script.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Here we are going to make a script  which will do all the things of instagram from download to uploading.
Here we can ->download profile picture .->upload a picture with caption -> follow someone
and many more features.

**Comment by prathimacode-hub** [comment]
Your issue doesn't feature ur name? @neelshah2409

**Comment by neelshah2409** [comment]
> Your issue doesn't feature ur name? @neelshah2409

Yes mam sorry by mistake 🙏

**Comment by prathimacode-hub** [comment]
Cool, no worries. Issue assigned. @neelshah2409
