### ISSUE TITLE
Password generator

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#50]
For generating a password I had used random lib. ,which generates random password of 8(length including alphabets, numbers and special characters)

**Comment by prathimacode-hub** [comment]
That's an interesting one to contribute. Sure, I will keep this issue open but make sure you get it assigned asap on June10th. Good to see your initiation and enthusiasm. All the best for your open source journey. @neelshah2409

**Comment by neelshah2409** [comment]
Thank you so much mam and I may submit it today or after 10 th??

**Comment by prathimacode-hub** [comment]
To get it counted under the LGM-SOC program you have raise a PR after June 10th. And also one more thing, I hadn't assigned this issue to you yet. So it won't be considered. One June 10th, the very first thing you will be doing is create a new and separate issues by referring the README and CONTRIBUTING GUIDELINES to get your projects assigned to you. You can only create a PR once it is assigned. @neelshah2409

**Comment by neelshah2409** [comment]
Mam please assign me so I can make a PR for this issue

**Comment by neelshah2409** [comment]
Title: Password Generator
About: I want to implement a python script for this problem using random library
Name: Neel Shah
Label: Feature Request
Assignee: ''

LGM-SOC'21>Participant

Description:> My approach would be like using random lib. it will generate a random password of 8 digit and also we can change the length of password.

**Comment by prathimacode-hub** [comment]
You have to raise a new issue with same desription as this issue is created 3 days ago. And you can work on only 1 issue at a time. So decide the issue you would like to work on first.

**Comment by neelshah2409** [comment]
Okay mam, I will do one by one.

**Comment by Adarsh357** [comment]
Can i do this

**Comment by Adarsh357** [comment]
Assign it to me

**Comment by prathimacode-hub** [comment]
You have to create a new issue using the template given to get it assigned to you. @Adarsh357

**Comment by Parth-Shete** [comment]
@neelshah2409 Can I work on this issue? Please assign me this issue.

**Comment by prathimacode-hub** [comment]
This issue is already done. @Parth-Shete
