### ISSUE TITLE
Add coffee machine game.

### ISSUE THREAD

**Issue by tjanhvi** [prathimacode-hub/Awesome_Python_Scripts#500]
Title: coffee machine game using python
About: Add a BasicPythonScripts to implement coffee machine game

Name: Janhvi Tiwari
Label: Feature Request
Assignee: "

Define You:
LGM-SOC'21 Participant

Solution:
It will be a BasicPythonScripts in which the user play a coffee machine game.

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. You can proceed working. @tjanhvi
