### ISSUE TITLE
Indian University NIRF Ranking

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#501]
---
Title: Indian University NIRF Ranking
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the NIRF Ranking of any top university in India.

This will include almost 200 top universities of India.

Along with NIRF Ranking, this application will also tells us about 5 things,
1) Teaching, Learning & Resources (TLR)
2) Research and Professional Practice (RPC)
3) Graduation Outcomes (GO)
4) Outreach and Inclusivity (OI)
5) Peer Perception

The NIRF Ranking of any university is decided on the basis of these above 5 values.

**Comment by akash435** [comment]
@prathimacode-hub , If this can be added under GUIScripts, then please assign me this under LGM SOC.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. @akash435
