### ISSUE TITLE
PDF to JPG Converter

### ISSUE THREAD

**Issue by sahilsingh2402** [prathimacode-hub/Awesome_Python_Scripts#503]
**Title :** PDF to Image in python
**About :** .pdf to .jpg file converter 
**Name :** Sahil Singh
**Label :** Feature Request
**Assignee :**

**LGM-SOC'21:** Participant

**Description :** I would like to create a simple file converter, which would convert documents of .pdf format to .jpg images in python using some of its libraries. Please assign this to me. @prathimacode-hub

**Comment by sahilsingh2402** [comment]
Please assign this to me. @prathimacode-hub

**Comment by Debashish-hub** [comment]
Good choice @sahilsingh2402 . Issue is assigned to you

**Comment by Debashish-hub** [comment]
Hey @sahilsingh2402 Any update on your work?

**Comment by sahilsingh2402** [comment]
I am not in a good health from a few days. Please assign this issue to someone else :( @Debashish-hub

**Comment by prathimacode-hub** [comment]
No worries, health comes first. Get well soon. Yup. @sahilsingh2402
