### ISSUE TITLE
Split Each Excel Sheet Into Separate Excel Files.

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#508]
---
Title: Split Each Excel Sheet Into Separate Excel Files.
About: We'll look at how to divide Excel sheets into distinct Excel files using numerous libraries of Python.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

We all know how crucial Excel sheets are today for holding large data packets. We will divide the sheets using the xlwings package, which is defined in Python.

**Comment by Debashish-hub** [comment]
Go ahead @Iamtripathisatyam Issue is assigned to you.
