### ISSUE TITLE
Fruit Ninja Game

### ISSUE THREAD

**Issue by Khushi-sharma07** [prathimacode-hub/Awesome_Python_Scripts#509]
Title: Fruit Ninja Game
About: Add a Python PyGame Script for a game which is very popular among kids the children use to slice the fruits and score points.
Name: Khushi Sharma
Label: Feature Request
Assignee: "

Define You: 

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Solution:
It will be a very fun Python PyGame Script game for kids that will entertain them. The kids will slice the fruits and score some points. 

Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Khushi-sharma07
