### ISSUE TITLE
Typing Speed test

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#51]
In this I had used time lib. for calculating the time taken by user to write the given sentence and it also indicates the errors.

**Comment by prathimacode-hub** [comment]
Fab script. is your project ready? @neelshah2409

**Comment by neelshah2409** [comment]
yes I haved worked on the logic and it will be complete today

**Comment by prathimacode-hub** [comment]
> yes I haved worked on the logic and it will be complete today

Ok

**Comment by neelshah2409** [comment]
mam now please assign me this issue under LGM-SOC

**Comment by neelshah2409** [comment]
Title: Typing Speed test
About: I want to implement a python script for this problem using time library 
Name: Neel Shah
Label: Feature Request
Assignee: ''


LGM-SOC'21>Participant

Description:> My approach would be like using  time lib. for calculating the time taken by user to write the given sentence and it also indicates the errors.

**Comment by prathimacode-hub** [comment]
Ceasar Encryption or Typing Speed Test. Which one you would like to work on first? As I can assign only 1 issue at a time. @neelshah2409

**Comment by neelshah2409** [comment]
Typing Speed test

**Comment by prathimacode-hub** [comment]
Then raise a new issue for typing speed test using the template. @neelshah2409
