### ISSUE TITLE
Document Converter App

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#513]
---
Title: Document Converter App
About: Using Python Scripts, to create an application where we can change the document format like pdf to word, excel to pdf, image jpg to png etc...
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

  Yes, This application has a lot of features so we don't want to use multiple applications for this.  

**Describe the solution you'd like...**

I would like to use python modules like tkinker, FPDF, PyPDF2, dox2PDF, etc.

Please assign this task to me.

**Comment by prathimacode-hub** [comment]
Interesting, but point to note: PDF to JPG is already done. Other than that, you can use rest of the conversions. If you're ok with it? @rammya29

**Comment by rammya29** [comment]
Its okay mam, assign to me mam, i ill do it

**Comment by prathimacode-hub** [comment]
Sure, you can proceed. @rammya29

**Comment by rammya29** [comment]
Hi mam, Sorry for inconvenience, due to system's older version some python modules are not accepted so I am unable to do it. Can I come up with some other issue?

**Comment by prathimacode-hub** [comment]
Yeah, sure. No worries. I will keep this issue open. @rammya29

**Comment by rammya29** [comment]
Tq mam

**Comment by prathimacode-hub** [comment]
> Tq mam

So, can this be assigned to someone else? @rammya29

**Comment by rammya29** [comment]
Yeah, if some other is willing to take this, surely they can work on this. No issues mam

**Comment by prathimacode-hub** [comment]
> Yeah, if some other is willing to take this, surely they can work on this. No issues mam

Ok, cool

**Comment by chandu6111** [comment]
@prathimacode-hub please assign me this issue as it is up-for-grab, I will do the task.

**Comment by prathimacode-hub** [comment]
Yes, you can work on it. As said, PDF to JPG is already taken. Other than that, you can work on other conversions. @chandu6111

**Comment by Debashish-hub** [comment]
Hey! @chandu6111 Any update on your work?

**Comment by chandu6111** [comment]
> Hey! @chandu6111 Any update on your work?

Hey, I have actually worked on 4 conversions already, they are: 
1) excel to pdf
2) jpg to pdf
3) jpg to png
4) pdf to word

I am working on 2 more conversions right now something like ppt to pdf
So please give me some time, I would definitely create PR in 5 days. I actually want to make these conversions project fully fledged with all extensions. Please do give me some time... @prathimacode-hub and @Debashish-hub

**Comment by prathimacode-hub** [comment]
Also add up PDF to JPG converter, it was assigned earlier. But they no longer want to work on it. @chandu6111
