### ISSUE TITLE
BITCOIN PRICE

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#514]
---
Title: Bitcoin pricer
About: this project will help in telling the bitcoin price when you add an input
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
I will be using python mam .
please assign this issue to me mam, I really want to work @prathimacode-hub mam.

**Comment by prathimacode-hub** [comment]
This issue is already done. @manognyaa
