### ISSUE TITLE
Binary Calculator GUI

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#515]
---
Title: Binary Calculator
About: this is a calculator where in it will give yo the answer of the given input by the user.
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
I will be using python mam
please assign this issue to me @prathimacode-hub mam, I would like to work on this.

**Comment by prathimacode-hub** [comment]
You're good to go. Can proceed. @manognyaa
