### ISSUE TITLE
Excel File Automation

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#518]
Title: Excel File Automation
About: here we will make excel file using openpyxl.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor
Describe the solution you'd like...
Here we will make excel file through our script using openpyxl and we can set the data and column name as per our requirement.

**Comment by prathimacode-hub** [comment]
You can proceed. @neelshah2409
