### ISSUE TITLE
All Indian Trains

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#519]
---
Title: All Indian Trains
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get Starting junction, Ending Junction and the train no. 
by selecting the train name.

for eg.) 
If user select train name as "Ahmadabad Passenger"
then script will tell that 
train no. : 59439
train starting junction : Mumbai Central
train ending junction : Ahmedabad Junction

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC, if this is OK.

**Comment by prathimacode-hub** [comment]
Interesting, you can start working. @akash435
