### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#521]
Title :- Pattern
About : Through this code will be able to print out different patterns . 
Name : ASHUTOSH KUMAR SAW
Label : Feature Request
Assign:"

Define You:
LGM-SOC'21 Participant
Contributor

Programming Language : Python

**Comment by Debashish-hub** [comment]
Please elaborate @Ashu-1309

**Comment by Ashu-1309** [comment]
Through this program we can make different patterns like ladder pattern , star pattern.

**Comment by prathimacode-hub** [comment]
Ok, is it a GUI scripts? @Ashu-1309

**Comment by Ashu-1309** [comment]
Noo

**Comment by prathimacode-hub** [comment]
Can you elaborate more. @Ashu-1309

**Comment by Ashu-1309** [comment]
Like this type of pattern s


![Screenshot_2021-06-27-13-17-40-166_com android chrome~2](https://user-images.githubusercontent.com/60690692/123536832-2d26c780-d74a-11eb-93b5-836572558b87.jpg)

**Comment by prathimacode-hub** [comment]
Ok, got it. Issue assigned. @Ashu-1309
