### ISSUE TITLE
Move Files To Creation and  Modification Date Named Directories

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/Awesome_Python_Scripts#522]
---
Title: Move Files To Creation and  Modification Date Named Directories
About: We'll attempt to write a Python script that will transfer all of your files to new folders depending on their creation and modification dates.
Name: Satyam Tripathi 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

We'll attempt to write a Python script that will transfer all of your files to new folders depending on their creation and modification dates.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @Iamtripathisatyam
