### ISSUE TITLE
Solar System Objects Details

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#527]
---
Title: Solar System Objects Details
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the details about the solar system objects.

The details will be in terms of Radius , Mass , Density, Gravity , Semi Major Axis, Orbital Period, Type and Year of Discovery.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC, will add this under Python Scripts.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
