### ISSUE TITLE
Virtual Voice Assistant using python

### ISSUE THREAD

**Issue by chandu6111** [prathimacode-hub/Awesome_Python_Scripts#528]
**Title**: Virtual Voice Assistant using python
**Name**: Chandana (chandu6111)
**Label**: Feature Request

The voice assistant project is really fascinating. We always want someone to do tasks as we instruct. A voice assistant is no exception for that. This project is completely voice-based.
The voice assistant can:
- play a song
- Tell the time
- Crack a joke
- Search in Wikipedia
- Opens: Notepad | Paint | Calculator | Twitter | LinkedIn | Facebook | WhatsApp | YouTube | Gmail | Google

- [x] LGM-SOC'21

**Comment by chandu6111** [comment]
@prathimacode-hub please do assign me this issue under LGM-SOC'21

Thank you

**Comment by prathimacode-hub** [comment]
This issue is already done. You can take up an another issue to work on. @chandu6111
