### ISSUE TITLE
String to ASCII

### ISSUE THREAD

**Issue by Vaibhav-Vipin** [prathimacode-hub/Awesome_Python_Scripts#530]
**Title:** String to ASCII Generator
**About:** ASCII Value of all Characters in String
**Name:** Vaibhav Vipin
**Level:** Feature Request
**Assignee:** ""

**Define You:**

- [X] LGM-SOC'21 Participant

- [ ] Contributor

**Description:** A python program that prints ASCII value of all characters of a string entered by the user. 

Eg: _If a user enters string as_: LGM-SOC
```
L        76
G        71
M        77
-        45
S        83
O        79
C        67
```

**Comment by prathimacode-hub** [comment]
Good choice, you can proceed. Issue assigned to you. @Vaibhav-Vipin
