### ISSUE TITLE
World Companies Detailer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#537]
---
Title: World Companies Detailer
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the details about the different top companies in the world.

The details will be in terms of 
Company name
Sales ($billion)
Global Rank
Profits ($billion)
Assets ($billion)
Market Value ($billion)
Country
Continent
Latitude,
Longitude.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC, will add this in GUI Scripts.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
