### ISSUE TITLE
Weather Updates (Web Scraping)

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#539]
Title: Weather Updates
About: Here we can get weather information of any city  
Name: Neel Shah
Level: Feature Request
Assignee: ""

Define You:

- [x] LGM-SOC'21 Participant

- [ ] Contributor

Description: By using requests and bs4 library we will fetch the weather information of any city  form the website.

**Comment by prathimacode-hub** [comment]
You can proceed. @neelshah2409
