### ISSUE TITLE
Image Steganography

### ISSUE THREAD

**Issue by skimran2000** [prathimacode-hub/Awesome_Python_Scripts#54]
Image Steganography is a process of hiding secret message in any image in such a way that no one can know the presence or contents of the hidden message.
I have first converted the secret message into 8-bit binary data and then used PIL module of python to extract pixels of image and modify it into 8-bit binary data so that I could store the secret message with it.

**Comment by prathimacode-hub** [comment]
Wow, awesome. Are you a participant of LGM-SOC? @skimran2000

**Comment by skimran2000** [comment]
Yes I am a participant of LGM-SOC

**Comment by prathimacode-hub** [comment]
Cool. You got to raise your issue using the template mentioned in README after 10th of june. Do make sure to create a new issue then and get it assigned. All the best for your open source journey. Any queries, don't hesitate to ask. @skimran2000

**Comment by skimran2000** [comment]
Thank you mam

**Comment by skimran2000** [comment]
In which file should I save this program?

**Comment by prathimacode-hub** [comment]
It should go under "ImageProcessingScripts". I have mentioned all the details in README file. @skimran2000

**Comment by skimran2000** [comment]
Ok mam
