### ISSUE TITLE
Bermuda Triangle Incidents

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#541]
---
Title: Bermuda Triangle Incidents
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the details incident that took place in past years.

In this user just need to select he years and he/she will be able to get the details about how many incident took place.

Also for each incidents, the details will be like, on which date, what happened, where happened and the conclusion.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC, will add this under GUI scripts.

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. You can start working. @akash435
