### ISSUE TITLE
Editor App

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#542]
---
Title: Editor App
About: This is a simple editing app that will allow the image to edit the features like, rotate, flip, add a border, blur, contrast, etc..
Name:  Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

 Yes, this project includes all the features mentioned above.

**Describe the solution you'd like...**

I will use python scripts for this project and import modules like Tkinter, PIL.

**Describe alternatives you've considered?**

The alternative may be using only PIL images to do this project.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @rammya29

**Comment by rammya29** [comment]
Inside which folder we have submit and create pull request

**Comment by Debashish-hub** [comment]
You can create it under ImageProcessingScripts as it is related to that.
