### ISSUE TITLE
MCQ

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#544]
---
Title: MCQ
About: This is a simple program which stores multiple choice questions and their answers. When a user opens it, it will prompt the user the questions along with the options and the user will have to answer the question. At the last it will show the score, the correct answers and the answers given by user. 
---

Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Is your feature request related to a problem? Please describe.

I will create the file.

Describe the solution you'd like...

I will use python scripts for this project which would do the necessary tasks.

Describe alternatives you've considered?

N.A

**Comment by prathimacode-hub** [comment]
This issue is assigned. You can proceed. @kumarjeetray
