### ISSUE TITLE
Calculating Compound Interest 

### ISSUE THREAD

**Issue by Vaibhav-Vipin** [prathimacode-hub/Awesome_Python_Scripts#545]
**Title:** Compound Interest 
**About:** Calculating Compound Interest 
**Name:** Vaibhav Vipin
**Level:** Feature Request
**Assignee:** ""

**Define You:**

- [X] LGM-SOC'21 Participant

- [ ] Contributor

**Description:** A python program that calculates Compound Interest, considering several factors.

Eg: 
```
How many years will you save? 
Enter years: 10
How much money is currently in your account? 
Enter amount: 100
Enter interest in decimal numbers (10% = 0.1): 0.05
How much money do you plan on investing monthly?
Enter amount:100

Your money in 10 years will be :16011.0340575

```

**Comment by prathimacode-hub** [comment]
Issue assigned. You can proceed. @Vaibhav-Vipin
