### ISSUE TITLE
Base convertering

### ISSUE THREAD

**Issue by Vaibhav-Vipin** [prathimacode-hub/Awesome_Python_Scripts#546]
**Title:** Base converter
**About:** Base converter (Binary, decimal, hexadecimal & Octal etc.) to (Desired base (i.e. Binary, decimal, hexadecimal & Octal))
**Name:** Vaibhav Vipin
**Level:** Feature Request
**Assignee:** ""

**Define You:**

- [X] LGM-SOC'21 Participant

- [ ] Contributor

**Description:** 
A python program which can handle any number and base we give, and it can output the desire base we need.
Eg :-  
If a user enter a Decimal number (base 10) and wants to convert it to binary number (Base 2)
i.e. `50, then Output should show 110010.`

**Comment by prathimacode-hub** [comment]
Interesting, have you finished up your previous issue taken. @Vaibhav-Vipin

**Comment by Vaibhav-Vipin** [comment]
> 
> 
> Interesting, have you finished up your previous issue taken. @Vaibhav-Vipin
Yes (on local device),
P.S: I want to learn about Git/GitHub (multiple branching) and wants to have at least two opened issues. This will not create any issue with master branch.

Can you please assign this issue to me.

**Comment by Vaibhav-Vipin** [comment]
> 
> 
> Interesting, have you finished up your previous issue taken. @Vaibhav-Vipin

Yes (on local device),
P.S: I want to learn about Git/GitHub (multiple branching) and wants to have at least two opened issues. This will not create any issue with master branch.

Can you please assign this issue to me.

**Comment by prathimacode-hub** [comment]
It's not about you not able to do it or not. But it's on one issue at a time, sorry to say but we have to abide by it. You can start working on this, once you create your previous PR. If you want to learn Git/Guthub, I shall guide. @Vaibhav-Vipin

**Comment by Vaibhav-Vipin** [comment]
> n one issue at a time, sorry to say but we have to abide by it. You can start

That's fine, and I have finished the previous issue.
And I do want to learn few concepts in Git/GitHub, e.g. if any git project is huge (1-2 GB) and using git clone is not an option for me due to data cap. How can contribute in it without cloning their entire project locally.

P.S: where should I ask the doubt asking here seems hectic to me.

**Comment by prathimacode-hub** [comment]
You can connect with me through social media handles. Great, but changes are being addressed to be done in your earlier PR. Once PR gets approved, you can start working on this. Insteading of cloning it, you can individually download the respective files or folders by selecting download option directly. @Vaibhav-Vipin

**Comment by prathimacode-hub** [comment]
You can now work on this issue, it's assigned to you. @Vaibhav-Vipin

**Comment by Debashish-hub** [comment]
Hey! @Vaibhav-Vipin Any updates?
