### ISSUE TITLE
HTML to markdown

### ISSUE THREAD

**Issue by tanvi355** [prathimacode-hub/Awesome_Python_Scripts#548]
---
Title: HTML to Markdown
About: CLI script
Name: Tanvi Bugdani
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Description: A script to convert HTML code into markdown format.

**Comment by Debashish-hub** [comment]
Please follow proper issue template @tanvi355

**Comment by tanvi355** [comment]
> Please follow proper issue template @tanvi355

I can't see ant template when I click on new issue
![image](https://user-images.githubusercontent.com/56465105/123645998-70fdf780-d844-11eb-9493-c715fd5167e6.png)

**Comment by Debashish-hub** [comment]
https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/.github/issue_template
Find it here.

**Comment by prathimacode-hub** [comment]
Issue is assigned to you. You can proceed. @tanvi355
