### ISSUE TITLE
Text to PDF

### ISSUE THREAD

**Issue by tanvi355** [prathimacode-hub/Awesome_Python_Scripts#549]
---
Title: Text to PDF
About: CLI script
Name: Tanvi Bugdani
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Description:
A script to convert a given text file to pdf and save it.

**Comment by prathimacode-hub** [comment]
This is already done. And also an issue is assigned to you already. You can work on only 1 issue at a time. @tanvi355
