### ISSUE TITLE
Rock Paper Scissors game

### ISSUE THREAD

**Issue by Harshitha-246** [prathimacode-hub/Awesome_Python_Scripts#55]
Hello mam,
I would like to create rock paper scissor game using python. The user can play with the computer or with another user from the same device. 
please assign this to me.
I am a participant of LGM-SOC21

**Comment by prathimacode-hub** [comment]
Rock Paper Scissor is already included in the repo. While raising issue, you got to check whether the project is available or not so that your efforts don't go wasted. @Harshitha-246

**Comment by Harshitha-246** [comment]
oh ok mam. thank you mam.
