### ISSUE TITLE
Solar System Planets Info

### ISSUE THREAD

**Issue by Aditya8821** [prathimacode-hub/Awesome_Python_Scripts#550]
Title: Solar System Planets Information
About: Implementation of this script is done by using a module like Pillow and Tkinter. Many useful functions of Tkinter and pillow are used to create this project.
Name: Aditya Trivedi
Label: Feature Request
Assignee: ''

Define You:

-[x] LGM-SOC'21 Participant
-[x] Contributor
I'll write a Python script that will display a picture of that particular planet along with some information about the planet and at the bottom, there will be a fun fact about the particular planet.  On the top there present a list of planets from where you can choose the planets as per your choice.

**Comment by Debashish-hub** [comment]
Is it similar to #527 @Aditya8821

**Comment by Aditya8821** [comment]
Yes sir but it have different interface

**Comment by prathimacode-hub** [comment]
Interface might be different, but concept is mostly same. It comes under which script? @Aditya8821

**Comment by Aditya8821** [comment]
Mam i have completed this only by the use of Tkinter itself so it will fall under GUI.

**Comment by prathimacode-hub** [comment]
> Mam i have completed this only by the use of Tkinter itself so it will fall under GUI.

But, we already have a similar script under GUI. It's better you take up an another issue to work on. @Aditya8821
