### ISSUE TITLE
Nobel Prize Winner

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#553]
---
Title: Nobel Prize Winner
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will create an application that will allow user to get the details about the nobel prize winner from the past years 100 years.

the details will be like
in which category they won,
birth place,
birth date, 
their resident,
their role,
recognition for that prize

**Comment by akash435** [comment]
@prathimacode-hub ,please assign this to me under LGM SOC, will add this under GUIScripts.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
