### ISSUE TITLE
Programming Keyboard

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#555]
---
Title: Programming Keyboard
About: It's a GUI script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this script,
will try to create a programming keyboard in which we will embed keys for
print
int
char
string

and many other keys are are keywords in Programming language.

It will work like this, when we click on print key, it will write "print", when we click on int key, it will print "int",
So using this Programming Keyboard we don't need to write much, most works will be done by keyboard

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
This looks like your earlier PR. @akash435

**Comment by akash435** [comment]
ok then, is it okay if i will enhance it, with some programming keywords keys?

**Comment by prathimacode-hub** [comment]
> ok then, is it okay if i will enhance it, with some programming keywords keys?

Ok, you can work as enhancement, but don't u think, u need to do some changes in your issue template?

**Comment by akash435** [comment]
yes, sorry, i have updated now.

**Comment by prathimacode-hub** [comment]
Sure, issue assigned as an enhancement. @akash435

**Comment by prathimacode-hub** [comment]
As you are adding it as an enhancement, you can merge your changes together for this project. But Add up a separate "README_enhancement.md" for the changes you had done in this PR. @akash435

**Comment by akash435** [comment]
ok mam
