### ISSUE TITLE
Top Movie GUI

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#556]
---
Title: Top Movie List GUI
About: Building a GUI to get top movies
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, This project is based on a python script.

**Describe the solution you'd like...**

Using the module we can built a GUI app to get the top movies using the module called IMDbPY

**Comment by prathimacode-hub** [comment]
Yes, you can proceed only if it is a GUI script. Bcoz we have similar script in API section. Are you sure, it's GUI? @rammya29

**Comment by rammya29** [comment]
Yes, it is based on GUI

**Comment by prathimacode-hub** [comment]
Issue assigned. @rammya29
