### ISSUE TITLE
Next Word Prediction

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#558]
Title: Next Word Prediction
About: Here we will predict the next word with the use of our database .
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description: Here we will predict the next word as per our data that is available with us using numpy library. Here there is one requirement is that we need a collection of data for prediction.

**Comment by prathimacode-hub** [comment]
Issue assigned. @neelshah2409
