### ISSUE TITLE
API Script

### ISSUE THREAD

**Issue by Bhuvanaa28** [prathimacode-hub/Awesome_Python_Scripts#56]
# API Script - OMDB Api
Title	  |   About   |	Name   |	Label   |	Assignee
------ | ---------- | ---------- | -------- | -------------
OMDB Api | In this project, information about a movie <br> is obtained upon request by the user via the API | Bhuvanaa28 |Feature Request
- [x] LGM-SOC'21 participant

The solution I would like to follow is to use the requests library to send requests to the API and obtain all information about the movie.

**Comment by prathimacode-hub** [comment]
Issues would be assigned on first come first serve basis from 12AM and describe the project with title. Also raise an issue using the template given. Have a good glance of README and CONTRIBUTING GUIDELINES of the project. I have as well attached an enclosed document with all the details pinned in the project channel of slack. @Bhuvanaa28

**Comment by prathimacode-hub** [comment]
Kindly do the same after 12AM and is it IMDB or OMDB? @Bhuvanaa28

**Comment by prathimacode-hub** [comment]
Ok, Do raise the same issue again. As this issue is opened 30mins ago, I can assign you through this. @Bhuvanaa28
