### ISSUE TITLE
To Do List - GUI

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#563]
---
Title: To-Do List
About: Build a GUI App where we can make a to-do list creation
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, This project is based on a python script.

**Describe the solution you'd like...**

To-do list app is created by sqlite and pyqt5

**Comment by prathimacode-hub** [comment]
Is it a notepad? @rammya29

**Comment by rammya29** [comment]
No mam, not a notepad. Its a kind of app where we can add task, delete task, save task etc...

**Comment by prathimacode-hub** [comment]
Ok, got it. You can proceed. @rammya29
