### ISSUE TITLE
Add a Python script for Quotes

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#566]
Title: Add a script for getting quotes using Python
Name: **Umesh Singh**
Label: Feature Request
Define You-
- [x] LGM-SOC'21 Participant
- [x] Contributor

Solution For Issue:
For this feature we need a python library for getting the quotes related to any author or person. And I will be adding a python script file for this feature and a readme file with some screenshots for showing it's working.

**Comment by prathimacode-hub** [comment]
You can proceed. @Umesh-01
