### ISSUE TITLE
Star  Pattern

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#567]
Title: Star
About: Through the python code I want to print this. Star under LGM-SoC 21
Name: Ashutosh Kumar Saw
Label: feature request
Assignee: ''

Define You :-
- [x] LGM-SOC'21 Participant 
- [x] Contributor
 
![Screenshot_2021-06-29-23-11-42-372_com android chrome~2](https://user-images.githubusercontent.com/60690692/123844093-3d989700-d930-11eb-9605-83270452a43c.jpg)

**Comment by prathimacode-hub** [comment]
Ok, you can proceed. @Ashu-1309
