### ISSUE TITLE
Scrabble using Python

### ISSUE THREAD

**Issue by NancyNegi23** [prathimacode-hub/Awesome_Python_Scripts#568]
Title: Scrabble
Name: Nancy negi
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Description**
I want to add this script under the BasicPythonScripts. It is game of Scrabble made using Python and a beginner friendly project.

**Comment by NancyNegi23** [comment]
@prathimacode-hub please assign me this issue under LGM-SOC'21

**Comment by Debashish-hub** [comment]
Please elaborate @NancyNegi23

**Comment by NancyNegi23** [comment]
It will be a two player game. A starting letter is given to the user and both the player enter a word with the same starting letter. According to a pre-defined score chart the score of each player is calculated and winner is announced. The letter which occur frequently in words like a, e, are of low value and letters like z, x, y are of higher value.

**Comment by Debashish-hub** [comment]
Sounds interesting! Issue is assigned to you @Debashish-hub
