### ISSUE TITLE
Add Password Generator Game.

### ISSUE THREAD

**Issue by tjanhvi** [prathimacode-hub/Awesome_Python_Scripts#569]
Title: Password generator game using python
About: Add a BasicPythonScripts to implement Password generator game

Name: Janhvi Tiwari
Label: Feature Request
Assignee: "

Define You:
LGM-SOC'21 Participant

Solution:
It will be a BasicPythonScripts in which the user can able to generate a password and also able to see whether the password is easy level or hard level password.

![image](https://user-images.githubusercontent.com/78703730/123856107-527c2700-d93e-11eb-8e25-11b29d9e45e0.png)

**Comment by Debashish-hub** [comment]
Issue is assigned to you @tjanhvi
