### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by Harshitha-246** [prathimacode-hub/Awesome_Python_Scripts#57]
Hello mam,
I would like to create hangman  game.
please assign this to me.
I am a participant of LGM-SOC21.

**Comment by prathimacode-hub** [comment]
I have mentioned all the details of how to get an issue assigned to you in enclosed document I have pinned to the project channel in slack. Do check it out. Any assignment would start on FCFS basis after 12AM. That's when you got to raise your issue and express your interest. @Harshitha-246
