### ISSUE TITLE
Odd Symbol Find Game

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#570]
---
Title: Odd Symbol Find Game
About: It's a Pygames script 
Name: Akash Ramanand Rajak
Label: feature request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

In this game, 
there will be 5 levels,
for each level there will be a matrix given of different size for different level, 
and each cell in the matrix will be having same symbol, except one cell which will have different symbol

for each level player needs to find the place in terms of x and y, where that different symbol is present.

**Comment by akash435** [comment]
@prathimacode-hub ,please assign this to me under LGM SOC< will add this under Pygames Scripts.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
