### ISSUE TITLE
Password Manager

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#572]
Title: Password Manager
About: it will store the passwords of different account very securely like that of browsers.
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description:
Here we will make a much secure password manager using fernet library .We will make a key first for the user using fernet and then we will ask him for the account and password for that and it will be stored in password text file in encrypted form , so even if someone sees our password text file then also he will not be able to find password.
Here we are making the security of passwords much stronger.
In chrome how all the passwords of different accounts can be saved ,similarly we created a secure environment using fernet.

**Comment by prathimacode-hub** [comment]
Sure, you can go ahead. @neelshah2409
