### ISSUE TITLE
Apple Store

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#574]
---
Title:  Apple Store
About: I designed a full stack web application which is an online apple store using Flask in Python and SQLAlchemy. Where the information of different prodducts are displayed. Where the customer can buy or sell products. The product informations have to be inserted manually with SQLAlchemy queries the structure to which is already there in this program
---

Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Is your feature request related to a problem? Please describe.

Web application to reduce visit to physical stores

Describe the solution you'd like...

I will use flask and SQLAlchemy in python scripts for this project which would do the necessary tasks.

Describe alternatives you've considered?

N.A

**Comment by prathimacode-hub** [comment]
That's interesting project. You can proceed. @kumarjeetray
