### ISSUE TITLE
Marksheet - GUI

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#575]
---
Title: Marksheet - GUI
About: It a GUI Application, where mark sheets can be created easily.
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, This one is related to python scripts using Tkinter module

**Describe the solution you'd like...**

I would like to use Tkinter to create the mark sheet application

**Comment by Debashish-hub** [comment]
Issue is assigned to you @rammya29

**Comment by Debashish-hub** [comment]
Hey! @rammya29 Any update?

**Comment by rammya29** [comment]
Actually, I done with project, but I am getting error while creating PR. I will find a solution to do that. Since my exam are going Sorry for delay.

**Comment by Debashish-hub** [comment]
> Actually, I done with project, but I am getting error while creating PR. I will find a solution to do that. Since my exam are going Sorry for delay.

Feel free to reach out to us, if you need any help!

**Comment by rammya29** [comment]
Since my last pull request has some merge conflict and I can't create the new pull request too.

**Comment by prathimacode-hub** [comment]
I shall do one thing, I shall close that PR. Delete up the forked repository, and refork it again. You can do this. This time , try with this project PR. Let's check. @rammya29

**Comment by prathimacode-hub** [comment]
Don't let 2 of your PR'S go wasted. Raise PR once again, first delete the forked repository from your profile. Refork it again. And push it to the PR again. One issue after the other.  Since README is conflicting. Create a new README file and add the documentation there. @rammya29

**Comment by rammya29** [comment]
Okay mam. I will work in that today

**Comment by prathimacode-hub** [comment]
All the best, hope this clicks now. @rammya29
