### ISSUE TITLE
Image_Steganography

### ISSUE THREAD

**Issue by skimran2000** [prathimacode-hub/Awesome_Python_Scripts#58]
---
Title: Image Steganography
About: Hiding secret data like messages in an image before sending
Name: Shaik Imranuddin
Label: Image Processing Script
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

I have talked regarding this with @prathimacode-hub in issue #54 

**Describe the solution you'd like...**

I have first converted the secret message into 8-bit binary data and then used PIL module of python to extract pixels of image and modify it into 8-bit binary data so that I could store the secret message with it.  The value is made odd if 1 occurs and even if 0 occurs.

**Comment by prathimacode-hub** [comment]
This is a wonderful add-on project. I had assigned this issue to you. @skimran2000
