### ISSUE TITLE
Word Search Game

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#586]
---
Title: Word Search Game
About: It's a Pygames script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a Word Search Game,
In this game there will be no. of levels and for each level there will be given a board in form of matrix, in which each cell will have an English alphabet and a word will be given.

for each level the player need to select either YES (means word is present in that board) or NO (if not present),

Also in board, the word can be in ant order, like horizontally, vertically, or in any diagonal
That word can be present in reverse order also.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC, will add this game under Pygames script

**Comment by prathimacode-hub** [comment]
You can proceed. @akash435
