### ISSUE TITLE
All Camera Model Detailer 

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#588]
---
Title: All Camera Model Detailer 
About: It's a GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

In this application the user will be able to find the details about about 1000 different types of cameras.
The details will be in terms of :
Release date
Max resolution
Low resolution
Effective pixels
Zoom wide (W)
Zoom tele (T)
Normal focus range
Macro focus range
Storage included
Weight (inc. batteries)
Dimensions
Price

The use just need to select the camera Model and the script will show all the above mentioned details about that camera model.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC, will add this under GUI scripts.

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @akash435
