### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by ASLManasa** [prathimacode-hub/Awesome_Python_Scripts#589]
I am LGM SoC21 participant. I want to create a calendar that gives the dates according to the year entered. Kindly assign me this issue.Thanks

**Comment by prathimacode-hub** [comment]
This issue is already done, And also follow the template given while raising an issue or PR. You can come with new issue and before that make sure it's not available in the repo. @ASLManasa

**Comment by ASLManasa** [comment]
ok Thanks.  I will make sure to check next time.@prathimacode-hub
