### ISSUE TITLE
Movie API Script

### ISSUE THREAD

**Issue by Bhuvanaa28** [prathimacode-hub/Awesome_Python_Scripts#59]
# API Script - OMDB Api
Title	  |   About   |	Name   |	Label   |	Assignee
------ | ---------- | ---------- | -------- | -------------
OMDB Api | In this project, information about a movie <br> is obtained upon request by the user via the API | Bhuvanaa28 |Feature Request
- [x] LGM-SOC'21 participant

The solution I would like to follow is to use the requests library to send requests to the API and obtain all information about the movie.

**Comment by Bhuvanaa28** [comment]
> Great, this is a Movie API script. I had assigned it to you. @Bhuvanaa28

Thank you Mam, will start working on it right away !

**Comment by prathimacode-hub** [comment]
Sure, go ahead. All the best. I shall hit to the bed. @Bhuvanaa28  👍
