### ISSUE TITLE
Chrome Dinosaur Automation

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#595]
Title: Chrome Dinosaur Automation
About: It's a script where we will automate the browser game .
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:
- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
 - [ ] Contributor

Description:
As we all face some sort of problem with internet sometime so the best way for time pass is dino game.so here we will automate the dino game using pyautogui ,pil and time .the score goes on increasing until we stop the program to run.

**Comment by prathimacode-hub** [comment]
Oh, interesting. Just had a small play on it yesterday. @neelshah2409
