### ISSUE TITLE
All Laptop Detailer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#598]
---
Title: All Laptop Detailer
About: It's a GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,
In this application user can get the details about more than 1300 different laptops,

for each laptop the details will be in terms of 
Company Name
Product Name
Laptop Type
Screen Inches
Screen Resolution
CPU Model
RAM Characteristics
Memory
GPU Characteristics
Operating System
Laptop's Weight
Laptop's Price

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC, will add this under GUIScript.

**Comment by prathimacode-hub** [comment]
Haha, again a detailer script? @akash435

**Comment by akash435** [comment]
you mean i should not do this?

**Comment by prathimacode-hub** [comment]
Nope, that's totally your choice. @akash435
