### ISSUE TITLE
Learning Github

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#6]

**Comment by prathimacode-hub** [comment]
Process to follow 👍 

1. Fork the repository. You are now in your profile repositories
2. You can see a "Add File" option in the local repository
3. You can add files or folders using the 2options given
4. Create new file option helps in creating both file and sub repository within this repository.
    Example : You want to add up your JumpingNumber Script to the repository
    Select "create a new file" option, it opens up like this - /Awesome_Python_Scripts
    To add up your repository and file you do :  /Awesome_Python_Scripts/JumpingNumber/README.md
    This add up would not only add JumpingNumber as repository but also adds a empty README.md file.
    You can add your README content in README.md file and commit the changes
5. Now you have created a repository of your desired script, you are yet to add your python program
6. From the very same "Add File" option, select "Upload files" and add your python program from your local drive of your system.
7. Make sure the script file name is Jumping_Number.py before you upload the file to this repository
8. You have successfully added up your required files needed.
9. Now select "Contribute" option above and select Open Pull request, and add a defined title, a commit message in a description.
10. Finally, create a pull request option to synchronize your fork to the committed repository. You are done.
11. Congrats, on learning how to create a PR in a easier way. No much fuss around to deal with.
12. PR can be created without the use of command line terminal, but preferrably that way to show professionalism.
13. Contribution is all that matters, so start contributing and feel free to do more PR in future. 

@sonaliBedade, I like your confidence and enthusiasm to learn. Keep going. 
If you found this helpful and easier to try, you can do create the PR of the same script with required changes I have mentioned in this comment. 

Looking forward to merge the upcoming PR from you. Thank You.

**Comment by prathimacode-hub** [comment]
Proud of you @sonaliBedade for your dedication. Kudos. As issue has been addressed, I shall close this issue. I hope you're now familiar with PR and GitHub Workflow. ✨😎
