### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by Harshitha-246** [prathimacode-hub/Awesome_Python_Scripts#60]
Title        |      About                                                   |  Name                |  Label                 |    Assignee  |
------------|----------------------------------------------|-------------------|-------------------|--------------|
Hangman  | using a list of words we randomly     select a word and make the user guess it          |              Harshitha-246 | Feature Request |
-----------------------------------------

Define you:
                    
- [x]  LGM- SOC'21 Participant
- [ ]    Contributor

I have talked regarding this with @prathimacode-hub in issue#57

Describe the solution you'd like...
create a list of words. randomly select a word from the list and get the the character from the user one by one and check it against the word. Then reduce the turns if it is wrong and eventually declare win or loose.

**Comment by prathimacode-hub** [comment]
Wonderful game to get engaged. I had assigned this issue to you. @Harshitha-246

**Comment by Harshitha-246** [comment]
thank you mam. Will start working on it.
