### ISSUE TITLE
Image Here To There

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#602]
---
Title: Image Here To There
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,
In this application user can select any image from anywhere from the local system and save it to another place in our local system with any file name of our choice.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub ,please assign this to me under LGM SOC.
Can you please also confirm it's goes under imageprocessing script or not?

**Comment by prathimacode-hub** [comment]
Yeah, it can go under it. Can you elaborate your issue more? @akash435

**Comment by akash435** [comment]
In the application window, there will be a SELECT button, using which user can select image from local system.

After that there will also be SAVE button, clicking on which user can save that file anywhere in the local system.

Also will try to preview the image selected by the user.

for this will be using cv2 library.

**Comment by prathimacode-hub** [comment]
Ok, you can proceed. @akash435
