### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#606]
---
Title: Text Editor
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an simple text editor using tkinter GUI,
In this application user have different option like
write anything
redo 
undo
cut 
copy
paste
can also find some text
save the open
open existing file

and many more options.

**Comment by akash435** [comment]
@prathimacode-hub , @Debashish-hub , please assign this to me under LGM SOC.
I searched for this but couldn't find anything similar to this, can you please tell if it is similar to existing one.

**Comment by Debashish-hub** [comment]
Is it similar to #237 @akash435

**Comment by akash435** [comment]
No in this Notes Panel, user can only write, but here i am going to create text editor kind thing.

like this
![1](https://user-images.githubusercontent.com/57003737/124217734-7d20d800-db16-11eb-8807-d5b3da9609cf.jpg)

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
