### ISSUE TITLE
Image Displayer GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#609]
Title: Image Displayer GUI
About: It's a  gui script where we can display all the images of our device.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
 - [ ] Contributor

Here we will use kivy for displaying the image , we firstly set the design of the preview screen and then we will redirect to devices file and then selected image will be displayed on the screen.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @neelshah2409
