### ISSUE TITLE
Movie Booking Application

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#612]
---
Title: Movie Booking Application
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an movie booking application using tkinter GUI,
In this application first we will ask user about type of movie like horror, romance, thriller, etc.
Also will ask user to select the name of the movie

Then will give choice to user to select the time at which he/she want to watch movie 

And will try to add the option to select the seat position in theatre
If that position is not booked previously, then will book then else notify user to select other seats

**Comment by akash435** [comment]
@prathimacode-hub , @Debashish-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
