### ISSUE TITLE
Indian Flag

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#613]
Title:  Indian Flag 
About: Through the python code I want to print this. Star under LGM-SoC 21
Name: Ashutosh Kumar Saw
Label: feature request
Assignee: ''

Define You :-
- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
You can proceed. @Ashu-1309
