### ISSUE TITLE
Design using python(turtle project)

### ISSUE THREAD

**Issue by tjanhvi** [prathimacode-hub/Awesome_Python_Scripts#616]
Title: Design using python(turtle project)
About: Through the python code I want to print a design in image processing script under LGM-SoC 21
Name: Janhvi Tiwari
Label: feature request
Assignee: ''

Define You:-

 LGM-SOC'21 Participant
 Contributor

**Comment by prathimacode-hub** [comment]
What's the design? @tjanhvi

**Comment by tjanhvi** [comment]
> What's the design? @tjanhvi

![image](https://user-images.githubusercontent.com/78703730/124361325-29b0a600-dc4c-11eb-9bf3-3b817a67ebe2.png)

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by prathimacode-hub** [comment]
This is already done. Kindly take up an another issue and also make sure the script is not in the repo. @tjanhvi
