### ISSUE TITLE
Weather Updates for further 5 days

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#617]
---
Title: Weather Updates for 5 days
About: API Script Project
Name: Pooja S Deshpande
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

About:
In this project, I will use Meta Weather API to get weather updates for today plus next 5 days.
Will be mostly implemented in GUI format for clean presentation of response from API.
Reference for API: [Meta Weather API](https://www.metaweather.com/)

**Comment by prathimacode-hub** [comment]
This script has already been done using API. @cybot-des

**Comment by cybot-des** [comment]
Okay Maam
