### ISSUE TITLE
Restaurant Management System

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#618]
---
Title: Restaurant Management System
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an Restaurant Management application using tkinter GUI,

in this we will add option to select different meals and will show the price for each meals also,

user can select any meals and also in any number, and will calculate the final price for the food

while calculating the price, will add the GST system
And will try to print the final receipt

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
You can proceed. @akash435
