### ISSUE TITLE
Want to add Rock-paper-scissior game

### ISSUE THREAD

**Issue by archismansaha** [prathimacode-hub/Awesome_Python_Scripts#62]
I am LGM-SOC participant  I want to add Rock-paper-scissor game which uses random py module.

**Comment by prathimacode-hub** [comment]
First thing, this script is already added up in the repository. You can take some other issue. And one more thing kindly follow the template given to get issues assigned. Stone-Paper-Scissor (or) Rock-Paper-Scissor both games are same. @archismansaha

**Comment by archismansaha** [comment]
Ohk mam , and from where I will get that template??

**Comment by prathimacode-hub** [comment]
All the best @archismansaha

**Comment by prathimacode-hub** [comment]
I shall close this issue, as this is invalid. You can raise a new issue. How is your learning journey? @archismansaha

**Comment by archismansaha** [comment]
Yes mam.. It's going good learning more things to build a good project 🙂

**Comment by prathimacode-hub** [comment]
Great going @archismansaha
