### ISSUE TITLE
Camera Application

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#620]
---
Title: Camera Application
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a simple Camera  application using tkinter GUI and OpenCV library,

In this on the main window a camera will open using OpenCV and will create an option to take the shot of an image 

After taking the image will ask the the user to save it in any location in local system.

And will also try to preview the image shot taken by the user.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC, will add this Camera Application in ImageProcessing Scripts.

**Comment by Debashish-hub** [comment]
Issue is assigned to you @akash435
