### ISSUE TITLE
Music Player GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#621]
Title: Music Player GUI
About: To make a music player for the downloaded music on device just like mp3 player
Name: Neel Shah
Label: feature request
Assignee: ''

Define You :-
- [x] LGM-SOC'21 Participant
 - [ ] Contributor

Here we will use tkinter for making the gui where there will be play , pause , stop and resume buttons which will be functioning through pygame functions and for selecting the music from device we use os and once the music is selected it will start playing.

**Comment by Debashish-hub** [comment]
It must be similar to #282 @neelshah2409

**Comment by neelshah2409** [comment]
> It must be similar to #282 @neelshah2409

Okay sir my bad .
