### ISSUE TITLE
Gesture Pet (Fun Game GUI)

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#622]
Title: Gesture Pet 
About: To make a emoji like pet which will show different reactions on click on it
Name: Neel Shah
Label: feature request
Assignee: ''

Define You :-

- [x] LGM-SOC'21 Participant
- [ ]  Contributor

Here using tkinter we will make a emoji kind of pet which will show different reactions on click of the cursor.
->When we place cursor on it , it will show happy face.
->When we double click on it ,it will show tongue.
->when we will ignore the pet for a while then it will show sad face.

**Comment by prathimacode-hub** [comment]
Ok, you can proceed. @neelshah2409
