### ISSUE TITLE
Bounce Ball Game

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#624]
---
Title: Bounce Ball Game
About: It's an Pygame script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a simple Bouncing ball game in tkinter GUI,

In this we will be having a bouncing ball and a rectangle bouncer , the ball keeps on bouncing in any direction and player needs to prevent the ball from falling down using the rectangular bouncer.

When player fails to prevent ball from falling, game will over.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SCO.

**Comment by prathimacode-hub** [comment]
This is already done. @akash435

**Comment by akash435** [comment]
ok, sorry, then you can close it.
