### ISSUE TITLE
Piano Application

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#626]
---
Title: Piano Application
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a Piano application using tkinter GUI,

In this we will created Piano button in black and white colour alternatively, and will embed different piano sound in each button

And for playing sound will be using Playsound library in python.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
