### ISSUE TITLE
Google Search Engine

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#628]
---
Title: Google Search Engine
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a Google Search Engine kind of GUI using tkinter GUI,

And for implementing google things will user googlesearch library in python.

Will be adding all the options that is in normal google search gui, like,
Apps, 
Google Drive,
youtube, 
Gmail,
Images search,
sign in,
a search bar

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.
And can you please specify in which script it will go.

**Comment by prathimacode-hub** [comment]
Interesting, you can proceed. Obviously it would go under 'GUIScripts'. @akash435
