### ISSUE TITLE
Text File To PDF

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#629]
Title: Text File To PDF
About: To convert text file to pdf using fpdf library
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:-

- [x] LGM-SOC'21 Participant
- [ ] Contributor

For converting text file to pdf we need to go to chrome or google and do that so why not our script do that for us.
Here we will use fpdf library and firstly read the text file and then will make a pdf of it in the same folder , here the text size of pdf can be changed by us.

**Comment by neelshah2409** [comment]
@prathimacode-hub @Debashish-hub please see this issue and assign me.

**Comment by prathimacode-hub** [comment]
It's already taken. @neelshah2409
