### ISSUE TITLE
What's your story?

### ISSUE THREAD

**Issue by tanvidaware17** [prathimacode-hub/Awesome_Python_Scripts#63]
---
| Title  | About | Name | Label | Assignee |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| What's your story? | On the basis of user's inputs a story full of fun and madness will be generated.  | Tanvi Daware | Feature Request | 
---

- [x] LGM-SOC'21 Participant 

**Approach to be followed :**
The user will be asked for their name, pronoun, favourite place, food, activity and some more choices as input. Then a story will be build based on that data. The template of the story will be almost the same but it will  vary a bit according to the user's input.

**Comment by prathimacode-hub** [comment]
This is kinda new and unique script. Good selection of an issue. I had assigned this issue. Go ahead. @tanvidaware17
