### ISSUE TITLE
Reddit Video Downloader

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/Awesome_Python_Scripts#631]
Title: Reddit Video Downloader
About: Add a python script which takes post URL and gives video as mp4 file. 

Name: Akash Jain 
Label: Feature Request
Assignee: "

Define You:

LGM-SOC'21 Participant
Contributor
Solution:
It will be a python script which scrapes data from reddit post url and display reddit post title, subreddit and author in the console and provides video as mp4 file in your local system.

**Comment by Akash20x** [comment]
@prathimacode-hub
Please assign me this issue as a part of LGM-SOC'21

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @Akash20x

**Comment by Akash20x** [comment]
@prathimacode-hub Please check my pull request
