### ISSUE TITLE
Taxi Hire Application

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#634]
---
Title: Taxi Hire Application
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a Taxi hiring application using tkinter GUI,

In this first will ask user to create an account in application ,or already had an account then option to login,
for this login and creating account process will be using sqlite3 data base, and store the user information in it

After logging in the main application , will open the main application of hiring in which will ask user to enter details like,
name, address, postal code, mobile no. , email, pickup address, drop address, 

will try to add option for asking user to go single or with special needs, and will add the prices for each.

Ans at last will create final receipt of his/her route.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
