### ISSUE TITLE
Next Episode Fetcher ( Web Scrapping)(TV Series)

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#635]
Title: Next Episode Fetcher
About: To get the date and time of next episode of tv series/serials
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:-

- [x] LGM-SOC'21 Participant
- [ ]  Contributor

## Description:
Here using tkinter we will make gui where we will ask for series name and that name we will found on the url using requests and using bs4 we will fetch the output in proper format.

**Comment by prathimacode-hub** [comment]
Issue is assigned. You can start working. @neelshah2409
