### ISSUE TITLE
Dice simulator

### ISSUE THREAD

**Issue by girija0707** [prathimacode-hub/Awesome_Python_Scripts#636]
About-It is a basic dice simulator using random module in python
Name-Girija Gupte
Label: Feature Request

Define You:

[x] LGM-SOC'21 Participant
Contributor
Describe the solution: I would write a python script for this app

**Comment by girija0707** [comment]
please assign this under lgmsoc

**Comment by Debashish-hub** [comment]
Isn't it similar to #396 @girija0707

**Comment by girija0707** [comment]
ok I will look for new issue

**Comment by Sakshi1007** [comment]
Atleast close the issues which are done so that it will be easy for us to choose
