### ISSUE TITLE
Simple Python IDE

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#638]
---
Title: Simple Python IDE
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an applicaton using tkinter GUI,

In this user will be given a textarea where user can write the python code

and using the run button , will show the output of that written in message box.

and is some error is there in the code, then will also try to show some error message.
for implementing this will be using StringIO library from io module.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
