### ISSUE TITLE
Phone Number Info

### ISSUE THREAD

**Issue by jigar-sable** [prathimacode-hub/Awesome_Python_Scripts#64]
---
| Title | About | Name | Label | Assignee |
|-------|-------|------|-------|----------|
| Phone Number Info  | Shows Country and the Service Provider of any phone number. | Jigar | Feature Request  |

---

Define You:

- [x] LGM-SOC'21 Participant

**Describe the solution you'd like...**
I'll use phonenumbers module to create this project. As the user enters the phone number the output will be shown with Country of that number which is access through geocoder and Service Provider which will be access through carrier name through the module.

**Additional context**

![image](https://user-images.githubusercontent.com/64949957/121423638-1d5b6500-c98e-11eb-85b0-26942aeef9c3.png)
  **Sample Program**

**Comment by prathimacode-hub** [comment]
That's cool. But you had raised 2 issues. So let me know of the project you are interested to work on first. Since i could assign only 1 issue at a time. @jigar-sable

**Comment by jigar-sable** [comment]
> That's cool. But you had raised 2 issues. So let me know of the project you are interested to work on first. Since i could assign only 1 issue at a time. @jigar-sable

Thank you ma'am I'll work on Number Guess(#61) first and then for this issue..

**Comment by muskantayal123** [comment]
@prathimacode-hub  mam, i want to solve this issue please assign it to me.

**Comment by muskantayal123** [comment]
@prathimacode-hub since, no one is working on this issue so can i?

**Comment by jigar-sable** [comment]
@prathimacode-hub should I work on this issue now as #61 has been closed.
Please assign me for this issue.

**Comment by prathimacode-hub** [comment]
Yes, this issue is assigned to you. Go ahead. @jigar-sable

**Comment by jigar-sable** [comment]
Thank you
