### ISSUE TITLE
Billing System For Hotel 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#640]
Title: Billing System For Hotel
About: To make an easy billing system for hotel .
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:-
- [x] LGM-SOC'21 Participant
- [ ] Contributor

Here we will use tkinter to make a grid and then we will give different choices like panner tikka and all and at last we will give the total amount  and here we will also show the prices of all for conveniency of customer.

**Comment by prathimacode-hub** [comment]
Assigned. @neelshah2409
