### ISSUE TITLE
Hangman game in python

### ISSUE THREAD

**Issue by girija0707** [prathimacode-hub/Awesome_Python_Scripts#643]
Title: Hangman game in Python

Description:
Interesting game on guessing words which will also help to increase vocabulary

Name-Girija Gupte
Label: Feature Request

Define You:

[x] LGM-SOC'21 Participant
Contributor
Describe the solution: I would write a python script for this app

**Comment by Debashish-hub** [comment]
Sorry to say, but this one is also done. Check it once #60  @girija0707

**Comment by prathimacode-hub** [comment]
Before you create an issue, check in the repo if it's done. These are the common scripts which are finished long back. @girija0707
