### ISSUE TITLE
Enhanced Covid Cases Bot

### ISSUE THREAD

**Issue by DelionA** [prathimacode-hub/Awesome_Python_Scripts#644]
### Related Issue
- Info about the related issue
Closes: #166
- [x] Contributor
### Problem:

1. It was not possible to use the win10toaste module in linux (it is possible only for me).
![text](https://github.com/DelionA/Awesome_Python_Scripts/blob/feature/AutomationScripts/Covid%20Cases%20Bot/Images/screenshot2.png?raw=true)
2. This is not really a problem, but I want to be able to manage the waiting time and the number of iterations. 
![text](https://github.com/DelionA/Awesome_Python_Scripts/blob/feature/AutomationScripts/Covid%20Cases%20Bot/Images/screenshot3.png?raw=true)

### Type of change
What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)

### Describe the add-ons or changes you've made
1. Add module notify2, it is necessary to display notifications in nix systems.
2. Add module platform to determine the OS.
3. Added count and timeout variables for convenience.
4. Add module math for the possibility of continuous iteration.
5. Data printing in the console window is removed.

### Screenshot:

![Output](https://github.com/DelionA/Awesome_Python_Scripts/blob/feature/AutomationScripts/Covid%20Cases%20Bot/Images/screenshot_enhanced.png?raw=true)
Added functions:
- To work in windows 'covidbot_Windows'
![covidbot_Windows](https://github.com/DelionA/Awesome_Python_Scripts/blob/feature/AutomationScripts/Covid%20Cases%20Bot/Images/screenshot5.png?raw=true)
- To work in Linux 'covidbot_Linux'
![covidbot_Linux](https://github.com/DelionA/Awesome_Python_Scripts/blob/feature/AutomationScripts/Covid%20Cases%20Bot/Images/scrennshot6.png?raw=true)
For continuous operation, the covidbot function is called by the count=math.inf parameter
![math.inf](https://github.com/DelionA/Awesome_Python_Scripts/blob/feature/AutomationScripts/Covid%20Cases%20Bot/Images/screenshot4.png?raw=true)

**Comment by prathimacode-hub** [comment]
Still your template is not right. Are you a LGMSOC participant? How would i know if u r one or not? @DelionA

**Comment by DelionA** [comment]
no, i'm not a LGMSOC participant.
maybe I need to offer my own idea to start with.
right?

**Comment by prathimacode-hub** [comment]
Ok, cool. If you provide the details earlier, it would have been much easier. Don't worry, you can still contribute. Kindly go through the project structure followed. And do the changes to your PR accordingly. But for the changes you do, there should be separate "README_enhanced.md" file which describes the work youd had done as it's an enhancement to the existing project. Don't do any changes to the existing ones in the project, except the project file. Other files, you just have t add the things used in your work. Libraries should be added in "requirements.txt" file. "Images" folder should have the screenshot of images of work you had done. Hope, this answer provided you with the clarity. @DelionA

**Comment by DelionA** [comment]
ok.thanks.

**Comment by prathimacode-hub** [comment]
Why did you close the issue? You should never close an issue or PR from your end. You didn't respond yet as well. @DelionA

**Comment by DelionA** [comment]
> Why did you close the issue? You should never close an issue or PR from your end. You didn't respond yet as well. @DelionA
I closed it because, first, I will offer my project for consideration. I didn't have any more questions, why keep it open?
or is it impossible? 
is it too bad that I closed the issue?

**Comment by prathimacode-hub** [comment]
You shouldn't close the issue. Are you working on this or not you haven't said anything about it? @DelionA

**Comment by DelionA** [comment]
Yes, I would like to work on this project.
Sorry that I do not have enough experience and knowledge of the correct design. 
I have a few questions for you:
- is it possible to create a separate folder 'enhanced', and place files in it?
- or create only README_enhanced.md and describe all the actions in it? and do not change the project files themselves?
- or can I change the project file itself?

**Comment by DelionA** [comment]
@prathimacode-hub
The changes have been made.
What do i need to do next?

**Comment by prathimacode-hub** [comment]
I will show you 1 sample of how they had worked on existing project. Here it is : [Project](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/BasicPythonScripts/Alarm%20Clock). This project is enhanced, you can check it here and follow the same. Also the changes, I had said earlier. Only extra file that gets added along with the project is "README_enhanced.md". Other files would be same, except the project file you had changed. For your extra add-ons, if there is something to add you would add up in "requirements.txt" and output screenshot or media in "Images" folder. Also there is a README template to follow. Any more doubts, feel free to ask. Else raise a PR. with the changes mentioned above. @DelionA

**Comment by prathimacode-hub** [comment]
No worries, I am here to help out. It happens with everyone and no contribution is small. @DelionA

**Comment by DelionA** [comment]
#641

**Comment by DelionA** [comment]
@prathimacode-hub
Thank you for accepting my PR.
I edited the Issue.
How can I leave a video?
Who should close the Issue?

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub
> Thank you for accepting my PR.
> I edited the Issue.
> In what form can I leave it?
> Who should close the Issue?

Great, you can leave your mail id here. I shall delete up your mail once I take a note of it. Actually if followed right and PR is merged, issue closes automatically, Else, I can close it. Might not have read the issue number correctly over PR.  So don't worry about that. Most Welcome. @DelionA

**Comment by DelionA** [comment]
> > @prathimacode-hub
> > Thank you for accepting my PR.
> > I edited the Issue.
> > In what form can I leave it?
> > Who should close the Issue?
> 
> Great, you can leave your mail id here. I shall delete up your mail once I take a note of it. Actually if followed right and PR is merged, issue closes automatically, Else, I can close it. Might not have read the issue number correctly over PR. So don't worry about that. Most Welcome. @DelionA
@prathimacode-hub
Thanks.
I have gained invaluable experience.
My email is:
Marko-140210@yandex.ru

**Comment by prathimacode-hub** [comment]
Glad you felt so. I highly appreciate your work. Great going. Keep contributing. @DelionA 🙌🤩
