### ISSUE TITLE
Mouse Pointer Co-ordinates Getter

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#646]
---
Title: Mouse Pointer Co-ordinated Getter
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

This application will provide us the where is our current mouse pointer on the computer screen.

It will give the coordinate of mouse pointer in terms of x and y values.

when we move the cursor arrow using mouse, the co-ordinates the arrow will also change accordingly and can get the coordinate of any position of mouse cursor on screen.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
