### ISSUE TITLE
Saying I love you in python

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#648]
---
Title: I love You in python
About: my project will write I love you in python
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Describe the solution you'd like...**
I will be using python @prathimacode-hub mam.

**Comment by prathimacode-hub** [comment]
Issue assigned. @manognyaa
