### ISSUE TITLE
Unit Converter GUI

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#649]
Title: Unit Converter GUI
About: To make unit conversion here we will convert kg to gram , ounce and pound.
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:-

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Here using tkinter we will make a gui and then we will ask the user to give weight in kg and then it will show it in gram , pound and ounce. We can change the given units as per our requirement and  we just need to change the units in our script.

**Comment by prathimacode-hub** [comment]
Issue assigned. @neelshah2409
