### ISSUE TITLE
Add sudoku game

### ISSUE THREAD

**Issue by pragyakhanna11** [prathimacode-hub/Awesome_Python_Scripts#65]
Title | About | Name |Label | Assignee | 
--- | --- | --- | --- |--- 
Sudoku game| A classic game of sudoku made using pygames | Pragya Khanna | Feature Request|  | 

- [x] LGM SOC participant

**Describe the solution you would like:**
I will use pygame module to make this project and make the classic sudoku game.

**Comment by prathimacode-hub** [comment]
It's my fav game, But you had raised 2 issues other one being twitter API. Can you select the issue, you want to work on first. As only 1 issue can be assigned at a time. @pragyakhanna11

**Comment by pragyakhanna11** [comment]
> It's my fav game, But you had raised 2 issues other one being twitter API. Can you select the issue, you want to work on first. As only 1 issue can be assigned at a time. @pragyakhanna11

I'll work on the twitter API first then

**Comment by pragyakhanna11** [comment]
Please assign me this issue now

**Comment by suvrashaw** [comment]
Title: Sudoku Game
About: I want to create a Sudoku Game using python modules.
Name: Suvra Shaw
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description: Would love to create a PyGame module script with a basic UI to play Sudoku.

Please assign me this issue, ma'am.

**Comment by prathimacode-hub** [comment]
Yes, But raise a new issue stating the same using this template. Your message here won't count as this issue is raised by other person. @suvrashaw

**Comment by pragyakhanna11** [comment]
> Yes, But raise a new issue stating the same using this template. Your message here won't count as this issue is raised by other person. @suvrashaw

@prathimacode-hub So this issue won't be assigned to me?

**Comment by prathimacode-hub** [comment]
Ok, sorry. I didn't notice your message earlier. Yes, you will be assigned this issue. @pragyakhanna11.

@suvrashaw  Raise a new issue on other script you would like to work on. This issue is assigned on first come, first serve basis.

**Comment by suvrashaw** [comment]
> Ok, sorry. I didn't notice your message earlier. Yes, you will be assigned this issue. @pragyakhanna11.
> 
> @suvrashaw Raise a new issue on other script you would like to work on. This issue is assigned on first come, first serve basis.

Sure.
