### ISSUE TITLE
Nutritional Calorie Recorder

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#651]
---
Title: Nutritional Calorie Recorder
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

this application will make the record of the calories consumed by a particular person.
All the data for the amount of calorie consumed and which calories consumed will be stored in the sqlite3 database.

In this whenever user take some calories he just need to select that name of the items consumed and it will directly get recorded and stored in the database.

And will show how much amount of calorie consumed till date.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
