### ISSUE TITLE
Sorting Visualizer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#654]
---
Title: Sorting Visualizer
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

In this we will generate a random array , and will visualize the sorting algorithms like bubble sort, selection  sort and insertion sort.

for visualizing the sorting of array will use matplotlib library.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
This is already done. @akash435

**Comment by akash435** [comment]
sorry for this, you can close this

**Comment by prathimacode-hub** [comment]
That's fine, no worries. @akash435
