### ISSUE TITLE
Image Resizer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#657]
---
Title: Image Resizer
About: It's an Image Processing Script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an image resizing application using tkinter GUI,

First we will ask user to select the image that he/she want to resize and then will ask to enter the size of image user want to resize.

After resize user will be able to save that image any where in the local system.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
