### ISSUE TITLE
University Website

### ISSUE THREAD

**Issue by kumarjeetray** [prathimacode-hub/Awesome_Python_Scripts#658]
---
Title:  University Website
About: I designed a full stack web application which is an university website using Flask in Python and SQLAlchemy. Where the information of different students are displayed. Here the student has to login with his roll number,username and password to access his information. The data of the students have to be inserted using SqlAlchemy manually---

Name: Kumarjeet Ray
Label: Feature Request
Assignee: ''

Define You:

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Is your feature request related to a problem? Please describe.

To help students see their information as and when required

Describe the solution you'd like...

I will use flask and SQLAlchemy in python scripts for this project which would do the necessary tasks.

Describe alternatives you've considered?

N.A

**Comment by prathimacode-hub** [comment]
Issue assigned @kumarjeetray
