### ISSUE TITLE
Github Bot (Python Automation)

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#659]
Title: Github Bot
About: To make all the works on github with our script only
Name: Neel Shah
Label: feature request
Assignee: ''

Define You:-

- [x] LGM-SOC'21 Participant
- [ ]  Contributor

Here we will have features as below in our script using PyGithub
- printing all repositories related to a specific langauge
- viewing all repositories of user account
- login on github
- view number of stars ,forks taraffic coming to a spefic repository
- create repository on github using python
- push files ina repositroy using python
- delete file in a repository

**Comment by neelshah2409** [comment]
@prathimacode-hub @Debashish-hub Please see the issue and assign me.

**Comment by prathimacode-hub** [comment]
Wow, interesting. Issue assigned. @neelshah2409
