### ISSUE TITLE
Implement Text translator using python

### ISSUE THREAD

**Issue by sherin527** [prathimacode-hub/Awesome_Python_Scripts#66]
@prathimacode-hub, I want to implement a python script for text translator with GUI using googletrans library of python. I am an LGM-SOC'21 participant please assign me this issue.

**Comment by prathimacode-hub** [comment]
Kindly follow the template mentioned to get issued. Do check up with the assigned issues for reference of how template should look like. So that I could assign this issue to you. @sherin527

**Comment by sherin527** [comment]
ok ma;am

**Comment by prathimacode-hub** [comment]
Hey @sherin527 you should never close the issues form your end. Just letting you know about it.

**Comment by sherin527** [comment]
ok, ma'am.
