### ISSUE TITLE
Python based GUI application to encrypt and decrypt text

### ISSUE THREAD

**Issue by Shivam0705** [prathimacode-hub/Awesome_Python_Scripts#660]
I would like to take the opportunity under devincept program to add this project here. Please assign me for this project.
Title: Python based GUI application to encrypt and decrypt text 
Name: Shivam Ravi
About the project:  Python GUI app that can encrypt and decrypt text. Implementing Caesar Cipher algorithm to perform the required operations
Label: Feature Request
Assignee: "

Define You:

I am a  DevIncept Participant. 

Solution:
I will develop the most secure and safe algorithm for encoding message/data and implementing it in the easiest way as possible. The data being transferred from one device to another is first converted into a form which couldn’t be decoded easily and user’s data will be kept stored till it reaches the receiver’s device.

Thanks & Regards

**Comment by prathimacode-hub** [comment]
Is this project similar to [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/BasicPythonScripts/Caesar%20Encryption)? And the contribution period for DevIncept program starts from 10th of July, 2021. You can come up with an issue from that point of time. Also make sure, the project isn't merged into this repo. All the best for your open source journey ahead. 👍@Shivam0705

**Comment by Shivam0705** [comment]
> Is this project similar to [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/BasicPythonScripts/Caesar%20Encryption)? And the contribution period for DevIncept program starts from 10th of July, 2021. You can come up with an issue from that point of time. Also make sure, the project isn't merged into this repo. All the best for your open source journey ahead. 👍@Shivam0705

Thanks for the reply. First of all the project you mentioned is quite ugly because it doesn't have any user interface and the Caesar cipher algorithm uses some mathematical formulas which is not clear in that project.  I will make sure that I will add my project to that repository that comes under DevIncept, but if possible please register my name to this project in order to avoid double entries at that time :)

**Comment by prathimacode-hub** [comment]
No, that's ok. It doesn't work like this actually. Once program starts, you can enhance that project. I cannot remove the existing project but you enhance it into a better solution. I shall guide with the process then and assign you, Go through README and CONTRIBUTING GUIDELINES, so that you can get ready by then. Right, it's a basic script. No contribution is small. Don't worry, you can get this issue assigned. But it's purely on FCFS basis. So make sure, you express your interest first. Yup, hope it answered your query. Thanks for showing up ur interest in making things better. Can't wait to see your work soon. @Shivam0705

**Comment by Shivam0705** [comment]
> No, that's ok. It doesn't work like this actually. Once program starts, you can enhance that project. I cannot remove the existing project but you enhance it into a better solution. I shall guide with the process then and assign you, Go through README and CONTRIBUTING GUIDELINES, so that you can get ready by then. Right, it's a basic script. No contribution is small. Don't worry, you can get this issue assigned. But it's purely on FCFS basis. So make sure, you express your interest first. Yup, hope it answered your query. Thanks for showing up ur interest in making things better. Can't wait to see your work soon. @Shivam0705

Hi, As the DevIncept program has been started, Could you assign me the above mentioned project name: Python based GUI application to encrypt and decrypt text

**Comment by prathimacode-hub** [comment]
Yes, issue is assigned. You can proceed. @Shivam0705
