### ISSUE TITLE
MP4 to MP3 Converter

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#664]
---
Title: MP4 to MP3 Converter
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

this application will allow user to select any mp4 video and will convert it to mp3 audio.

User can also save the mp3 video to any where on the local system.

for this will be using pymovie library of python

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
This issue is assigned to you. @akash435
