### ISSUE TITLE
Image To Cartoonish Image

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#665]
Title: Image To Cartoonish Image
 About: here we make cartoonish images
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Description
Here we make a simple image to cartoonish image using the cv library ,  here we change the colour scale of a picture and makes the combination in such a manner that it look like cartoon.

**Comment by prathimacode-hub** [comment]
Issue assigned. You can keep your project title as "Image Cartoonify". @neelshah2409
