### ISSUE TITLE
Heart Shape

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#667]
Title:  Heart Shape
About: Through the python code I want to print Heart shape under LGM-SoC 21
Name: Ashutosh Kumar Saw
Label: feature request
Assignee: ''

Define You :-
- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
Issue assigned. @Ashu-1309
