### ISSUE TITLE
Drawing Hexagonal Pattern

### ISSUE THREAD

**Issue by Ashu-1309** [prathimacode-hub/Awesome_Python_Scripts#670]
Title:  Hexagonal Pattern
About: Through the python code I want to print Hexagonal pattern under LGM-SoC 21
Name: Ashutosh Kumar Saw
Label: feature request
Assignee: ''

Define You :-
- [x] LGM-SOC'21 Participant 
- [x] Contributor

**Comment by prathimacode-hub** [comment]
Show some variations in your issues. Doing patterns one by one doesn't add up value. @Ashu-1309
