### ISSUE TITLE
EMI Calculator

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#671]
---
Title: EMI Calculator
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

this application will ask user to enter details about loan amount, interest per annum and no. of periods in month.
And after that it calculates the emi.

Will also add the option to generate the PDF that contains details about it.
Will also add option to download the PDF.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
