### ISSUE TITLE
Image To Ascii Art

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#672]
Title: Image To Ascii Art
About: here we will convert image to ascii image/art
Name: Neel Shah
Label: feature request
Assignee: ''

Define You :-

- [x] LGM-SOC'21 Participant
 - [ ] Contributor

Here we will convert simple image to an ascii art using PIL and system library we will first fetch the image and will make a similar art with different symbols like "S","%","?","*","+",";" and then saving the final art in text file.

**Comment by prathimacode-hub** [comment]
This script is already done. You can check it [here](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/ImageProcessingScripts/Image%20to%20ASCII%20Art)
