### ISSUE TITLE
Ideal Weight Calculator

### ISSUE THREAD

**Issue by cybot-des** [prathimacode-hub/Awesome_Python_Scripts#674]
---
Title: Ideal Weight Calculator
About: GUI Script project
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Details:
In this project, I will create a GUI with Tkinter which will take input of user's height and current weight.
On basis of above info it will calculate ideal weight (in kg) using 3 formulas (petersons, miller, robinson) and also show whether user is over weight or not

**Comment by cybot-des** [comment]
@prathimacode-hub please assign me this issue under LGMSoc'21

**Comment by prathimacode-hub** [comment]
Issue assigned. @cybot-des
