### ISSUE TITLE
Screenshot Taker

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#676]
---
Title: Screenshot Taker
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

this application will allow user to take the screenshot.
Will also show the screenshot taken.
And user can save it any where on the local system.

for this will be using pyautogui library in python.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
