### ISSUE TITLE
URL Extractor

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#678]
---
Title: URL Extractor
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

using this application user will be able to extract all types of URL, either be https, www, or any html or jpg url  from the given text  or documents.

will be using regex library for extracting urls

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
