### ISSUE TITLE
Twitter API

### ISSUE THREAD

**Issue by pragyakhanna11** [prathimacode-hub/Awesome_Python_Scripts#68]
Title | About | Name |Label | Assignee | 
--- | --- | --- | --- |--- 
Twitter API| Extract tweets using a keyword or username | Pragya Khanna | Feature Request|  | 

- [x] LGM SOC participant

**Describe the solution you would like:**
I will use tweepy module to make this project and extract tweets based on a keyword or twitter id.

**Comment by prathimacode-hub** [comment]
Interesting one. Issues is assigned to you. @pragyakhanna11
