### ISSUE TITLE
Programming Language Detector

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#681]
---
Title: Programming Language Detector
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

using this application user will be able to detect the among the common programming language.
here user will be allowed to enter small code snippets of the basic programming language like C, C++, Java or python.

And this will detect in which programming language is that code snippet is written.
Will be  using regex for detecting.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Great choice, issue assigned. @akash435
