### ISSUE TITLE
Latitude-Longitude Pair Verifier

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#683]
---
Title: Latitude-Longitude Pair Verifier
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

using this application user will be able to verify the pair of latitude and lonitude.

First will allow user to enter the longitude and latitude and the  will tell whether that pair is valid or not.
And if valid will try to show which location is present around that pair.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
