### ISSUE TITLE
Caesar Encryption 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#69]
I would like to solve this with python under LGM-SOC ,so mam please assign this issue.

**Comment by prathimacode-hub** [comment]
Kindly follow the template to get issue assigned. You can look into other assigned issues for reference of how template should look like. Once you do that, issue will be assigned. @neelshah2409

**Comment by neelshah2409** [comment]
Title: Caesar Encryption
About: I want to implement a python script for caesar problem 
Name: Neel Shah
Label: Feature Request
Assignee: ''


LGM-SOC'21>Participant

Description:> My approach would be like taking any input from user and in the code the number will be there for how many alphabets you need shift and user can change the number as per their requirement.

**Comment by prathimacode-hub** [comment]
Raise a new issue again with same project and description. This won't count. @neelshah2409
