### ISSUE TITLE
Anime Conversion

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#690]
---
Title: Anime Conversion
About: Suggest an idea for this project
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is related to python scripts.

**Describe the solution you'd like...**

I am going to use opencv for cartoonify the image of the original photo.

**Comment by prathimacode-hub** [comment]
This is already done, Kindly take up an another issue to work on. @rammya29
