### ISSUE TITLE
Absolute Time Delta

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#691]
---
Title: IP Address Extractor/Validator
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

in this first will allow user to enter two time in any time zones
time will be entered in terms of day, date,  Month,  year hour, minute, second, and time zone

And entering entering two times, user will be able to get the absolute time different between two this two times.

**Comment by akash435** [comment]
@prathimacode-hub ,please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
