### ISSUE TITLE
Hey I want To Add My UI for Khatabook

### ISSUE THREAD

**Issue by Knighthawk-Leo** [prathimacode-hub/Awesome_Python_Scripts#693]

**Comment by Knighthawk-Leo** [comment]
Can I create a PR NOW!!!

**Comment by prathimacode-hub** [comment]
Thie issue doesn't have any template neither any information about what the project is. Change the issue title to project title.  Elaborate the project. You can refer to other assigned issues to see how template looks like. Are you a devincept participant? @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
I am LGMSOC Participant
And Sure I will add some more points on template.

**Comment by prathimacode-hub** [comment]
Ok, but first add an issue template to get it assigned. Provide a project title. Let me know of where this would fit in the project. Elaborate your project. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
I have created a new issue you can check there.

**Comment by prathimacode-hub** [comment]
That issue don't have template, I had addressed the issue, check it.
