### ISSUE TITLE
KhataBook Management UI 

### ISSUE THREAD

**Issue by Knighthawk-Leo** [prathimacode-hub/Awesome_Python_Scripts#694]
Title: Khatabook UI Script 
About: It's an GUI script
Name: Sanskar Dwivedi
Label: Feature Request
Assignee: ''

Define You:

 LGM-SOC'21 Participant
 Contributor

This is an UI based Credit Management System App . This Will Manage credits of customers for local shops . As we know in India the credit system is very useful and this will help the shopkeepers to manage their shops. They can manage the customer profiles by just their Id they can perform Multiple Operations Such As
1. Add Customer Data
2. update The Data
3. Delete The Data
4. To show All remaining credits.

**Comment by prathimacode-hub** [comment]
Where is the issue template? Please follow the instructions. So this is a GUI script. Hope you are using python. Also you don't have to create a new issue for this, you can edit comments in your old PR with the edit option. Also letting you know, one should never close issues or PR form your end. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
I have Edited This And yes I am using Python and MYSQL for Data base management

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @Knighthawk-Leo
