### ISSUE TITLE
Hex Color Code

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#697]
---
Title: Hex Color Code
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

using this script user will be easily able to get to know about the hex code of the color.
Here will allow user to first select the color with name, and it will provide user about its 
1.) hex code
2.) In which category of shades it belongs to
3.) Also  also the RGB color code

and will also preview the color like how that selected color looks like in the preview area.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned to you @akash435
