### ISSUE TITLE
Smart Calculator

### ISSUE THREAD

**Issue by coding-geek21** [prathimacode-hub/Awesome_Python_Scripts#699]
---
Title: Smart Calculator
About: Smart Calculator is just like when you type "add 3 and 5" in google it will give you answer, this will be developed using GUI
Name: Jayapritha N
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Can you elaborate more, I guess this is done @coding-geek21

**Comment by coding-geek21** [comment]
> Can you elaborate more, I guess this is done @coding-geek21

Output will be like this Here I will be using Tkinter for GUI and normal functions using list
![image](https://user-images.githubusercontent.com/53329034/125404144-f00e3680-e3d3-11eb-9d78-ecf31d71d50a.png)

**Comment by prathimacode-hub** [comment]
Ok, you can proceed. @coding-geek21
