### ISSUE TITLE
Python Text Translator

### ISSUE THREAD

**Issue by sherin527** [prathimacode-hub/Awesome_Python_Scripts#70]
`---
Title: Python Text Translator
About: I want to implement a python script for text translator with GUI using googletrans library of python
Name: Sherin Shibu
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Describe the solution you'd like...**
It would be a basic text translator written in python language using GUI, where the user can enter input of any language and get the desired output according to the user's desire. I will be using googletrans library for text translation

@prathimacode-hub ma'am, I have changed the template, kindly assign this issue to me `

**Comment by prathimacode-hub** [comment]
Great. I had assigned this issue. Go ahead. @sherin527

**Comment by sherin527** [comment]
yes ma'am.

**Comment by sherin527** [comment]
@prathimacode-hub ma'am, in which folder I should add my implementation part?
