### ISSUE TITLE
Registration_form GUI

### ISSUE THREAD

**Issue by thejaswin123** [prathimacode-hub/Awesome_Python_Scripts#700]
---
Title: Registration form using Tkinter 
About: Form with attached database sqlite3
Name: Thejaswin S
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

I would like to add a Registration form using Tkinter for GUI and Sqlite3 for database.

**Describe the solution you'd like...**

fully coded in Python language and Tkinter for GUI and Sqlite3 for the database will be used.

**Approach to be followed (optional):**

A registration form using Tkinter and ssqlite3 for the database is used to store the details and display them.

**Additional context**
A nice GUI will be shown as output.

**Comment by prathimacode-hub** [comment]
This issue is already done [here](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/GUIScripts/Registration%20Form). If you want you can enhance this project. @thejaswin123

**Comment by thejaswin123** [comment]
I assure The Registration form will be completely different from the above

**Comment by prathimacode-hub** [comment]
It might be different but its same gui script. Enhance the existing project, that would be better. @thejaswin123

**Comment by prathimacode-hub** [comment]
So do you like to enhance it? @thejaswin123

**Comment by thejaswin123** [comment]
![form](https://user-images.githubusercontent.com/52855622/125423563-1e07a869-b46a-4457-a2a2-f6f0274c3cec.png)
i have been working on this and would like to add this

**Comment by prathimacode-hub** [comment]
Looks good, but there is already a project of the same in "GUIScripts", ok do one thing. Inside the project folder which is existing, add up the "Enhanced" folder and provide all your project files there according to the project structure given. If you are ok with this, I shall assign the issue. @thejaswin123

**Comment by thejaswin123** [comment]
Yeah I am ok with this and in Awesome_Python_Scripts/GUIScripts/Registration Form/  I should create "Enhanced" folder and add my files right?

**Comment by prathimacode-hub** [comment]
Yes, right. Issue assigned. @thejaswin123
