### ISSUE TITLE
Hotel Management System - GUI

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#701]
---
Title: Hotel Management System - GUI
About: The Hotel Management system the are features like the check-in, check-out and booking facilities of the customer and used tkinter module for looking as a application
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is created using python scripts. and using tkinter module

**Describe the solution you'd like...**

This project gives the information regarding the check-in, check-out and booking facilities of the customer. There are user friendly buttons available for the custtomers

**Comment by Debashish-hub** [comment]
Issue is assigned to you @rammya29
