### ISSUE TITLE
Spotify Song Lyrics Extractor 

### ISSUE THREAD

**Issue by Akash20x** [prathimacode-hub/Awesome_Python_Scripts#702]
Title: Spotify Song Lyrics Extractor 
About: Add a python script to scrape all lyrics of the spotify Track or spotify Playlist songs from different lyrics provider websites. 

Name: Akash Jain 
Label: Feature Request
Assignee: "

Define You:

DevIncept Participant
Contributor

Solution:
In this user have to give name of a spotify track or provide link of the spotify playlist, then if it is a valid Spotify track or valid playlist url then it searches lyrics for that track's song from different lyrics provider websites and scraped it and save the lyrics as a text file. It will also display song title and artist name in the console.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of DCP'21

**Comment by himanshu007-creator** [comment]
@Akash20x  thanks for submitting the issue. Please submit your code in [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/BasicPythonScripts) folder. Please comment your code wherever possible and use a docstring in functions/classes as well
