### ISSUE TITLE
Pharmacy Management System 

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#704]
---
Title: Pharmacy Management System
About: This project will ask to enter the details of the medicine and rate and quantity of the products.  
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is related to python scripts 

**Describe the solution you'd like...**

 I would like implement this project using tkinter module and also thought of using database to give better output.

**Comment by Debashish-hub** [comment]
Please elaborate @rammya29

**Comment by prathimacode-hub** [comment]
You can work on this as only one, devincept or lgmsoc. let us know. @rammya29

**Comment by rammya29** [comment]
I would like to work this under lgmsoc.

**Comment by rammya29** [comment]
This project looks like the user should enter the item name, price and quantity of the medicine and it will stored like a database of the items, we can add items and delete items from the list also we can see previous item, first item and item entered.

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @rammya29
