### ISSUE TITLE
Family Keylogger Python Script for Ethical hacking

### ISSUE THREAD

**Issue by Dhruv-194** [prathimacode-hub/Awesome_Python_Scripts#705]
---
Title: Ethical Hacking python scripts
About: I would like to create a folder/section in this repository where the contributors could add python scripts related to ethical hacking. I would like to begin this section by adding a family keylogger python script.
Name: Dhruv Mehta
Label: Feature Request
Assignee: 'Kindly please assign this to me

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

**Additional context**
A section of adding python based ethical hacking scripts to this repository would improve this repository and open it to more and more contribution.

**Comment by prathimacode-hub** [comment]
You can work on only 1 issue at a time
An issue is already been assigned. @Dhruv-194

**Comment by Dhruv-194** [comment]
Alright @prathimacode-hub I will first work on that issue and then after my successful submission, you can assign me this one too.

**Comment by prathimacode-hub** [comment]
It's a wonderful idea, good to see your initiation. Yes, you can work on this. But add the script name you would like to work on first. This looks like bundle and not specific. 1 Issue = 1 Project. @Dhruv-194

**Comment by Dhruv-194** [comment]
Hey @prathimacode-hub I have updated the title and the description of this issue. Now can you please assign me this so that I can work on it.

**Comment by prathimacode-hub** [comment]
Issue assigned. As said, create a separate repository of "EthicalHackingScripts". @Dhruv-194
