### ISSUE TITLE
Drink Water Reminder Script

### ISSUE THREAD

**Issue by Dhruv-194** [prathimacode-hub/Awesome_Python_Scripts#706]
---
Title: Drink Water Reminder Script
About: A python script which runs in background of your system and reminds you to drink water after every 40mins.
Name: Dhruv Mehta
Label: Feature Request
Assignee: Kindly please assign this issue to me

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

**Additional context**
We developers keep on sitting on our laptops focusing on our tasks and more often than not we forget to drink the minimum amount of water which our body needs. Hence this reminder script would run in the background of our system and remind us to drink water from time to time.

**Comment by prathimacode-hub** [comment]
Awesome, issue assigned. @Dhruv-194
