### ISSUE TITLE
Postal Code Validator

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#707]
---
Title: Postal Code Validator
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

using this script user will be able to check if the postal code is valid or not.
And if valid will show user that postal code if for which city, state in India.

And checking validity will use regex for postal code.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
