### ISSUE TITLE
Typing Speed Test

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#71]
Title: Typing Speed test
About: I want to implement a python script for this problem using time library
Name: Neel Shah
Label: Feature Request
Assignee: ''

LGM-SOC'21>Participant

Description:> My approach would be like using time lib. for calculating the time taken by user to write the given sentence and it also indicates the errors.

**Comment by prathimacode-hub** [comment]
Interesting project. Sure, go ahead with it. I had assigned it to you. @neelshah2409
