### ISSUE TITLE
Code Comments Fetcher

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#710]
---
Title: Code Comments Fetcher
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

using this script user will be easily able to fetch all the comments in the common programming language code like c , c++, java, python.
First will allow user to enter any code snippets with  comments, and the application will fetch all types of comments present in it.

Will try to make it supportable for all common programming language like c,c++, java and python.

**Comment by akash435** [comment]
@prathimacode-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
