### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#713]
Title: Loan Calculator
About: It's an GUI script
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ]  Contributor

Here it is an gui script where we will ask the rate of interest , duration / no. of years and total loan amount and from that we will calculate the monthly payment and total repay payment of the loan.

**Comment by Debashish-hub** [comment]
Issue assigned @neelshah2409
