### ISSUE TITLE
Contact Management System

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#717]
---
Title: Contact Management System
About: 
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, It is related to Python script. 

**Describe the solution you'd like...**

This project is done by using the tkinter module. It has functions which include adding, viewing, deleting and updating contact lists. While adding the contact of a person, he/she has to provide first name, last name, gender, address and contact details. The user can also update the contact list if he/she wants to..

**Comment by prathimacode-hub** [comment]
Is this an address book? @rammya29

**Comment by rammya29** [comment]
No mam, it is a contact phone number, as a feature it also include address.

**Comment by prathimacode-hub** [comment]
Ok, cool. Issue approved. @rammya29
