### ISSUE TITLE
Tic_ Tac_ Toe_ Game 

### ISSUE THREAD

**Issue by prakhar07msd** [prathimacode-hub/Awesome_Python_Scripts#72]
Title: Tic Tac Toe game using Tkinker
About: I want to implement Tkinker GUI for tic tac toe game
Name: Prakhar Agarwal
Label: Feature Request
Assignee: 

LGM-SOC'21: Participant

Description: I would like to implement Tkinker GUI for simple Tic toe game.can you please assign me this one?

**Comment by prathimacode-hub** [comment]
Good to see your enthusiasm. Yup, go ahead. I had assigned this issue to you. @prakhar07msd

**Comment by prathimacode-hub** [comment]
No update yet from your end. Is evrything going good. @prakhar07msd

**Comment by prakhar07msd** [comment]
> No update yet from your end. Is evrything going good. @prakhar07msd

Due to some health related issue I was not active...

**Comment by prathimacode-hub** [comment]
Ok, hope all got fine now. No issues. Let me know about it. Health is top most priority. So that you can take some extra time for it. @prakhar07msd

**Comment by jayant766** [comment]
Please assign it to me under LGMSOC'21

**Comment by Debashish-hub** [comment]
> Please assign it to me under LGMSOC'21

This has been assigned already. You can create a new issue @jayant766
