### ISSUE TITLE
Marvel API

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#720]
Title: Marvel API
About: It's api script
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ] Contributor

Here from the marvel website we get an api key and using that we fetch the information of a particular character that in how many movies he/she had played a role and showing the list of that all.

**Comment by prathimacode-hub** [comment]
Issue assigned. @neelshah2409
