### ISSUE TITLE
Memory Game

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#722]
---
Title: Memory Game
About: Memory puzzle game to check your concentration and for fun.
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

It is created by python scripts. 

**Describe the solution you'd like...**

It is a memory puzzle game where you can test your concentration of image blocks and connect the blocks until all the boxes are opened. It is created by pygame and animation used for image blocks to give more attraction.

**Comment by Debashish-hub** [comment]
Is not it similar to #231 @rammya29

**Comment by rammya29** [comment]
Yes, it is kind of similar. I will raise another issue with new project.

**Comment by Debashish-hub** [comment]
> Yes, it is kind of similar. I will raise another issue with new project. Is slide game is already taken?

What is slide game? You can just have a look at the scripts and the active issues.
