### ISSUE TITLE
Slide Game

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#723]
---
Title: Slide Game
About: In this game, the player has to arrange the tiles or blocks in the correct order.
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is related to the python script

**Describe the solution you'd like...**

This project is to create a sliding tile game of multiple levels. In this game, the player has to select level which he/she wants to play. It is implemented using pygame and random modules.

**Comment by Debashish-hub** [comment]
Issue assigned @rammya29
