### ISSUE TITLE
Cryptocurrency API

### ISSUE THREAD

**Issue by drashtipatel2503** [prathimacode-hub/Awesome_Python_Scripts#724]
**Project Title**: Cryptocurrency rates
**about**:           It will take cryptocurrency as input and return its current value, max value of the day, min value of the day, and 
                           time  when this value is last updated.
**Name:** Patel Drashti
**Label**: Feature Request
 LGM SOC'21 participant

The idea is to build a python program that takes user input(currency) and returns out its value, max value, min value, and last updated time in JSON format.

**Comment by Debashish-hub** [comment]
Issue assigned @drashtipatel2503
