### ISSUE TITLE
Resume Generator

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#728]
---
Title: Resume Generator
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

In this application first will ask user to fill the common details that are in Resume like
Name
Email Id
different Links
Education
Skills
Experience
Certificates & Awards
Projects

And the will generate the Resume which can be generated and saved.

**Comment by akash435** [comment]
@prathimacode-hub, @Debashish-hub  please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
