### ISSUE TITLE
Regex Checker

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#733]
---
Title: Regex Checker
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

In this application user will be able to check whether a given regex is correct or not.

here will ask user to enter any regex and application will tell the user that regex is correct or not.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
