### ISSUE TITLE
Simulate Color Game

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#735]
---
Title: Simulate Color Game
About: Pygame Scripts
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes it is relate to python scripts.

**Description**

There are four colored buttons on the screen. The buttons light up in a certain random pattern, and then the player must repeat this pattern by pressing the buttons in the correct order. Each time the player successfully simulates the pattern, the pattern gets longer. The player tries to match the pattern for as long as possible.

**Describe the solution you'd like...**

I will implement this using pygame.

**Comment by Debashish-hub** [comment]
Issue assigned @rammya29
