### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by GVictorsd** [prathimacode-hub/Awesome_Python_Scripts#736]
_Title_: Collision Detection and handling
_About_: Physics simulation script in python 3
_Name_: Victor Swaroop
_Label_: Feature Request
Assignee: ''

**Define You:**

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Collision detection and handling the collisions between two rigid bodies is one of the key parts of game development and other simulation software.
The project aims to implement a physically precious model of collisions between two balls bouncing in a box. Collisions are handled according to law of conservation of momentum and kinetic energy.

**Describe the solution you'd like...**

I am planing to leverage the concepts of object oriented programming in the code flow with python 3. Turtle module is used for frontend graphics.

**Comment by prathimacode-hub** [comment]
It's a wonderful script, issue assigned. @GVictorsd
