### ISSUE TITLE
Add snake_mania

### ISSUE THREAD

**Issue by sambit221** [prathimacode-hub/Awesome_Python_Scripts#74]
Title: snake_mania
About: I want to implement Pygame module for snake mania game.
Name: Sambit Kumar tripathy
Label: Feature Request
Assignee:
LGM-SOC'21: Participant

Description: I would like to implement pygame module for the snake mania game.In this game, the main objective of the player is to catch the maximum number of fruits without hitting the wall or itself.
can you please assign me to do so?

**Comment by prathimacode-hub** [comment]
Sorry to say, but snake game is already assigned on first come first serve basis. Isn't this the same game? @sambit221

**Comment by sambit221** [comment]
its the same game with some good features like 
1-background music
2- notification sound
3- it records previous high score

**Comment by prathimacode-hub** [comment]
Oh that's great. I can suggest one thing. Once PR is made for snake game. You can create a new issue stating that you want to do enhancement for the snake game. Ok? Shall I close this issue now? @sambit221

**Comment by sambit221** [comment]
Ok maam. can you please tag the link of that assigned issue here. it would be helpful for me to find. thank you.

**Comment by prathimacode-hub** [comment]
https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/PyGamesScripts/Snake%20Game This is the link of snake game which has been approved. @sambit221

**Comment by prathimacode-hub** [comment]
You shouldn't close PR or issue from your end. @sambit221

**Comment by sambit221** [comment]
I am sorry. I thought I have to close it as the project was submitted by someone else.
