### ISSUE TITLE
Tetromino Game

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#740]
---
Title: Tetromino Game
About: These are look like block game played in mobile, when a row is completed it deletes the block in that row. 
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, the problem is related to python scripts.

**Describe the solution you'd like...**

The board is made up of 10 x 20 spaces that the blocks fall and stack up in.
A box is a single filled-in square space on the board.
The things that fall from the top of the board that the player can rotate and position. Each piece has a shape and is made up of 4 boxes.
The shapes are the different types of pieces in the game. The names of the shapes are T, S, Z, J, L, I, and O.
When a piece has either reached the bottom of the board or is touching a box on the board, we say that the piece has landed. At that point, the next piece should start falling.

**Comment by prathimacode-hub** [comment]
Issue assigned. @rammya29
