### ISSUE TITLE
Credit Card Numbers Authentication

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#743]
---
Title: Sentence Segmenter
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

In this application user will be able to authenticate whether his/her credit card number is authenticated as true credit card numbers.

Also if a credit card number is not authenticated will show the reason why it is not authenticated.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
