### ISSUE TITLE
Star Pusher Game

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#749]
---
Title: Star Pushing game
About: It is a game where there will number of stars and player has to move the star in the to fill the blocks.
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is related to the python scripts.

**Describe the solution you'd like...**

The player is in a room with several stars. There are star marks on the grounds of some of the tile sprites in the room. The player must figure out how to push the stars on top of the tiles with star marks. It is implemented using pygame module

**Comment by prathimacode-hub** [comment]
Issue assigned. @rammya29
