### ISSUE TITLE
Alarm_Clock

### ISSUE THREAD

**Issue by pratimakush10** [prathimacode-hub/Awesome_Python_Scripts#75]
Title :  Alarm Clock using time module of python.
About : input hours and minutes for alarm to ring *at that respective time alarm will ring.*
Name : Pratima Kushwaha
Label : Feature Request
Assignee :

LGM-SOC'21: Participant

Description : I would like to implement basic python script *Alarm Clock* using time module of python can you please assign this to me?

**Comment by prathimacode-hub** [comment]
Kudos of you. Well needed in day to day lives. Go ahead. I had assigned this task to you. @pratimakush10
