### ISSUE TITLE
Income-Tax-Calculator

### ISSUE THREAD

**Issue by baljeet-singh97** [prathimacode-hub/Awesome_Python_Scripts#750]
Title: Income-Tax-Calculator
About : its a GUI based income tax calcultor coded in python
Name: Baljeet Singh
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant 
Is your feature request related to a problem? Please describe.

Yes, it is related to the python scripts.

Describe the solution you'd like...

here is basic GUI based income tax calculator written in python language all the parameters used here are not correct just on internet search basis just pull the code and update the creteria of tax and use it anyone can contribute this to upgrade it or if willingly to make changes just fork it make changes and pull req.

**Comment by baljeet-singh97** [comment]
i want to be assigned on this.

**Comment by prathimacode-hub** [comment]
Issue assigned. @baljeet-singh97
