### ISSUE TITLE
Smart Calculator

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#751]
Title: Smart Calculator
About: It is a gui script.
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
 - [ ] DevIncept Participant
- [ ] Contributor

Here using the tkinter we will make gui and in that there will be text area for input where user can write " add 4 and 4, mul 5and 2,hcf of 3 and 9 , etc." Here we have multiply and all simple functions along with lcm ,hcf and modulo also.

**Comment by prathimacode-hub** [comment]
This is already assigned. @neelshah2409
