### ISSUE TITLE
Age On Different Planet

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#753]
---
Title: Age On Different Planet
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an application using tkinter GUI,

In this application user will be able to calculate his/her age on different planets.

User just enter his/her birth date, and select the planet and can calculate the age on selected planet.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned to you @akash435
