### ISSUE TITLE
Anagram String

### ISSUE THREAD

**Issue by sumitsoni0907** [prathimacode-hub/Awesome_Python_Scripts#756]
**About:**  second string is a rearrangement of first string which means anagram string is a another string that contains same character only order of characters can be different.
example: "race" and "care"

**Name:** Sumit Soni

**Label:** Feature Request

Define You:
- [ ] LGM-SOC'21 Participant
- [x] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
     yes it is related to python script

**Describe the solution you'd like...**
 user entering two string. checking length of  both string same or not. if length not same then string is not anagram. if same then sorting both string and check sorting string match or not. It is match then both strings are anagram string. sorting strings not same then it is not anagram string.

**Comment by prathimacode-hub** [comment]
You haven't filled all the details. @sumitsoni0907

**Comment by prathimacode-hub** [comment]
Are you LGMSOC or Devincept participant? @sumitsoni0907

**Comment by sumitsoni0907** [comment]
> Are you LGMSOC or Devincept participant? @sumitsoni0907

Devincept participant

**Comment by sumitsoni0907** [comment]
> You haven't filled all the details. @sumitsoni0907

can I edit this issue and fill all details?

**Comment by prathimacode-hub** [comment]
Yes. @sumitsoni0907

**Comment by sumitsoni0907** [comment]
I edited this issue. verify and assign me.

**Comment by prathimacode-hub** [comment]
Issue assigned. @sumitsoni0907

**Comment by sumitsoni0907** [comment]
hello mam I fork and clone repository. but I create a branch give following fatal error
fatal: 'String' is not a commit and a branch 'Anagram' cannot be created from it
**Command:** $ git checkout -b Anagram String

**Comment by prathimacode-hub** [comment]
Hmm, are you on slack? If so ping me over there. @sumitsoni0907
