### ISSUE TITLE
Aadhaar Card Generation Application

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#758]
---
Title: Aadhar Card Generation Application
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a simple aadhar card generating application using tkinter GUI,

In this application user will be able to allowed to fill the form of aadhar card.
which will contain basic details like Name, Profile picture, virtual signature, DOB and other details necessary for aadhaar card.

Will also implement to check the validiy of each data user is filling, and if data is not valid then will not allow user to submit the form.

And after that will generate a virtual aadhar card using that data.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned @akash435
