### ISSUE TITLE
Correct Flow Game

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#763]
---
Title: Correct Flow Game
About: It's an Pygame script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a correct flow game generating application using tkinter GUI,

In this we will give any terms or things and for that we will give the process of that in random order and player needs to sort the process in correct flow.
Like for we give recipe process in random other and player needs to correct the order.

And there will be different level of each terms.

And at last final score will be displayed.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
