### ISSUE TITLE
Squirrel Eating Game 

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#765]
---
Title: Squirrel Eating Game
About: Its a game where squirrel eats the smaller squirrel.
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes it is related to python scripts

**Describe the solution you'd like...**

It is a graphical game where squirrel will be moving around the screen eating smaller squirrels and avoiding larger squirrels. Each time the player’s squirrel eats a squirrel that is smaller than it, it grows larger. The player loses if their squirrel gets hit three times.

**Comment by Debashish-hub** [comment]
Issue assigned @rammya29
