### ISSUE TITLE
Detect The Language

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#769]
---
Title: Detect The Language
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an  application using tkinter GUI,

In this user will be able able to detect the language in which the entered sentence or phrase is written.
like if user enter 
- good morning , it will show ENGLISH
- Hola - it will show Hawaains
- हिन्दी - it will show HINDI

will be using nltk library in python to detect this

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
