### ISSUE TITLE
Snake_game 

### ISSUE THREAD

**Issue by muskantayal123** [prathimacode-hub/Awesome_Python_Scripts#77]
Title: Snake Game
About: I'll implement random or turtle library for this project.
Name: Muskan Tayal
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description:  First i'll make the virtual screen for the game and then i'll work on the snake body after that on the food. 
Then also i'll work on the score points too.

please assign to me this issue.

**Comment by prathimacode-hub** [comment]
Where's the template? @muskantayal123

**Comment by prathimacode-hub** [comment]
Shall I make it easy for you? I shall provide the template here. You just add the changes according to your project. @muskantayal123

**Comment by muskantayal123** [comment]
Title: Snake Game
About: I'll implement random or turtle library for this project.
Name: Muskan Tayal
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description:  First i'll make the virtual screen for the game and then i'll work on the snake body after that on the food. 
Then also i'll work on the score points too.

please assign to me this issue.

**Comment by muskantayal123** [comment]
@prathimacode-hub  Mam i have done this. Please check it and assign this issue to me.

**Comment by prathimacode-hub** [comment]
Good to see your dedication. Issue is assigned to you. @muskantayal123

**Comment by prathimacode-hub** [comment]
There was no update from you about the progress. Is everything going fine?@muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub Done with the project mam but actually i am facing problem while doing pull request as i'm new user to github so do not know how to commit.

**Comment by Debashish-hub** [comment]
What's the problem you are facing @muskantayal123

**Comment by muskantayal123** [comment]
@Debashish-hub  i did till clone part after that i do not know how to commit.

**Comment by Debashish-hub** [comment]
Please follow the procedure :
- Fork the repo
- Clone the repo of your GitHub to your system
- Make the required changes
- write the following  commands
- - git add .
- - git commit -m 'message'
- - git push origin
- then go to your GitHub repo and merge by creating pull request

**Comment by muskantayal123** [comment]
@Debashish-hub  thank you . I'll try and if i face some issue i'll get  back to you.

**Comment by Debashish-hub** [comment]
> @Debashish-hub thank you . I'll try and if i face some issue i'll get back to you.

Great! Go ahead @muskantayal123

**Comment by muskantayal123** [comment]
@Debashish-hub 
![image_2021-06-14_120256](https://user-images.githubusercontent.com/62842695/121849005-74ec2e80-cd08-11eb-83fc-852e5b8bcd7a.png)
 Sir Please tell me why i am getting this error?

**Comment by Debashish-hub** [comment]
use your email and your name in place of "you@example.com" and "Your Name" @muskantayal123
