### ISSUE TITLE
I want to update snake game from Procedure Oriented Programming to Object Oriented Programming

### ISSUE THREAD

**Issue by AlexAdvent** [prathimacode-hub/Awesome_Python_Scripts#770]
I want to use oop in-game which makes coding more readable and efficient.

**Comment by prathimacode-hub** [comment]
This is done long back. Make sure you check if it's done in repo before you create an issue, it will reduce your efforts. And also readm the README and CONTRIBUTING GUIDELINES. Are you a participant of Devincept or LGMSoC?

**Comment by AlexAdvent** [comment]
yes I am Devincept participant @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Ok you want to enhance it. Then choose one out of the 2 games mentioned. And also use the issue template given to get issue assigned to you. You just have to add the template here and do the changes according to your project. Fill those details here in the comment. Also change the issue title to specific issue. 1 Issue = 1 PR. @AlexAdvent

**Comment by AlexAdvent** [comment]
---
Title: Sanke game improvement
About: create sperate file for each class and storing the highest score.
Name: Rajpurohit Vijeshkumar
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor




**Is your feature request related to a problem? Please describe.**

currently snake game is Procedure based I want to convert it into object-based. Separating each class in different files also storing the highest score.

**Describe the solution you'd like...**
I will make code easier to understand and also capable of storing the highest score.


@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Great, if that's the case inside Snake Game folder add an "Enhanced" folder into it. Here add all your project files according to project structure given in README file of this project. Issue assigned. @AlexAdvent
