### ISSUE TITLE
Dodger Game

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#772]
---
Title: Dodger
About: In the Dodger game, the player controls a sprite (the player’s character) who must dodge a whole bunch of baddies that fall from the top of the screen. The longer the player can keep dodging the baddies, the higher their score will get.
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is related to the python scripts

**Describe the solution you'd like...**
This game is made by pygame and also I will add some cheat modes to this game. If the player holds down the X key, every baddie’s speed is reduced to a super slow rate. If the player holds down the Z key, the baddies will reverse their direction and travel up the screen instead of down.

**Comment by prathimacode-hub** [comment]
This is already done. Kindly come up with an another issue. @rammya29

**Comment by prathimacode-hub** [comment]
Ok, are you using a GUI interface for it? @rammya29

**Comment by rammya29** [comment]
Yes

**Comment by prathimacode-hub** [comment]
Then you can add it up in "GUIScripts". Hope something extraordinary comes out from your end like you always showcase. 🤩@rammya29
