### ISSUE TITLE
Image Encryption Decryption

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#773]
---
Title: Image Encryption Decryption
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an  application using tkinter GUI,

In this user will be able to select the image user wants to encrypt,
will show encrypted image in grayscale form or any other.

User will also be able to decrypt the image to original one.

will also show the preview for both encryption and decryption.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
