### ISSUE TITLE
Steganography through CMD

### ISSUE THREAD

**Issue by dilroseR** [prathimacode-hub/Awesome_Python_Scripts#774]
<html>
<body>

Title | About | Name | Label | Assignee
-- | -- | -- | -- | --
hide text in image| encryption and decryption of text through images | Dilrose Reji | Feature Request |  

**Define You:**
DevIncept Participant
 
**Is your feature request related to a problem?** 
Yes

**Describe the solution you'd like...**
I would make a solution which would take a secret key, image and the text to be encrypted and the decryption of that would be done only if the secret key is provided from the intended receiver

**Comment by prathimacode-hub** [comment]
Issue assigned. @dilroseR

**Comment by dilroseR** [comment]
> Issue assigned. @dilroseR

thankyou
