### ISSUE TITLE
Pdf Merger 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#775]
Title: Pdf Merger
About: Here we merge all the pdfs
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ] Contributor

Here using the PyPdf library we use the PdfFileMerger module of that to merge  all the pdfs present in our folder .
So for merging the pdf we need to have in the same folder as of the script and then after running the script a new pdf will be generated . for the sequence concern we can rename all the pdf as 1 ,2 ,etc. so it will be easier.

**Comment by neelshah2409** [comment]
@prathimacode-hub @Debashish-hub Please see the issue and assign me.

**Comment by prathimacode-hub** [comment]
Issue assigned. @neelshah2409
