### ISSUE TITLE
Avatar Creator

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#780]
Title: Avatar Creator
About: Creating customised avatars 
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ] Contributor

Description:
Here using the python avatar library we will be creating different avatars as per our wish we can customise eyes, nose , tone  and  all the other accessories .

## Example
![Screenshot (693)](https://user-images.githubusercontent.com/71593494/125962882-e5f91ecf-172b-4bae-8ae9-5df2ac7812ff.png)

**Comment by Debashish-hub** [comment]
Issue assigned @neelshah2409
