### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#781]
---
Title: Video Player
About: It's an GUIScripts script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an  application using tkinter GUI,

In this user will be able to select the video from the local system and will be able to play video in the frame.

will be using library related to video in python.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned to you @akash435 
I think it will come under GUI Scripts
