### ISSUE TITLE
Connect Four game in Pygame

### ISSUE THREAD

**Issue by Dhruv-194** [prathimacode-hub/Awesome_Python_Scripts#782]
---
Title: Connect Four Game
About: I would like to create the famous connect four game using PyGame library and add it to this project.
Name: Dhruv Mehta
Label: Feature Request
Assignee: 'Kindly please assign me this issue

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

**Additional context**

I would like to add the connect four game which I will make using the PyGame python library. I will add it to the PyGame scripts folder of this repository.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Dhruv-194

**Comment by prathimacode-hub** [comment]
Its been 16days and no update from you yet. @Dhruv-194

**Comment by Dhruv-194** [comment]
> Its been 16days and no update from you yet. @Dhruv-194

@prathimacode-hub So sorry I just forgot about this issue. I have been contributing to other projects in DCP21 so this issue slipped out of my mind. I will right away start working on it and send the PR by today or tomorrow.

**Comment by prathimacode-hub** [comment]
Ok, go ahead. No issues. @Dhruv-194

**Comment by prathimacode-hub** [comment]
Update? @Dhruv-194

**Comment by Dhruv-194** [comment]
@prathimacode-hub kindly check my PR linked with this issue
