### ISSUE TITLE
Video Stitching

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#784]
---
Title: Video Stitching
About: It's an GUIScripts script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an  application using tkinter GUI,

In this user will be able to select the two videos from the local system and will be to stitch both videos.

User will also allowed to stitch videos in up-down or side by side manner.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
