### ISSUE TITLE
Image Snipper

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#789]
---
Title: Screen Snipper
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an  application using tkinter GUI and opencv library,

In this user will be able to snip some specific selected part of the image.

Like there will be a mouse pointer, user need to hold that pointer and drag it to make a rectangle shape around the part of the image user want to take the snip.

Also user will be able to save that snipped image anywhere on the local system.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
