### ISSUE TITLE
 Youtube video downloader 

### ISSUE THREAD

**Issue by Yash-Sakre** [prathimacode-hub/Awesome_Python_Scripts#79]
Title: Youtube video downloader
About: I want to create a script to download youtube videos.
Name: Yash Sakre
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description: I would like to Implement Python libraries to create this downloader. Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Sure, issue is assigned to you. Go ahead. 
Point to note : Never close issues and PR from your end. @Yash-Sakre

**Comment by prathimacode-hub** [comment]
Is everything going fine? No update since past 2 days. @Yash-Sakre

**Comment by Parth-Shete** [comment]
@prathimacode-hub can I work on this issue?

**Comment by prathimacode-hub** [comment]
Go through the README and CONTRIBUTING GUIDELINES of the project to know how to proceed. @Parth-Shete

**Comment by jayant766** [comment]
Please assign it to me under LGMSOC'21

**Comment by prathimacode-hub** [comment]
This issue is already assigned, check on with the label. If you want to work on issue, create on own using the template given. Don't comment on issues created. @jayant766

**Comment by prathimacode-hub** [comment]
It's been 8 days. As said, time to complete PR is only 5 days and no update since then. I already mentioned, you should update your progress once in 2 days. @Yash-Sakre

**Comment by Debashish-hub** [comment]
Hey @Yash-Sakre  Are you working on it or not, It's been 10 days without any update

**Comment by Yash-Sakre** [comment]
@Debashish-hub assign someone else. Something came up so I am unable to do it. Sorry for your time.

**Comment by prathimacode-hub** [comment]
That's fine. No issue. @Yash-Sakre

**Comment by ainy-123** [comment]
hey @prathimacode-hub ,I want to work on this issue under LGM-SoC'21.
Will you please assign this to me?

**Comment by prathimacode-hub** [comment]
You can work on only 1 issue at a time. So first decide on the issue you want to work on, or create a new issue you're interested to work on. Before that read the README and CONTRIBUTING GUIDELINES of the project. @ainy-123

**Comment by ainy-123** [comment]
> You can work on only 1 issue at a time. So first decide on the issue you want to work on, or create a new issue you're interested to work on. Before that read the README and CONTRIBUTING GUIDELINES of the project. @ainy-123

okay. I will complete this one first and then will work on issue #20(drowsiness detection...).

**Comment by prathimacode-hub** [comment]
Ok, sure. You can proceed. Issue is assigned. All the best. @ainy-123

**Comment by ainy-123** [comment]
> Ok, sure. You can proceed. Issue is assigned. All the best. @ainy-123

thank you :)

**Comment by prathimacode-hub** [comment]
Any progress update? @ainy-123

**Comment by ainy-123** [comment]
> Any progress update? @ainy-123

Yes, will create the PR today.

**Comment by Debashish-hub** [comment]
Hey! @ainy-123. Any progress update!

**Comment by prathimacode-hub** [comment]
No update from you. @ainy-123

**Comment by ainy-123** [comment]
> No update from you. @ainy-123

Sorry, I won't be able to complete this,stuck in other urgent stuffs , unassigning myself.

**Comment by prathimacode-hub** [comment]
You shouldn't unassign yourself, instead of notifying it you did off on your own. It's completely wrong. @ainy-123

**Comment by ainy-123** [comment]
> You shouldn't unassign yourself, instead of notifying it you did off on your own. It's completely wrong. @ainy-123

Oh, I didn't know that it's wrong to unassign myself.sorry for that.there was the option to "unassign me",so I did that.

**Comment by chandu6111** [comment]
Hey @prathimacode-hub could you please assign me this issue? I would like to contribute to it

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @chandu6111

**Comment by chandu6111** [comment]
Title: YouTube Video Downloader
Name: Chandana(@chandu6111)
Label: Feature Request 

- [x] LGM-SOC'21 participant 

**Description**:
A GUI application made using Tkinter. It basically has a textfield where the user can copy paste any YouTube Video link and click on "Download" button. The video gets downloaded in the same folder where the user is executing this code. And a message "Downloaded" gets displayed.

In this way, user can download any YouTube video of 'mp4' format and the speed depends on duration of video.

**Comment by chandu6111** [comment]
@prathimacode-hub is it okay?

**Comment by prathimacode-hub** [comment]
Issue assigned. Yup. @chandu6111
