### ISSUE TITLE
Movie Review Scraping

### ISSUE THREAD

**Issue by devkumar24** [prathimacode-hub/Awesome_Python_Scripts#791]
Title: It will scrap the reviews of the movies, and store them in the JSON file.
About: Add a python script to scrape movie reviews from the IMDB website.

Name: Dev Kumar
Label: Feature Request

Define You:

- [x] DevIncept Participant
- [ ] Contributor

Solution:
The user will enter the name of the movie and it will give make a JSON file in which all the reviews will be stored.

**Comment by prathimacode-hub** [comment]
You can proceed. @devkumar24
