### ISSUE TITLE
Image Watermark Remover

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#793]
---
Title: Image Watermark Remover
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create an  application using tkinter GUI and opencv library,

In this user will be able to remove the watermark from any image of the documents.

User just need to select that image with watermark and application will display the output with new gui window with image without watermark

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
