### ISSUE TITLE
Text to Speech in English Dictionary

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#795]
---
Title: Text to Speech in English Dictionary
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this  want to add text to speech feature in English Dictionary.

Will add text to speech button for both input entry and the output text.

For implementing will be using pyttsx3 library in python.

Want to work as an enhancement in English Dictionary which is in GUIScripts.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435

**Comment by akash435** [comment]
@Debashish-hub Also want to add Speech to Text in Dictionary, should I add this also or need to create another issue for that?

**Comment by Debashish-hub** [comment]
> @Debashish-hub Also want to add Speech to Text in Dictionary, should I add this also or need to create another issue for that?

It would be better if you will add it separately @akash435
