### ISSUE TITLE
Extracting Quotes from Website

### ISSUE THREAD

**Issue by Gaurav1401** [prathimacode-hub/Awesome_Python_Scripts#798]
Title: Extracting Quotes
About: Collecting the data from quotes.toscrape.com regarding different famous quotes of famous personalities
Name: Gaurav Kumar
Label: Feature Request

Define You:
LGM-SOC'21 Participant

    Contributor

In this, I want to discuss the basic concepts of WebScraping by extracting data from quotes.toscrape.com which contains famous quotes of different personalities and how to store that data in csv file for further analysis.

**Comment by Debashish-hub** [comment]
Issue assigned @Gaurav1401

**Comment by prathimacode-hub** [comment]
Is this a tutorial? This repo accepts only projects. @Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub I have changed all the thing now, including Read me file, now please let me know, if anything is left?
