### ISSUE TITLE
HTTP Error Codes

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#799]
---
Title: HTTP Error Codes
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this  will create an application using tkinter GUI,

here user will be able to get the details about any HTTP error codes.

The details will be in terms of 
what type of error
what's the meaning of that error code
Is it official or not official

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
