### ISSUE TITLE
Add flappy-bird game

### ISSUE THREAD

**Issue by sambit221** [prathimacode-hub/Awesome_Python_Scripts#80]
About: I want to implement pygame for flappy-bird game
Name: Sambit kumar tripathy
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description: I would like to implement pygame for flappy-bird game.can you please assign me to do so?

**Comment by prathimacode-hub** [comment]
Yup, go ahead. All the best. Issue is assigned to you. @sambit221

**Comment by sambit221** [comment]
can i know why you have removed LGM-SOC'21 tag?

**Comment by prathimacode-hub** [comment]
Didn't notice. I shall add up. @sambit221

**Comment by sambit221** [comment]
thank you maam
