### ISSUE TITLE
Billing System GUI

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [prathimacode-hub/Awesome_Python_Scripts#800]
Name:Sulagna Dutta Roy
Project name: Billing System GUI
Language:Python

It's a billing GUI which consists various types of items, tax, billing section etc.

**Comment by Sulagna-Dutta-Roy** [comment]
Please assign me this Issue

**Comment by prathimacode-hub** [comment]
Follw the issue template given and add the details according, this is not in right template to get issues assigned. Look at other assigned issues for reference. @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
---
Title: Biiling System GUI
About:  It consists various items ,total tax, ,buttons for generate tax etc.
Name: Sulagna Dutta Roy

---

Define You:

- [X] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

 This project is made by python tkinter library. 
It has a section that display the bills and generate successful bill.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Sulagna-Dutta-Roy
