### ISSUE TITLE
Yandex Website Clone

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#804]
---
Title: Yandex Website Clone
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will create a clone of Yandex Website using tkinter GUI,

Will be adding all the options that is in Yandex website gui, like,
Images
Video
Mail
Maps
AppMetrica
Translate
Browser

Also in search bar, will add option to enter input using virtual keyboard.

And will be using googlesearch library to implement this.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub ,please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
