### ISSUE TITLE
Password Validator

### ISSUE THREAD

**Issue by Mannuel25** [prathimacode-hub/Awesome_Python_Scripts#805]
---
Title: Password Validator
About: It's a CLI program that validates user's password
Name: Tanimowo Emmanuel
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

This program validates passwords to match specific rules. A valid password is one that conforms to the following rules:
- Minimum length is 6;
- Maximum length is 12;
- Contains at least an uppercase letter or a lowercase letter
- Contains at least a number;
- Contains at least a special character (such as @,+,£,$,%,*^,etc);
- Doesn't contain space(s).

**Comment by Mannuel25** [comment]
@Debashish-hub or @prathimacode-hub kindly assign this issue to me. Thanks.

**Comment by prathimacode-hub** [comment]
Issue assigned. Are you a LGMSoC participant or DCP participant or a Contirbutor? @Mannuel25

**Comment by Mannuel25** [comment]
> Issue assigned. Are you a LGMSoC participant or DCP participant or a Contirbutor? @Mannuel25

Thanks, I'm a Contributor by the way.
