### ISSUE TITLE
Internship -WebScrapping

### ISSUE THREAD

**Issue by rammya29** [prathimacode-hub/Awesome_Python_Scripts#806]
---
Title: Internship - WebScrapping
About: To scrap the internship details from the internship site - Internshala 
Name: Rammya Dharshini K
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is related to python - web scrapping

**Describe the solution you'd like...**

I would like to scrap the internship details from the Internshala website using beautifulsoup4

**Comment by Debashish-hub** [comment]
Issue assigned @rammya29
