### ISSUE TITLE
2DShapeArea Calculator

### ISSUE THREAD

**Issue by DurgaSai-16** [prathimacode-hub/Awesome_Python_Scripts#807]
---
Title: **2D Shapes Area Calculator**
About: Basic script for creating areas of 2D shapes.
Name: **Nallani Durga Sai**
Label: Feature Request
Assignee: ''

---

Define You:  **DevIncept Participant**

Description: I would like to make a tool that helps to calculate Areas of  2D shapes like (Circle,triangle,square,etc.) Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Great, it needs more details. But for this project, it has all that needs. Issue assigned. @DurgaSai-16
