### ISSUE TITLE
Image Size Compressor

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#809]
Title: Image Size Compressor
About: To reduce the size of the image without changing the dimension
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Using image module of the pillow library we will convert the size(memory space) of the image without changing the dimension of the image.

**Comment by Debashish-hub** [comment]
Issue assigned @neelshah2409
