### ISSUE TITLE
Typing Speed Test

### ISSUE THREAD

**Issue by Debashish-hub** [prathimacode-hub/Awesome_Python_Scripts#81]
Title : Typing Speed Test using pygame in python
About :  Test the typing skills of the user
Name : Debashish Kumar Sahoo
Label : Feature Request
Assignee :

LGM-SOC'21: Participant

Description : 
It would be a script using pygame which will be a game which will test the typing speed. The user has to type the given sentence and  the speed, accuracy and wpm will be shown as output. Please assign it to me.

**Comment by prathimacode-hub** [comment]
Typing speed test is already assigned, Do check out with issues and projects available in repository so that your efforts don't go wasted. Do raise a new issue which is not in the list. As well follow the template while you raise an issue. @Debashish-hub

**Comment by prathimacode-hub** [comment]
Never close issue from your end it's not a good practice. @Debashish-hub
