### ISSUE TITLE
Mouse Speed Tracker

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#813]
---
Title: Mouse Speed Tracker
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this script, will application using pyQt5.

Using this application user will be able to track the speed of the mouse movement in no. of pixels per second.
These speed will be between the starting and ending mouse position.

User will be shown the speed for each instance of his/her mouse movement.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
