### ISSUE TITLE
Speech Input in English Dictionary

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#817]
---
Title: Speech Input in English Dictionary
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this want to enhance the search in English Dictionary, with speech input.

Here will add a button clicking on which user can speak up word to search and it will analyze the word and display that word in the search entry box.
which can be searched using search button.

And if user didn't speak anything, then will show message for the same.

Will work as an enhancement in English Dictionary.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
