### ISSUE TITLE
Calculator App

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#82]
---
Title: A Calculator App
About: I would like to create a calculator app using python
Name: Manognya Dasika
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [] Contributor

**Describe the solution you'd like...**
Calculator is the one which is being always used by us. Keeping in mind that why not we create a calculator app for ourselves?
Yes, it is possible. I would like to create a calculator app using python mam. 

**Approach to be followed (optional):**
I will be using python to create a calculator app

**Comment by prathimacode-hub** [comment]
Yes, but this is not right template to follow while you create an issue. Do check out with the assigned issues to know the right template. And screenshots or images should be shown in PR. PR as well has a template. @manognyaa

**Comment by manognyaa** [comment]
@prathimacode-hub okay mam. I have edited the issue pls have a look mam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Sure, issue is assigned to you. Do check the project structure and template to follow along with the contributing guidelines while you raise a PR. @manognyaa
