### ISSUE TITLE
Text to Captcha Image

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#820]
---
Title: Text to Captcha Image
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI and Open CV library.

here will ask user to enter any text or word, of which user want to generate an captcha image,
and application will generate the captcha image for that and will also preview the captcha image to user at the same time.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
