### ISSUE TITLE
Text On Image

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#822]
---
Title: Text On Image
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI and Open CV library.

here will ask user to select any image and user will be able to add or write text on that image at any position on image.
And user will also be able to save that image with text on that.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
