### ISSUE TITLE
Video to Images

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#825]
---
Title: Video to Images
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI and Open CV library.

here user will be able to get the images from the selected.

User will be asked to select the any video (either mp4, mkv, avi or any other), 
and application will create all the image in a folder.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
