### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by Mannuel25** [prathimacode-hub/Awesome_Python_Scripts#826]
---
Title: Password Generator
About: It's a CLI program that randomly generate secure passwords
Name: Tanimowo Emmanuel
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

This program accepts the desired password length from the user and generates a secure password based on the length entered.

**Comment by Mannuel25** [comment]
Kindly assign this to me as a contributor @prathimacode-hub. Thanks.

**Comment by prathimacode-hub** [comment]
Sorry to say, but this issue is already done. You can come up with new issue but make sure it's not in the repo so that your efforts don't go wasted. @Mannuel25

**Comment by Mannuel25** [comment]
> Sorry to say, but this issue is already done. You can come up with new issue but make sure it's not in the repo so that your efforts don't go wasted. @Mannuel25

Oh, I did check the repo and I found only a password generator game, not a password generator. But, I'll definitely come up with another one and ensure it isn't present in the repo.

**Comment by prathimacode-hub** [comment]
Yup, sure. All the best. 👍@Mannuel25

**Comment by prathimacode-hub** [comment]
You shouldn't close issues or PRs from your end
@Mannuel25

**Comment by Mannuel25** [comment]
> You shouldn't close issues or PRs from your end
> @Mannuel25

Oh, my apologies.

**Comment by prathimacode-hub** [comment]
> > You shouldn't close issues or PRs from your end
> > @Mannuel25
> 
> Oh, my apologies.

No worries, I am just letting you know. @Mannuel25
