### ISSUE TITLE
Video Property Fetcher

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#828]
---
Title: Video Property Fetcher
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

here user will be able to select any video and application will fetch the properties of that selected video 

Video Properties like:
Codec
Resolution
Aspect Ratio

Along with this also fetch the audio properties of audio which is in video
Audio properties like :
Codec:
Channels: 
Sample rate:

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
