### ISSUE TITLE
a voice recorder using python

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#829]
Title: Want to make a Voice Recorder using Python
Name: Umesh Singh
Label: Feature Request

Define You-
- [x] LGM-SOC'21 Participant
- [x] Contributor

Solution For Issue:
This feature will allow us to record our voice using a simple script written in python. I will be adding a working instruction for the project in the readme file with some screenshots.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam may I work on this??

**Comment by prathimacode-hub** [comment]
Issue assigned. @Umesh-01

**Comment by prathimacode-hub** [comment]
Its been 12 days no PR for this issue yet. @Umesh-01

**Comment by Umesh-01** [comment]
It's almost done @prathimacode-hub mam, regret for the delay... 😞

**Comment by prathimacode-hub** [comment]
Thats ok as long as u inform i have no issue. @Umesh-01
