### ISSUE TITLE
Weather Report using Python GUI

### ISSUE THREAD

**Issue by vaikunth-coder27** [prathimacode-hub/Awesome_Python_Scripts#83]
Title | About | Name | Label | Assignee
------------ | ------------- | ------------- | ------------- | -------------
Weather Report | This project will display the weather <br> report of the user's location | Vaikunth-coder27 | Feature request | 

- [x] LGM-SOC'21 participant

I would like to proceed by accessing the user's location then getting the weather report using necessary libraries and displaying it through a python GUI

**Comment by prathimacode-hub** [comment]
Is this a GUI script? Have you worked on it or yet to work? How would you expect the output to look like? @vaikunth-coder27

**Comment by vaikunth-coder27** [comment]
Yes ma'am it is a GUI script, I can display the user weather report in CLI. so now integrating it with GUI(PyQt5) I will do now ma'am.
The output will display the current temperature(both original temperature and apparent feel temperature), and also next day prediction will also be displayed ma'am.

**Comment by prathimacode-hub** [comment]
Ok sure. Go ahead with the issue. Issue is alloted to you. @vaikunth-coder27

**Comment by vaikunth-coder27** [comment]
Thanks a lot ma'am.

**Comment by vaikunth-coder27** [comment]
Good evening ma'am, regarding the update from my program. Minor functionality implementation is in progress ma'am.

**Comment by prathimacode-hub** [comment]
How is your project going on? Is it going according to your expectations? Had you framed the GUI? What are the steps you had underwent till now? @vaikunth-coder27

**Comment by vaikunth-coder27** [comment]
Yes ma'am the project is going well. I am getting output as expected. GUI s also framed ma'am, at present, I am working on adding more interactive features to the GUI. Ma'am at first using the API key I was able to get the details such as temperature, precipitation, humidity, and status of the weather for any user location and forecasting data is also extracted ma'am.

**Comment by prathimacode-hub** [comment]
That's great, can't wait to see your working model of the project. All the best. @vaikunth-coder27

**Comment by vaikunth-coder27** [comment]
Thanks a lot ma'am.
