### ISSUE TITLE
Emoji Dictionary

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#832]
---
Title: Emoji Dictionary
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

here will allow user to enter any emoji in the text area and will be able to search that emoji meaning.

like
if user enter 😃, then dictionary will show it's meaning like "grinning_face_with_big_eyes"

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
