### ISSUE TITLE
Video Cropper

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#834]
---
Title: Video Croppe
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

Here first will ask user to select any video user want to crop
and also for the dimensions of cropping, like height & width

After along with cropping will also  show the preview to the user.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue asigned. @akash435
