### ISSUE TITLE
Telegram Bot 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#835]
Title: Telegram Bot
Name: Neel Shah
Label: Feature Request

Define You-

- [x] LGM-SOC'21 Participant
- [ ] Contributor

## Description:
Here we would assign the function to bot created by us using the BotFather like if we type hello in the telegram bot then it will reply something like I am fine how are you.
Here we will use the keys given by BotFather in our script and then give the functions to our bot .

**Comment by prathimacode-hub** [comment]
Issue assigned. @neelshah2409
