### ISSUE TITLE
Brick Breaker Game

### ISSUE THREAD

**Issue by Jagannath8** [prathimacode-hub/Awesome_Python_Scripts#84]
Title: Brick Breaker Game
About: I want to create a Brick Breaker Game
Name: Jagannath Pal
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description: I would like to Implement Python libraries to create this game. Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Can you elaborate the game? How would you expect it to work? @Jagannath8

**Comment by Jagannath8** [comment]
In this game, the ball will bounce off every wall except the bottom one. Using the paddle to move along the screen, the player hits the ball that can touch the bricks and destroy them. Player have to destroy all the bricks to win the game.

**Comment by prathimacode-hub** [comment]
Got you, this issue is assigned to you. Get going. @Jagannath8
