### ISSUE TITLE
Image Noise Remover

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#840]
---
Title: Image Noise Remover
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

Here first will ask user to select any image from which user wants to remove noise
noise includes random brightness in image, the color factor of image, etc.

And will also allow user to see the preview of the noise removed image.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub  please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
