### ISSUE TITLE
Color Mixer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#842]
---
Title: Color Mixer
About: It's an GUIscript
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

Here first will allow user to enter the colour in hex code along with its proportion.

Then application will show the output final color formed by mixing those color in given proportion.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
