### ISSUE TITLE
Covid records

### ISSUE THREAD

**Issue by Gaurav1401** [prathimacode-hub/Awesome_Python_Scripts#843]
---
Title: Covid casesAPI
About: It will show the records of corona cases around the world like Total deaths and active cases. The records will be updated after every 10 min.
Name: Gaurav Kumar
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
The whole world is currently suffering with Corona so my project would be showing the number of corona cases all around the world 

**Describe the solution you'd like...**
By pulling the data from [disease.sh](https://disease.sh/) API, I shall be showing the number of records affected with corona.

**Comment by Gaurav1401** [comment]
@prathimacode-hub please assign me this issue :)

**Comment by Debashish-hub** [comment]
It's already done @Gaurav1401 
Check it once #205

**Comment by Gaurav1401** [comment]
Ohh alright, thanks for letting me know @Debashish-hub

**Comment by Gaurav1401** [comment]
@Debashish-hub but in that script, he is scraping data from another website and I am pulling data from an API. Also he is showing country wise data but I will be showing the whole world data, 
please have a look at my project here, and please let me know your opinion @Debashish-hub  and @prathimacode-hub 
https://github.com/Gaurav1401/Awesome_Python_Scripts/tree/main/APIScripts/Covid%20CasesAPI

**Comment by prathimacode-hub** [comment]
Ok, you can proceed. Do add it up in "APIScripts" @Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub mam, please have a look at my pull request
