### ISSUE TITLE
Unicode and Emoji

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#846]
---
Title: Unicode to Emoji
About: It's an GUIscript
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

here user will be able to convert from unicode to emoji 
and even vice  versa.

for eg.
\U0001f600  to  😀
and vice versa

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
