### ISSUE TITLE
Image Segmentation

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#848]
---
Title: Image Segmentation
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI and OpenCv library.

This application will analyze the image and highlights the border or partition line in image, or basically make segments of image highlights clearly.

And the show the segmented image as the preview also.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub ,please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435

**Comment by akash435** [comment]
@Debashish-hubcan you please add the assigned and LGMSOC label also.
