### ISSUE TITLE
Wanna try a guess ?

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#85]
Title: Wanna try a guess ?
About: My project is all about a guessing one. you need to type a random number to see whether you're random is correct or not .
Name: Manognya Dasika
Label: Feature Request
Assignee:

LGM-SOC'21: Participant 

Description: I would like to work on this issue. Please assign this issue to me mam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
This issue is already assigned. Do think of another issue to contirbute. But get things done with the PR before you move to next one. @manognyaa

**Comment by prathimacode-hub** [comment]
Since these issues are already taken, I shall close these 2 issues. You can create a new issue but finish the PR ok?

**Comment by prathimacode-hub** [comment]
All the best @manognyaa
