### ISSUE TITLE
Map Coloring

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#850]
---
Title: Map Coloring
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI and OpenCv library.

Here will allow user to select the image of map of any country, or state or district or any place with oulines present in it.

And the application will color that selected map with different color and preview the colored map to the user.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
