### ISSUE TITLE
Pokedex GUI 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#851]
Title: Pokedex GUI
About: It's an GUI script
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ] Contributor

## Description:
- Pokedex is basically an electronic device which shows information regarding all the members of pokemon and its types.
- Here using the pypokedex library we will do the same thing , we will take name or id of the member as input and then in the gui we will load the image and type of the character .

**Comment by prathimacode-hub** [comment]
Issue asigned. @neelshah2409
