### ISSUE TITLE
Decode Image Game

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#854]
---
Title: Decode Image Game
About: It's an Pygames script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an image decoding game using tkinter GUI.

Here, there will be many levels and for each level player will be given an image, which is concatenation of different image, \
And also there will be a word given related to that image, in which some alphabet will be missing and player need to fill that missing alphabets so that the final word will resemble  the image.

And there will be different score for each level and will show final score at the end.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
