### ISSUE TITLE
Number Guessing Game

### ISSUE THREAD

**Issue by Mannuel25** [prathimacode-hub/Awesome_Python_Scripts#855]
---
Title: Number Guesing Game
About: A CLI Number guessing game
Name: Emmanuel Tanimowo
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

This is a game that allows you guess a number between the range of 1- 10 in just 7 trials.

**Comment by Mannuel25** [comment]
@prathimacode-hub kindly assign this to me as a contributor. Thanks.

**Comment by prathimacode-hub** [comment]
I guess it's done once check it off. @Mannuel25

**Comment by Mannuel25** [comment]
> I guess it's done once check it off. @Mannuel25

Yeah, just confirmed it.
