### ISSUE TITLE
adding sorting script for algorithm in Awesome_Python_scripts

### ISSUE THREAD

**Issue by slowy07** [prathimacode-hub/Awesome_Python_Scripts#856]
Title : Sorting algorithm script
About : List All of sorting algorithm script
Name : [Arfy Slowy](https://github.com/slowy07)
Label : Feature Request
Assigne: ''

## Info about the related issue 
- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

## information
hello, here i wanna create  some script sorting algorithm with python, i have some script about sorting algorithm like **heap_sorting**, **selection_sort**, and many more

**Comment by prathimacode-hub** [comment]
What's the project? This repo allows only projects not alogrithms. To contribute algorithms, you can creat an issue [here](https://github.com/prathimacode-hub/PyAlgo-Tree). All the best. @slowy07

**Comment by slowy07** [comment]
okay thanks !! @prathimacode-hub
