### ISSUE TITLE
Object Counter in Image

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#858]
---
Title: Object Counter in Image
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an a simple object counting in image using tkinter GUI and OpenCv.

Here first allow user to select any image which has object in it, and the application will counts the total no. of project present in that selected image.

will also try to show the space occupied by the object in that image.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
