### ISSUE TITLE
Hand Cricket

### ISSUE THREAD

**Issue by DurgaSai-16** [prathimacode-hub/Awesome_Python_Scripts#859]
|Title|About|Name|Label|
|-|-|-|-|
|Hand Cricket|Hand Cricket is similar to cricket game with numbers between User and Computer | [Nallani Durga Sai](https://github.com/DurgaSai-16)|Feature request|
---

**Define You:**

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

**Description:**
- This came can be made possible by using simple python concepts Loops and Conditionals.
- User will bat first and score runs and He gets out
- User will out when his number equals with Computer number
- Then Computer will chase down the target and User should try take computers wicket.

Please Assign this issue to meMa'am

**Comment by prathimacode-hub** [comment]
Issue assigned. @DurgaSai-16
