### ISSUE TITLE
Pls feed me food

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#86]
Title: Snake game
About: I would like to create an snake game, please assign this issue to me mam
Name: Manognya Dasika
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description: Snake game is the only game which we never get bored. Adding to it, _My snake will only eat **(*)**_
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
This issue is already assigned. Take up an other issue, but before that do the corrections I had suggested for your PR you had created. @manognyaa

**Comment by prathimacode-hub** [comment]
All the best @manognyaa
