### ISSUE TITLE
Images Slideshow

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#861]
---
Title: Images Slideshow
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI.

Here will first ask user to select as many as images user want to make slideshow of that,
and the application will create a slideshow and convert it into mp4 video file.

And will also try to show the preview of the slideshow created using the images selected.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
issue assigned @akash435
