### ISSUE TITLE
Zip File Creator

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#862]
Title: Zip File Creator
About: To create zip file
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ] Contributor

- So here we will create a zip file having all the files that we wanted using zipfile library .
- Here all the files that we wanted in our zip file should be in the same folder as of script and the output zip file will also be created in the same folder.

**Comment by Debashish-hub** [comment]
Issue assigned @neelshah2409
