### ISSUE TITLE
RGB to LAB Conversion

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#865]
---
Title: RGB to LAB Conversion
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will want to enhance the color converter script in GUIScript by adding RGB to LAB conversion also.

In this user will be able to  convert any RGB color to LAB conversion.
LAB Stands for Lightness and A and B are chromatic component of color.

eg. RGB ([10, 0, 0])  ->  LAB ([0.5826, 2.6174, 0.9201])

and will also show the preview of the color being converted 

Want to work as an enhancement.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub , please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
