### ISSUE TITLE
Text Summarizer

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#867]
---
Title: Text Summarizer
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI,

Here user will be able to any long text or paragraph and will be able to summarize that paragraph.

application will show the paragraph in brief.

for implementing will be using nltk library in python.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
