### ISSUE TITLE
Screen Recorder

### ISSUE THREAD

**Issue by tanujadasari** [prathimacode-hub/Awesome_Python_Scripts#868]
---
| Title |About | Name | Label |
|-|-|-|-|
|Screen Recorder| To build a screen recorder using Python with PyAuto GUI| [D Tanuja](https://github.com/tanujadasari)|Feature Request|

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

**Description:**
In this script, will create Screen Recorder using PyAuto GUI,
In this user will be able to record the screen
Please Assign this issue to me @prathimacode-hub Ma'am .

**Comment by prathimacode-hub** [comment]
Issue assigned. @tanujadasari
