### ISSUE TITLE
Video to Grayscale

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#870]
---
Title: Video to Grayscale
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI, and OpenCv library

Here user will be able to select any video (either .mp4, .mkv, .ovi or anyother format) and application will convert selected video to grayscale video

Also user will be able to see the preview of both original video selected and the gray scale video generated.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
