### ISSUE TITLE
Peterson Number

### ISSUE THREAD

**Issue by sumitsoni0907** [prathimacode-hub/Awesome_Python_Scripts#871]
| Title | About | Name | Label | Assignee|
| :----:  | :-----: | :----: | :----: | ----|
| Peterson Number| Peterson number means sum of factorials of each digit is equal to number itself | [Sumit Soni](https://github.com/sumitsoni0907) | Feature Request|

Define You:

- [ ] LGM-SOC'21 Participant 
- [X] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

 yes It is related to basic python Script.

**Describe the solution you'd like...**

In this Problem user enter the number after spilt number into digit and adding with each digit factorial and compering  with entered number is same then number is Peterson  number otherwise not. Example: 145 = 1! + 4! +5! = 1+ 24 + 120 = 145.

**Additional context**

Please assign this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @sumitsoni0907
