### ISSUE TITLE
Image Contours Co-ordinates

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#874]
---
Title: Image Contours Co-ordinates
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI, and OpenCv library

Here user will be able to select any image with objects in it, and application will find all the contours present in it and will find co-ordinates of all of and show them in an image.

Like if there is any shape in image, it will show  the co-ordinates of the corner point of that shape.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub ,please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
