### ISSUE TITLE
Folder Content Sorter

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#875]
Title: Folder Content Sorter
About: here we sort the files
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
 - [ ] Contributor

- Here we will sort all the files of the folder as image , video, document and app/software and then we will merge all the files in their respective folder.
- Here we will use os and shutil library to sort the files as per their extension and then merge the files.

**Comment by prathimacode-hub** [comment]
Issue assigned. What about other issue opened? You don't want to work for it as an enhancement? @neelshah2409

**Comment by neelshah2409** [comment]
> Issue assigned. What about other issue opened? You don't want to work for it as an enhancement? @neelshah2409

yes mam let it be as it is , I had an GUI script but the purpose was same so please close that issue.
