### ISSUE TITLE
RGB Color Palette

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#877]
---
Title: RGB Color Palette
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI,

Here will create palette scale for red, green and blue color
using which user will be able to change the same at any instant and see the preview of the RGB color.

Also along  with preview of the color,As soon as user change the scale in the pallete, 
user will be able to get the Degree, Saturation and Lightness factor for that color at every instance.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
