### ISSUE TITLE
Video Encryption Decryption

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#881]
---
Title: Video Encryption Decryption
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI and OpencV library,

Using this will allow user to select any video and will be able to encrypt video.
And if user tries to play video after encryption, the video will play with grayscales frame.

After that user will also be able to decrypt video to original format.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub ,please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
