### ISSUE TITLE
Snowfall Filter on Image

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#882]
Title: Snowfall Filter on Image
About: It's an image processing script
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
- [ ] Contributor

- Here we create a virtual snowfall on any image and it looks like the person or object in the image feels like having the snowfall .
- Here we use random and pygame to make small small white circles moving so it would look like snowfall and we can also change the size of white circle and its speed.

**Comment by Debashish-hub** [comment]
Issue assigned @neelshah2409
