### ISSUE TITLE
Color Difference

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#884]
---
Title: Color Difference
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI

Here will allow user to select any two color using color palette and application will tell user about the difference between both selected color according to some standard method

Standard method includes :
Delta E CIE1994
Delta E CIE1994
Delta E CIE2000
Delta E CMC.

Above are the standard defined to find the difference between two color.

**Comment by akash435** [comment]
@prathimacode-hub @Debashish-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
