### ISSUE TITLE
Privacy Virtual Camera

### ISSUE THREAD

**Issue by TusharAMD** [prathimacode-hub/Awesome_Python_Scripts#887]
---
Title: Privacy Virtual Camera
About: This project will be about a virtual camera that will be made using OpenCV which will enable user to hide his/her face during video call and only outline of their face will be seen.
Name: Tushar Amdoskar
Label: Feature Request
Assignee: 'TusharAMD'

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

There are many instances where users don't wish to show their face and don't want the other person to recognize their identity from their voice. In simpler words, users wish to hide identity and at the same time have a video chat. There can be various examples like medical help, or if the judge has to provide an unbiased verdict without knowing someone's race, gender, etc. For such reasons, we can use just an outline of the face and the speech will be converted into text and will be displayed below the video.

**Describe the solution you'd like...**

I will be using OpenCV to create a outline mask of the user and then using pyvirtualcam. After that speech will be converted to text using watson speech or gtts. And that text will be shown on video

**Describe alternatives you've considered?**

I actually decided to make a full meet application using wither jitsi or WebRTC apis. And then convert speech to text and then again convert that text into computer generated speech. At end connect both the users using sockets. But I find it little difficult to work on that at current moment and need to research on it and moreover I think a single script will be more suitable for this repo.

**Comment by TusharAMD** [comment]
Can I work on this issue?

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. @TusharAMD
