### ISSUE TITLE
GUI Scroll-View

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#888]
---
Title: GUI Scroll-View
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI

Here will implement Scroll View in tkinter GUI window.

Normally tkinter GUI window has no scroll view, we only have to do in the space of GUI window only.
So here will implement scroll view in GUI window and will display either text, image with the help of scroll view.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
