### ISSUE TITLE
Image Search

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#890]
---
Title: Image Search
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an image search application using tkinter GUI

Here user will search by selecting any image from the local system.

First user will be asked to select any image, and on searching it will search all the related in the webpage.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
