### ISSUE TITLE
Bank Data Finder 

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#891]
Title: Bank Data Finder
About: It's an script with streamlit which runs in the browser
Name: Neel Shah
Label: Feature Request
Assignee: ''

Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant
 - [ ] Contributor

- Here we make a web application using streamlit , we find all the information of bank just by giving the IFSC code .
- We get information like address ,branch ,city, state , facilities available like upi , rtgs ,etc.

**Comment by neelshah2409** [comment]
@Debashish-hub @prathimacode-hub Please see the issue .

**Comment by prathimacode-hub** [comment]
Is it a  GUI or management system for banks? @neelshah2409

**Comment by neelshah2409** [comment]
> Is it a GUI or management system for banks? @neelshah2409

Mam it is a web app using streamlit.

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @neelshah2409
