### ISSUE TITLE
Update Cloning Repo Link in CONTRIBUTING_GUIDELINES.md

### ISSUE THREAD

**Issue by Mannuel25** [prathimacode-hub/Awesome_Python_Scripts#892]
---
Title:Update Link
About: --
Name: Emmanuel Tanimowo
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

I checked the CONTRIBUTION_GUIDELINES and found out that the cloning a repo link isn't valid. Upon clicking the link, it explains how to create an issue or pull request not how to clone a repo.

I would like to fix the link in the CONTRIBUTION_GUIDELINES and make the necessary ammendments.

**Comment by Mannuel25** [comment]
Kindly assign this to me @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned. @Mannuel25

**Comment by Mannuel25** [comment]
> Issue assigned. @Mannuel25

Thanks 🙂
