### ISSUE TITLE
Circular Image Cropper

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#895]
---
Title: Image Search
About: It's an ImageProcessing script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an circular image cropper application using tkinter GUI and OpenCv library,

Here user will be able to select any image and will be able to crop it in circle.

Here user can also reset the cropped image to original format.
Also user will be shown the preview of both the original format and the cropped format.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
