### ISSUE TITLE
move the box

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#90]
Title: _move the box_ 
About: my project is about a box where you can move anywhere in the given area. I will be using python for this mam.  

Name: Manognya Dasika
Label: Feature Request
Assignee:

LGM-SOC'21: Participant

Description: 
you can move the box where ever you like to move.
Can you please assign this issue to me. I would like to work on this issue @prathimacode-hub mam.

**Comment by prathimacode-hub** [comment]
First, do the changes for your PR I had asked for before moving to next issue.  @manognyaa

**Comment by manognyaa** [comment]
hello mam,
Can you please assign this issue to me, I would like to work on this mam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. @manognyaa
