### ISSUE TITLE
Random Shape Image Generator

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#900]
---
Title: Random Shape Image Generator
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI,

Here the application will generate random images each time whenever user clicks on generate image button.
Each image contains random shapes like circle, oval ,rectangle, line, etc.
And all the shapes will be in random order in image.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
