### ISSUE TITLE
American and British English Conversion

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#906]
---
Title: American and British English Conversion
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI,

Here user will be allowed to enter any text or paragraph in either american english and convert it to british engliish,
or british english to american english

will use requests library to get the content from json file link

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
