### ISSUE TITLE
OTP Generator

### ISSUE THREAD

**Issue by sumitsoni0907** [prathimacode-hub/Awesome_Python_Scripts#907]
|Title | About | Name | Label | Assignee |
|-----| --------|--------|-------|-----------|
|OTP Generator| Generating random OTP using random library | [Sumit Soni](https://github.com/sumitsoni0907)| Feature Request|  |

Define You:

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, It is related to python script. 

**Describe the solution you'd like...**

Now a days OTP’s are used in almost every service like Internet Banking, online transactions etc. They are generally combination of 4 or 6 numeric digits or a 6-digit alphanumeric. 
random() function can be used to generate random OTP(One Time Password) which is predefined in random library.

**Comment by prathimacode-hub** [comment]
Issue assigned. @sumitsoni0907
