### ISSUE TITLE
Adding Frames to Video

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#909]
---
Title: Adding frames to Video
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application using tkinter GUI,

using this application user will be able to add frames to video.

First will allow user to select any video, and also to select the frames user want to add in video.
Then application will add that frames to original video and preview the new video.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
