### ISSUE TITLE
CONTRIBUTING Link not working in README

### ISSUE THREAD

**Issue by MuditCh57** [prathimacode-hub/Awesome_Python_Scripts#91]
Error : On line 51-52 CONTRIBUTING link give 404 error.

Wrong : https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/Contributing_Guidelines.md 
**Contributing_Guidelines.md** should be in **capital letters** but it is in **small**.

Correction : https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/CONTRIBUTING_GUIDELINES.md
New link with **capital letters**.

**Comment by MuditCh57** [comment]
Can I fix this typo?

**Comment by prathimacode-hub** [comment]
Yeah, you can. Go ahead @MuditCh57
