### ISSUE TITLE
Dr Battery

### ISSUE THREAD

**Issue by DurgaSai-16** [prathimacode-hub/Awesome_Python_Scripts#911]
---
|Title|About|Name|Label|
|-|-|-|-|
|Dr Battery| Notifies you to charge when battery is draining and Unplug When battery seems to be over charging| [Nallani Durga Sai](https://github.com/DurgaSai-16)| Feature request|
---
## Define you: 
- [x] DevIncept Participant

## Description
- Battery is one of the important components in our system. We've to protect it from over charging and draining at the same time.
- This code wil let you know when the battery is draining and generates a voice output that ask you to charge.
- Also asks you to unplug if the battery seems to be over charging.
- In the end this will help you to increase the life time of your battery.

Please Assign this issue to me @prathimacode-hub Ma'am

**Comment by prathimacode-hub** [comment]
You can proceed. Issue assigned. @DurgaSai-16

**Comment by DurgaSai-16** [comment]
Okay Ma'am 🤩🤩
