### ISSUE TITLE
Object Detector

### ISSUE THREAD

**Issue by BMaster123** [prathimacode-hub/Awesome_Python_Scripts#913]
---
Title: Object detector
Name: Bhavesh Mandalapu
Label: Feature Request
---

Define You:

- [ ] Contributor

**Describe the solution you'd like...**

The program will ask for two images as inputs. The purpose of the program is to find the object in the first image in the second image. The program will find the object in the second image and draw a rectangle around it.

**Comment by prathimacode-hub** [comment]
Sorry to say but this is already done. You can take up an nother issue to work on. All the best. Also make sure before you take if script is present in the repo so that ur efforts don't go wasted. @BMaster123

**Comment by prathimacode-hub** [comment]
Never close issue or PR from your end, instead you can change up the title of the project to ur project using edit option here itself once you decide on the upcoming project. @BMaster123

**Comment by BMaster123** [comment]
Ok

**Comment by BMaster123** [comment]
Can you please assign this issue if it isn't already taken?

**Comment by prathimacode-hub** [comment]
Can you elaborate the issue? @BMaster123

**Comment by prathimacode-hub** [comment]
Also are you a LGMSoc participant, DCP participant or Contributor? @BMaster123

**Comment by BMaster123** [comment]
I am a contributor. What is LGMSoc?

**Comment by prathimacode-hub** [comment]
Issue assigned. That's a open source program currently this repo is part of. @BMaster123

**Comment by BMaster123** [comment]
Ok thank you.
