### ISSUE TITLE
Progress Bar in Video Player

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#915]
---
Title: Progress Bar in Video Player
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will enhance the Video Player script which is in GUIScript with progress bar.
Here will add progress bar, such that when video starts playing , the we can see the progress of video in progress bar,

Also when user clicks on the pause button, the  progress in progress bar will stop.
And on resuming again it will start again.

will be working as an enhancement

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
