### ISSUE TITLE
Wiki Bot

### ISSUE THREAD

**Issue by DurgaSai-16** [prathimacode-hub/Awesome_Python_Scripts#918]
---
|Title|About|Name|Label|
|-|-|-|-|
|Wiki Bot|  Wikipedia Bot is to benefit user just by taking user's speech as input and then it searches for the topic and provides relevant output in the form of text as well as audio along with an image related to it.| [Nallani Durga Sai](https://github.com/DurgaSai-16)| Feature request|
---
## Define you: 
- [x] DevIncept Participant

## Description
- Wiki Bot takes your voice as input.
- Browses all the relevant information regarding your topic from wikipedia
- Dictates the gathered information with related Image.
- All this process will be done within the IDE itself instead of opening browser and searching for it and gathering information.

Please Assign this issue to me @prathimacode-hub Ma'am

**Comment by prathimacode-hub** [comment]
Issue assigned. @DurgaSai-16
