### ISSUE TITLE
listen to the music 

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#92]
| Title| About|     Name           |          Label           |           Assignee            |
| ------------- | ------------- |  ------------- | ------------- |  ------------- | 
| song play | the song will play when you click run and I will be using python for this mam.|          Manognya Dasika         |        Feature Request               |                    |

LGM-SOC'21: Participant

Description:
_Do you know you can listen to the songs without any hard work ?_
yes, it's possible. My project will play the song when you click run and if you want to pause you can click (p) and if resume then (r) and if you are done you can click (e) for exit :)  

Can you please assign this issue to me. I would like to work on this issue @prathimacode-hub mam.

**Comment by prathimacode-hub** [comment]
First finish on the changes I had asked for. Your PR is still pending. Don't buzz over issues. Quality is better than quantity. You can do it. @manognyaa

**Comment by manognyaa** [comment]
hello mam,
can you please assign me this issue @prathimacode-hub mam

**Comment by prathimacode-hub** [comment]
Sorry to say, but this issue is already taken. You can take up some other issue to work on. No worries. @manognyaa
