### ISSUE TITLE
Password Generator for unique and strong passwords

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#920]
**Name: Umesh Singh
Label: Feature Request**

Define You-
- [x] LGM-SOC'21 Participant
- [x] Contributor

#### Is your feature request related to a problem? Please describe.
I want to make a password generator that will generate strong and unique passwords including a combination of uppercase and lowercase letters, numbers, and symbols.

#### Describe the solution you'd like
I will be using python for creating password generator. We can change the length of passwords and can also get any number of passwords according to our need.

**Comment by prathimacode-hub** [comment]
This issue is already done. Kindly take up an another issue to work on. @Umesh-01
