### ISSUE TITLE
Large Image Preview

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/Awesome_Python_Scripts#921]
---
Title: Large Image Preview
About: It's an GUI script
Name: Akash Ramanand Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

In this will create an application in tkinter GUI,

Generally while opening any large image, the image is previewed well is if it is larger than screensize.
Thus this application will allow user to preview the large image in small video with both X - axis scroll bar and Y - axis scroll bar

Using this user can preview large image in small window.

**Comment by akash435** [comment]
@prathimacode-hub please assign this to me under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
