### ISSUE TITLE
Instagram Profile Downloader

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#922]
Hey LGM-SoC / DCP participants, good to see you.

This project will help us in automatically downloading the instagram profile

Repo : Automation Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub 
In this we need to download the profile pic and instagram id using the instagram user name of any user.
is it?

**Comment by akash435** [comment]
@prathimacode-hub if this you can assign me under LGM SOC

**Comment by Debashish-hub** [comment]
Issue assigned @akash435
