### ISSUE TITLE
Website Status Checker

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#923]
Hey LGM-SoC / DCP participants, good to see you.

This project will check the status of the web address which is inputted.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub can i work on this under LGM SOC

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @akash435
