### ISSUE TITLE
Zoom Auto Attendant

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#925]
Hey contributors, good to see you. 

This project is a zoom bot that automatically joins zoom calls for you and saves the meeting id and password.

Repo : Automation Scripts 

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by NEERAJAP2001** [comment]
Hey, @prathimacode-hub is this repo eligible for hacktoberfest 2021? , If yes I'd like to work on this issue.

**Comment by prathimacode-hub** [comment]
Yes, this repo is eligible for hacktoberfest. @NEERAJAP2001

**Comment by prathimacode-hub** [comment]
First you have to get an issue assigned, before creation of your PR. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Oh! I'm sorry didn't notice that! Can you please assign the issue to me😅

**Comment by prathimacode-hub** [comment]
No worries. Issue assigned to @NEERAJAP2001
