### ISSUE TITLE
Youtube Trending Feeds Scrapper

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#926]
Hey LGM-SoC / DCP participants, good to see you. 

This project helps in scraping first 10 trending feeds of youtube in all categories.

Repo : Web Scraping Scripts 

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by BMaster123** [comment]
Can I work on this? I don't have any experience with web scraping but I would like to give it a try.

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. If you need any help, you can ask me. @BMaster123

**Comment by BMaster123** [comment]
Ok, thank you.

**Comment by prathimacode-hub** [comment]
Update please? @BMaster123

**Comment by BMaster123** [comment]
I am currently learning Beautiful Soup and Selenium. I will most likely be done making the scraper sometime within the next week.

**Comment by Master7130** [comment]
Update: I got it to scrape 3 of the trending pages but for some reason, the program isn't able to scrape one of them.

**Comment by prathimacode-hub** [comment]
Ok, can you share your project link? So that I could check on to it. @Master7130 
Do you have 2 github accounts? Since issue is assigned to you for @BMaster123. Kindly reply only through that profile if so.

**Comment by BMaster123** [comment]
Ok, I will do that. The code isn't long so I will just copy and paste it below. I was just trying to get the trending videos so I didn't format it yet but I will do so later.


```
from bs4 import BeautifulSoup
import requests
from selenium import webdriver

urls = [
    "bp=6gQJRkVleHBsb3Jl",
    "bp=4gINGgt5dG1hX2NoYXJ0cw%3D%3D",
    "bp=4gIcGhpnYW1pbmdfY29ycHVzX21vc3RfcG9wdWxhcg%3D%3D"
    "bp=4gIKGgh0cmFpbGVycw%3D%3D"
    ]

driver = webdriver.Chrome()

for url in urls:
    driver.get(f"https://www.youtube.com/feed/trending?{url}")

    content = driver.page_source.encode('utf8').strip()
    soup = BeautifulSoup(content, 'lxml')
    titles = soup.find_all('a', id='video-title')

    for i in range(0, 10):
        print(titles[i].text)
```

In the urls list, the 4 strings are the urls for the 4 tabs in the youtube trending page, Now, Music, Gaming, and Movies. The 3rd link which is the gaming tab is the one that isn't working.

**Comment by BMaster123** [comment]
@prathimacode-hub I just found the issue as I was looking through my code again. I didn't put a comma after the 3rd element in the urls list. The code works just fine now and I'll finish it and create a pull request today.
