### ISSUE TITLE
Voice Calculator

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#927]
Hey LGM-SoC / DCP participants, good to see you. 

This project helps in calculating various calculations such as arithmetic, linear expressions and trignometric problems using your voice.

Repo : GUI Scripts 

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by Khushi-sharma07** [comment]
Mam I would like to work on this under hacktoberfest please assign this to me.

**Comment by Khushi-sharma07** [comment]
I will create the pull request by tomorrow morning positively.

**Comment by prathimacode-hub** [comment]
Ok, sure. Issue assigned. You can proceed. @Khushi-sharma07
