### ISSUE TITLE
SlideShare Downloader

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#932]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in downloading slides from SlideShare as pdf using URL

Repo : GUI Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by vivekthedev** [comment]
Hey @prathimacode-hub , can you assign this to me? I think I can work on this.

**Comment by prathimacode-hub** [comment]
Sure, Issue assigned to @vivekthedev
