### ISSUE TITLE
Python IDE

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#933]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in using python IDE created to compile python files.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub i think this is similar to issue #638 ? Or there is some thing new in this?

**Comment by prathimacode-hub** [comment]
Oh, you had done it then. Oops, yes it's similar. Just recollecting all the scripts in repo seems daunting. Thanks for notifying. I shall close this issue. @akash435
