### ISSUE TITLE
Screen Recorder

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#934]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in recording the computer screen using record button.

Repo : GUI Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by TusharAMD** [comment]
Can I take up this issue?
1. I will be taking screenshots using library like selenium or any automation library
2. Store it in folder
3. Stitch the images into video using opencv video writer.
4. On Gui there will be pause, take screenshot and stop buttons

**Comment by prathimacode-hub** [comment]
Yes sure. Issue assigned. @TusharAMD
