### ISSUE TITLE
Rain Alert Notification

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#936]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in checking up the weather condition for the upcoming 12 hours and senda a message to registered mail id about being sunny or rainy.

Repo : Automation Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vkb20

**Comment by vkb20** [comment]
done.

**Comment by prathimacode-hub** [comment]
> done.

Kindly check with changes addressed. @vkb20
