### ISSUE TITLE
Are You Pawned

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#937]
Hey contributors, good to see you.

This project helps users in checking if their passwords were a part of data breach using the "haveibeenpwned.com API" to obtain data regarding passwords and how many times it did indulge in data breach

Repo : API Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by Developer-R-7** [comment]
Hey ,can you get me assigned for this issue and sorry for breaking the workflow of the project .

**Comment by prathimacode-hub** [comment]
Provide your approach and the issue are taking through part of any open source program while getting assigned. @Developer-R-7

**Comment by Developer-R-7** [comment]
**Approach**
This script will be using "ihavebeenpwned API V3" [Link for documentation](https://haveibeenpwned.com/API/v3#PwnedPasswords)

1. I will be using "requests" in-built python module to send a GET request to the API
2. Taking password input from the user as a string
3. The password string will be converted to hash SHA-1 as mentioned in the documentation  by using "hashlib" in-built python module 
4. The first 5 character of the hash SHA-1 will be send as parameters in the API call , the API response will be store in the form of list type.

**Sample request form**
> GET https://api.pwnedpasswords.com/range/{first 5 hash chars}

**Sample Response for the hash prefix  "21BD1" (first 5 character)**
```
0018A45C4D1DEF81644B54AB7F969B88D65:1
00D4F6E8FA6EECAD2A3AA415EEC418D38EC:2
```
5. If the password hash (excluding first 5 character) given by the user matches one of the API response password hash then the password is pwned. if it does not find match then the password is not pwned!.
6. The number of times the password has been pwned is after the (colon) ":" in the response format

**Comment by prathimacode-hub** [comment]
Issue assigned to @Developer-R-7
