### ISSUE TITLE
Pomodoro Timer

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#938]
Hey LGM-SoC / DCP participants, good to see you.

This project helps users in checking their productivity using pomodoro timer in a GUI friendly interface

Repo : GUI Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub can i work on this under LGM SOC.

**Comment by prathimacode-hub** [comment]
Issue assigned. @akash435
