### ISSUE TITLE
Image Neon Effect Filter

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#941]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in converting an image into an neon effect filtered image.

Repo : Image Processing Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by Khushi-sharma07** [comment]
Mam I would like to work on this issue under hacktoberfest please assign this to me.

**Comment by prathimacode-hub** [comment]
Yes, sure. Issue assigned. @Khushi-sharma07
