### ISSUE TITLE
Morse Code Translator

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#942]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in encoding text characters as standardized sequences of two different signal durations, called dots and dashes. Mostly used in safe communications

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub can i work on this under LGM SOC.

**Comment by prathimacode-hub** [comment]
Yes you can proceed. Issue assigned. @akash435
