### ISSUE TITLE
Lyrics Downloader

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#947]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in downloading lyrics of any number of songs, by any number of Artists using Genius API

Repo : API Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by TusharAMD** [comment]
In this project, user will be giving artist's name and song as input and lyrics will be shown to the user right?
![Image 1014](https://user-images.githubusercontent.com/59115865/128600770-ddaa3333-554a-481e-afdc-2f63609c45c6.png)

Also how should be the output presented. Will it be in terminal or file should be saved as text file?

**Comment by prathimacode-hub** [comment]
Instead of terminal, it should be like lyrics downloaded up in a subfolder created to upload it in .txt file when you run the program. Here you can use any API for working on this project. @TusharAMD

**Comment by TusharAMD** [comment]
Ok mam I can do this task, Please assign to me. LGM SOC participant

**Comment by prathimacode-hub** [comment]
Issue assigned. @TusharAMD

**Comment by prathimacode-hub** [comment]
Are you done? Before evening I should merge it up. Time is ticking up. @TusharAMD

**Comment by prathimacode-hub** [comment]
Sorry time is up and unfortunately i have to remove the label. But you can turn up the PR asap. @TusharAMD

**Comment by TusharAMD** [comment]
Okay mam no problem. Actually, I could have submitted it early. Thanks for your support and guidance in this repo and also ML Project kart. We can still submit PRs for other issues like even if they are not under LGM SOC?

**Comment by prathimacode-hub** [comment]
No worries, your PR reached on time and is added up for the scores. So no worries. All good. Most welcome. Sure, you are free to work on issues even if it's not a part of a program. @TusharAMD
