### ISSUE TITLE
My Routine Database System

### ISSUE THREAD

**Issue by LasyaGanesuni** [prathimacode-hub/Awesome_Python_Scripts#95]
**Title** : My Routine Database System
**About** : I want to create a My Routine Database System.
**Name** : Lasya Ganesuni
**Label** : Feature Request
**Assignee**:

**LGM-SOC'21** : Participant

**Description** : This My Routine Database System is a desktop application where we can update our daily routine. The frontend of this project is made up of Tkinter. The widgets used in development of this frontend are Label, Entry, Listbox, and Button. The backend of the project is developed with MYSQL. Here in this application we can add data, we can delete a particular data, we can view the data as a whole or we can also search by a particular data. Finally we can close the application by using close button.

**Please assign me this issue.**

**Comment by prathimacode-hub** [comment]
I understood the project. I want you to let me know of how would you expect this to work? And as well here in this project repository, where would this project fit in. It's a desktop application. Else, you can suggest a new repository to add this script? @LasyaGanesuni

**Comment by LasyaGanesuni** [comment]
mam, I thought it would fit in GUI Scripts.

**Comment by prathimacode-hub** [comment]
So output would be in GUI format? @LasyaGanesuni

**Comment by LasyaGanesuni** [comment]
Yes mam the ouput will be displayed in a GUI

**Comment by prathimacode-hub** [comment]
Ok, cool Go ahead. I had assigned this issue to you. Follow the program structure as given in README file. All the best. @LasyaGanesuni

**Comment by LasyaGanesuni** [comment]
Thank you mam.
