### ISSUE TITLE
Image Background Remover

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#950]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in removing the background from an image by keeping only foreground in focus.

Repo : Image Processing Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by vchsi** [comment]
@prathimacode-hub I can do this with CV2, IMUTILS or Numpy. Can I have this issue?

**Comment by prathimacode-hub** [comment]
Yes, you can. But first let me know, are you a DCP participant or LGMSOC participant or Contributor? So that I can assign  accordingly. @vchsi

**Comment by vchsi** [comment]
I am contributor

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @vchsi

**Comment by vchsi** [comment]
Almost done. What background should I put over the old one?

**Comment by prathimacode-hub** [comment]
Thats upto you. @vchsi

**Comment by prathimacode-hub** [comment]
Any update? @vchsi

**Comment by vchsi** [comment]
@prathimacode-hub Still currently working on it

**Comment by prathimacode-hub** [comment]
Ok, proceed. @vchsi

**Comment by prathimacode-hub** [comment]
It's been 9days since issue is assigned. No update yet. Kindly let me know of your progress. Issue can't be held for this long. @vchsi

**Comment by prathimacode-hub** [comment]
Update please? @vchsi

**Comment by shubhdholakiya** [comment]
Hello, Can I work on this issue as pervious contributor has exceeded their time!
If yes, kindly assign this to me.

**Comment by prathimacode-hub** [comment]
Lets give time for more 3 days. If not, can think accordingly. Meanwhile other issue is assigned to you. You can complete that.  👍@shubhdholakiya

**Comment by Khushi-sharma07** [comment]
Mam I want to work on this under hacktoberfest. Can you please assign this to me?

**Comment by prathimacode-hub** [comment]
@Khushi-sharma07, already 3 issues have been assigned to you. I will assign this once you finish the assigned issues so that it won't be a burden for you.

**Comment by Khushi-sharma07** [comment]
Mam now I had submitted the pr for two issues can I please get it assigned under hacktoberfest so  that I can finish it within deadline.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Thank you mam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Awaiting your PR. @Khushi-sharma07
