### ISSUE TITLE
HTML Mail Sender

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#951]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in sending HTML mails to bulk email adresses.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by dilroseR** [comment]
can i do this with python?

**Comment by prathimacode-hub** [comment]
Yes, you can. Issue assigned. @dilroseR

**Comment by prathimacode-hub** [comment]
Yes, only python is allowed, that's the reason issue is here in this repo. @dilroseR

**Comment by prathimacode-hub** [comment]
Last date to merge PR's is 9th Aug. Make sure you complete it by then. @dilroseR
