### ISSUE TITLE
Generate WIFI Passwords

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#954]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in sending all the stored WIFI passwords of your Windows PC to your given mail address.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by shubhdholakiya** [comment]
Hello Mam,
I want to work on this issue.
Can please elaborate what this code will do?

**Comment by prathimacode-hub** [comment]
Hey, glad to see your interest in this issue. So, basically this project is about generating all the WIFI passwords that are stored in your PC and automatically send it to the mail address notified in your code. Hope it's clear. If you're with ok with project, I shall assign it up the issue. @shubhdholakiya

**Comment by shubhdholakiya** [comment]
So basically it is like it will extract all WiFi SSIDs and their passwords for all the wifi networks on a computer right and send that in well format way to given email address? 
If I am wrong please correct me. Basically, I am new to open source so I will take a bit time to understand, sorry for the inconvenience.

**Comment by prathimacode-hub** [comment]
You are absolutely on right track. No issues, I will be happy to guide you. Don't hesitate to ping me. @shubhdholakiya

**Comment by shubhdholakiya** [comment]
Okay, so please assign me this task. Thank you very much for understand and helping out.

**Comment by prathimacode-hub** [comment]
> Okay, so please assign me this task. Thank you very much for understand and helping out.

Most welcome. Sure, issue is assigned. You can proceed. Max time for PR is 5 days and keep updating your progress once in 2days. Any queries, you can put it out here. You can ask me or @Debashish-hub. All the best. @shubhdholakiya

**Comment by shubhdholakiya** [comment]
Hello,
In which folder do you want to add this program, mam?

**Comment by prathimacode-hub** [comment]
> Hello,
> In which folder do you want to add this program, mam?

You can add this in AutomationScripts. @shubhdholakiya

**Comment by shubhdholakiya** [comment]
> > Hello,
> > In which folder do you want to add this program, mam?
> 
> You can add this in AutomationScripts. @shubhdholakiya

Surely, thank you.

**Comment by shubhdholakiya** [comment]
I think we should name this as Extracting WiFi Passwords, instead of Generate WiFi Passwords?
