### ISSUE TITLE
Image Ghost Filter

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#956]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in converting an image into ghost/negative image.

Repo : Image Processing Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by TusharAMD** [comment]
I think according to my understanding in this project we are supposed to convert a normal image to negative image as we do invert in paint
for eg. 
Converting this
![2](https://user-images.githubusercontent.com/59115865/128594543-4e9e844b-511a-422c-9207-2c06a4eac59d.jpg)
into
![Image 1013](https://user-images.githubusercontent.com/59115865/128594549-cdb7d00d-cee9-467c-a603-9dd6a0a8a974.png)

If this is problem statement my approach will be pretty straightforward. I will traverse all pixels of the image and get negative value that is 255 - value of current pixel.
If my understanding is correct then I can do this program. Please assign it to me (LGM SOC Participant)

**Comment by prathimacode-hub** [comment]
Yes, your understanding is absolutely right. You can go ahead. Issue assigned. @TusharAMD
