### ISSUE TITLE
Crypto Price Checker

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#957]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in allowing the users to fetch live top-100 cryptocurrency prices scraped from cointracker.io

Repo : Web Scraping Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by Ashu-1309** [comment]
@prathimacode-hub can you please explain me what o have to do in this ??

**Comment by prathimacode-hub** [comment]
@Ashu-1309, it gets prices of top 100 cryptocurrencies as an output.

**Comment by Ashu-1309** [comment]
Can you assign me this project under Hacktoberfest .

**Comment by prathimacode-hub** [comment]
Issue assigned to @Ashu-1309

**Comment by devkumar24** [comment]
Can I work on this issue?

**Comment by prathimacode-hub** [comment]
I had assigned the issue to you. You can make a PR for it. @vkb20

**Comment by vkb20** [comment]
done.
