### ISSUE TITLE
Censor Word Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#958]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in detecting censor words from English language. Censor words are swear words/abusive words/curse words/bad words in any language.

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by TusharAMD** [comment]
Can I work on this issue?
Following are things I will be doing.
1. Make a list of all censor words with all variations.
2. Ask user to paste the text matter in to a text file
3. Run script and in that ask user to enter filename
4. Execute program and store result in new text file
Is this ok for this issue or any addition is needed?

**Comment by prathimacode-hub** [comment]
Perfect but instead of asking user to enter filename, in project file you can add up an empty text file in the script end where once script starts running, user can add a text matter and it automatically detects the censor words and deposit them in the empty text file that's created using the script. You can create  GUI interface for this project so that it would feasible for the working criteria. @TusharAMD

**Comment by prathimacode-hub** [comment]
If this is ok, I shall assign it to you. @TusharAMD

**Comment by TusharAMD** [comment]
Ok mam I can do this. You can assign this to me.

**Comment by prathimacode-hub** [comment]
Ok, DCP or LGMSoC particpant? @TusharAMD

**Comment by TusharAMD** [comment]
LGMSoC
