### ISSUE TITLE
Network Usage Tracker

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#959]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in keeping a track of network usage and notify you if it exceeds a specified limit (for WIFI).

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
Can i work on this issue?

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. @akash435

**Comment by akash435** [comment]
@prathimacode-hub I am done with this, can you please add labels, so that I can make PR.

**Comment by prathimacode-hub** [comment]
Added labels, you can proceed @akash435
