### ISSUE TITLE
Alarm Clock

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#96]
Title | About | Name | Label | Assignee
----- |------- | ------- | ----- | ----------
Alarm Clock | using Python GUI | Sonali Bedade | Feature Request |

- [ x ]  LGM-SOC'21 Participant

GUI of an alarm clock which beeps at the time entered.

**Comment by prathimacode-hub** [comment]
Hey @sonaliBedade, PR is already created for Alarm clock. You had come late. Sorry. You can take up another issue.
