### ISSUE TITLE
Auto Fill Google Forms 

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#960]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in filling out the google form automatically by bot

Repo : Automation Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by whyadiwhy** [comment]
please assign this to me

**Comment by prathimacode-hub** [comment]
Issue assigned. @whyadiwhy
