### ISSUE TITLE
Attachment Downloader

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#961]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in downloads gmail atttachments in no time

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by shubhdholakiya** [comment]
I want to work on this issue. Kindly assign this to me, mam!

**Comment by shubhdholakiya** [comment]
Hello mam, can you please assign this to me?

**Comment by prathimacode-hub** [comment]
Yes, sure. Issue assigned. @shubhdholakiya

**Comment by shubhdholakiya** [comment]
Okay, thank you for assigning this to me.

**Comment by prathimacode-hub** [comment]
> Okay, thank you for assigning this to me.

Go ahead, welcome. @shubhdholakiya

**Comment by prathimacode-hub** [comment]
It's been 23 days and no revert yet. @shubhdholakiya

**Comment by prathimacode-hub** [comment]
@shubhdholakiya, any update?

**Comment by shubhdholakiya** [comment]
> @shubhdholakiya, any update?

Hello,
I am very sorry, I wasn't able to make PR, give me 2 days and will make a PR.

**Comment by prathimacode-hub** [comment]
No PR yet? @shubhdholakiya

**Comment by shubhdholakiya** [comment]
Yes mam, will be making PR by tomorrow, very sorry for the delay.
