### ISSUE TITLE
Test Your Internet Speed

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Awesome_Python_Scripts#964]
Hey LGM-SoC / DCP participants, good to see you.

This project helps in checking up with the internet speed of uploading and downloading files.

Repo : GUI Scripts

If you like to work on this issue, follow the given guidelines for code as well as for the README.

**Comment by akash435** [comment]
@prathimacode-hub I think this is similar to #473

**Comment by prathimacode-hub** [comment]
Ha, yes. Right. You have good observation skills. Thank you. @akash435
