### ISSUE TITLE
Change Image background

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#968]
Define You-

- [x] LGM-SOC'21 Participant
- [x] Contributor

Title:
A project for changing image background 
**Name: Umesh Singh**
Label: Feature Request

### Solution For Issue:
I want to make a project that can help us to change the background of any image using python. I will be adding working instructions for the project in the readme file with some screenshots.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam there is no project for changing image background....
should I work on this issue??

**Comment by prathimacode-hub** [comment]
k, issue assigned. @Umesh-01
