### ISSUE TITLE
Card_Game

### ISSUE THREAD

**Issue by Manasa2811** [prathimacode-hub/Awesome_Python_Scripts#97]
Title: Card-Game

About: A simple card game developed using OOP in python. A two player game where each player draws a card and the player with higher value takes both the cards. The player with no cards left loses the game.

Name: Manasa2811

LGM-SOC'21: Participant

A python IDE or a jupyter notebook can be used to build this project. Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Good project, nice to know. Assigning this issue to you. @Manasa2811
