### ISSUE TITLE
Caesar Encryption

### ISSUE THREAD

**Issue by neelshah2409** [prathimacode-hub/Awesome_Python_Scripts#98]
Title: Caesar Encryption
About: I want to implement a python script for Caesar problem
Name: Neel Shah
Label: Feature Request
Assignee: ''

LGM-SOC'21>Participant

Description:> My approach would be like taking any input from user and in the code the number will be there for how many alphabets you need shift and user can change the number as per their requirement.

**Comment by prathimacode-hub** [comment]
Great going. Assigned this issue to you. @neelshah2409
