### ISSUE TITLE
Watermark on Image or Video

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#980]
Define You-

- [x] LGM-SOC'21 Participant
- [x] Contributor

Title:
A project for adding Watermark on Image or Video 
**Name: Umesh Singh**
Label: Feature Request

### Solution For Issue:
I want to make a project that can help us to add watermark on any image image using python. I will be adding working instructions for the project in the readme file with some screenshots.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam should I work on this project??

**Comment by prathimacode-hub** [comment]
Sorry to say, but this is already done. You can come up with an another issue. @Umesh-01

**Comment by Umesh-01** [comment]
> Sorry to say, but this is already done [here](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/ImageProcessingScripts/Watermark%20Inserter%20GUI). You can come up with an another issue. @Umesh-01

okk mam, I will close this issue...

**Comment by prathimacode-hub** [comment]
You shouldn't close up the issue. @Umesh-01
