### ISSUE TITLE
Camera based thermal screening

### ISSUE THREAD

**Issue by Umesh-01** [prathimacode-hub/Awesome_Python_Scripts#982]
Define You-

- [x] LGM-SOC'21 Participant
- [x] Contributor

Title:
Project for thermal screening based on an image. 
**Name: Umesh Singh**
Label: Feature Request

### Solution For Issue:
I want to make a project that can do thermal screening based on images from the video or only images with the help of libraries in python. I will be adding working instructions for the project in the readme file with some screenshots.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam should I work on this project??

**Comment by Umesh-01** [comment]
I will do it by tomorrow

**Comment by prathimacode-hub** [comment]
Yes, only if you could do it by tomorrow. Issue assigned. @Umesh-01

**Comment by prathimacode-hub** [comment]
Are you done? @Umesh-01

**Comment by Umesh-01** [comment]
> Are you done? Team has asked me to wind up PR's. I have time only till 2pm. @Umesh-01

yes mam almost done, give me some time...

**Comment by prathimacode-hub** [comment]
Ok, have it only till 2pm. Kindly make it fast. @Umesh-01

**Comment by prathimacode-hub** [comment]
Done? @Umesh-01

**Comment by Umesh-01** [comment]
done @prathimacode-hub mam :sweat:
