### ISSUE TITLE
PDF to Audiobook converter

### ISSUE THREAD

**Issue by sonaliBedade** [prathimacode-hub/Awesome_Python_Scripts#99]
Title | About | Name | Label | Assignee
----- | ------ | ------- | ------ | ---------
PDF to Audio book | Creating an audio book from a pdf | Sonali Bedade | Feature Request | 

- [x] LGM-SOC'21 Participant

**Comment by prathimacode-hub** [comment]
Can you elaborate the issue? @sonaliBedade

**Comment by sonaliBedade** [comment]
The input will be in the form of a PDF and on running the code, the entire text in the PDF will be read out like a text to speech converter does

**Comment by prathimacode-hub** [comment]
That's fab.
