### ISSUE TITLE
Add Bit Coin Mining Script 

### ISSUE THREAD

**Issue by NEERAJAP2001** [prathimacode-hub/Awesome_Python_Scripts#993]
# Aim
The objective of this script is to mine Bitcoin.

# Details
It's a script to mine bitcoin but It actually won't reward any bitcoin as the difficulty level is 20 which requires huge processors for rewarding.
So, It's a fun project to understand how hashing, etc works.
I will give complete details in a pdf file to understand everything from scratch.
Thanks.

I'd Like to work on this issue as part of the Hacktoberfest-21

**Comment by prathimacode-hub** [comment]
Issue assigned to @NEERAJAP2001
